### ISSUE TITLE
[Errata] NPC Reload Action Change

### ISSUE THREAD

**Issue by Kl0ndike** [AshleyMoni/Lancer-Community-Edition#107]
**The Problem:**
Current Reload Action is stated as a Quick Action and reloads 1 weapon.

**The Solution:**
Move Reload to the Full Action section and have it reload all weapons.

**The Location:**
Page 348.

**The Ratification:**
Screenshot: https://cdn.discordapp.com/attachments/531498621586374656/532307774168629278/Screenshot_20190109-102012.png

**Comment by KaiTave** [comment]
Corrected in 1.8.5
