### ISSUE TITLE
[RAI] [RAW] [needs dev input] LoS Rules unclear

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#108]
**The Problem:**
The pilot explicitly has LoS that they lose when they sit down in a Mech, but the Mech does not explicitly have LoS. The thread seems to end with the pilot losing LoS as they sit down. 

**The Solution:**
Explicitly state that a Mech has LoS when it is activated, possibly also state that it loses LoS when it is shut down. 

**The Location:**
Pages 63-64

**Comment by KaiTave** [comment]
Clarified in 1.8.5
