### ISSUE TITLE
[RAI][dev input needed] Electronic Systems clarification

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#109]
**The Problem:**
Reference to "Electronic Systems" in UNAVOIDABLE_VOID rules block is ambiguous, although it also seems to be mentioned in the  Dummy Switch Talent (Infiltrator Rank II) and the Systems Mech Skill descriptions.

**The Solution:**
Clarify what counts as an "electronic system" for the purposes of these abilities. Most pressingly, do mech sensors count as "electronic systems"?

**The Location:**
Unavoidable Void pg 222, Systems pg 64, Dummy Switch pg 127

**Comment by KaiTave** [comment]
UNAVOIDABLE_VOID is no longer core rules material as of 1.8.5
