### ISSUE TITLE
[Typo] Sample pilot Oda has errors with the system point spending at LL0

### ISSUE THREAD

**Issue by azhais** [AshleyMoni/Lancer-Community-Edition#11]
**The Problem:**
He has 6 system points to spend and chooses to spend them on the following:
(2) GMS Pattern A “Apple” HE Grenades x4
(1) GMS Burst type Jump Jet system
(1) Personalizations
(2) GMS Shield Type I

Burst is 2 SP, Grenades are 1 SP and appear to come in packs of 1 not 2

**The Solution:**
He has 6 system points to spend and chooses to spend them on the following:
(1) GMS Pattern A “Apple” HE Grenades x1
(2) GMS Burst type Jump Jet system
(1) Personalizations
(2) GMS Shield Type I

Or any other combination really.

**The Location:**
Example character creation, page 105 of the 1.8 community edition

**Comment by KaiTave** [comment]
This remains in need of looking at as of 1.8.5

**Comment by KaiTave** [comment]
The specifics of this have changed but this precise entry is out of date, so it will be recompiled and re uploaded under new tags.
