### ISSUE TITLE
[Errata] Infiltrator Rank 2 (Dummy Switch) Reword

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#110]
**The Problem:**
Dummy Switch currently has a flavor description present in the rule block "can only be seen with the naked eye".

**The Solution:**
Replace current wording with "it can only be detected through direct line of sight"

**The Location:**
Infiltrator rank 2, page 127

**The Ratification:**
![image](https://user-images.githubusercontent.com/1812965/52875736-af366880-311a-11e9-95e7-7f8f24de1f64.png)

**Comment by KaiTave** [comment]
This text as since been removed as of 1.8.5
