### ISSUE TITLE
[Typo] Ordnance/Ordinance Spelling throughout the book

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#111]
**The Problem:**
Ordnance -- mounted guns; artillery.

Ord**i**nance -- an authoritative order; a decree, a piece of legislation enacted by a municipal authority.

In several places Ordinance is being mistaken for Ordnance, and probably vice versa

**The Solution:**
Correct the spelling in the places it needs correcting

**The Location:**
Ctrl-f for "Ordinance" or "Ordnance", evaluate on a case by case basis

**Comment by KaiTave** [comment]
Still a couple examples of this left in the prerelease to be found.

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.
