### ISSUE TITLE
[RAI] [RAW] Biological tag description and location are somewhat misleading

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#113]
**The Problem:**
The placement of the Biological tag in the NPC tags section combined with the wording "An **NPC** with the biological tag..." might mislead someone into thinking the tag only applies to NPC's

**The Solution:**
Move or copy the tag into the player tags, remove "An NPC" wording

**The Location:**
Pg. 350

**Comment by KaiTave** [comment]
PC pilots have the biological tag as per page 112 of the 1.8.5 document
