### ISSUE TITLE
[RAI]  NPC immunities are inconsistent

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#115]
**The Problem:**
Squad NPC's are immune to grappling and ramming

Swarm NPC's are immune to grappling

Human NPC's are not immune to either

Are mechs supposed to be able to grapple and ram pilots? From the wording of grapple "you attempt to grab hold of an enemy **mech**" and Ram "with the aim of knocking down or
back an enemy **mech**" I'd argue that they are not meant to ram or grapple anything but other mechs.

**The Solution:**
Add the full immunity to all non-mech NPC types, as well as Pilots

**The Location:**
Ram / Grapple Pg. 92
Human NPC Pg. 408, Squad NPC Pg. 410, Swarm NPC Pg. 414

**Comment by KaiTave** [comment]
Swarms and Squads have identical Strength in Numbers traits.  I suspect that human NPCs aren't meant to be immune to grappling or rams but Tom will need to confirm this.

**Comment by KaiTave** [comment]
Addressed in the prerelease.
