### ISSUE TITLE
[RAI] Jump Jet Systems intention and usage

### ISSUE THREAD

**Issue by FranciscoSMM** [AshleyMoni/Lancer-Community-Edition#116]
**The Problem:**
Listed here is the text chat from the Rules-Discussion which was on how the GMS ‘Burst’ Jump Jet System, page 148, actually worked. could it be that the intention was for it to be used as a full speed jump system? How does it work when the actor finishes the boost but it is still in the air? Will it immediately fall or only at the end of turn? If only at the end of turn, could a non-flier mech still move to reach the ground? Could an actor boost and then overcharge for another boost to not fall immediately? If yes then why would it fall if no boost actions were made?

![jump jet systesm1](https://user-images.githubusercontent.com/38992510/53463059-a69c3700-3a24-11e9-8ec4-f213ae4d2f25.PNG)
![jump jet systesm2](https://user-images.githubusercontent.com/38992510/53463060-a734cd80-3a24-11e9-9d1c-2379ea5681f6.PNG)
![jump jet systesm3](https://user-images.githubusercontent.com/38992510/53463061-a734cd80-3a24-11e9-8156-a2eea91e3c04.PNG)
![jump jet systesm4](https://user-images.githubusercontent.com/38992510/53463063-a734cd80-3a24-11e9-9dce-b6750d957d7b.PNG)

**The Solution:**
To solve this we created a suggested text to overwrite the current text on the system:
"when you boost you can jump as far and as high as your speed and count as flying for ignoring obstructions and terrain"

This text was suggested supposing that the intention of the system was to actually modify the jump action.

**The Location:**
GMS ‘Burst’ Jump Jet System is on Page 148
Falling is on Page 86
Jump is on Page 86
Flight is on Page 87-88

**Comment by KaiTave** [comment]
This has since been clarified in the prerelease that you require a landing after using Jump Jets.
