### ISSUE TITLE
[Typo] p86 patch 1.8.5 repairs

### ISSUE THREAD

**Issue by FranciscoSMM** [AshleyMoni/Lancer-Community-Edition#117]
**The Problem:**
The text says: 
Spending 4 repairs **can be spent** to repair a destroyed mech (during a rest only, see below)

**The Solution:**
It could be:
Spending 4 repairs can repair a destroyed mech (during a rest only, see below)

**The Location:**
Page 86 under Rest and Repair right before the last paragraph

**Comment by KaiTave** [comment]
To clarify, the issue here is the redundant nature of "spending 4 repairs can be spent"

**Comment by KaiTave** [comment]
Corrected as of the prerelease.
