### ISSUE TITLE
The pilot creation/advancement section doesn't mention talents at all

### ISSUE THREAD

**Issue by azhais** [AshleyMoni/Lancer-Community-Edition#12]
**The Problem:**
The "Creating a pilot" section completely ignores talents.  It has you doing skills, backgrounds, pilot stats, and gear.  Advancement mentions skill/specialty and grit, but at no point does it talk about taking your starting 3 talents and the 1 talent per level

**The Solution:**
I'd just take some of the stuff from the preamble in the Talent's section and insert it after step 3.

4. **Select Talents** At level 0, a pilot gains three talent points to spend on talents.  At creation these are limited to Rank I.

And add a bullet in Advancement

- Each time you level up, you gain 1 talent point that you can use to acquire a new talent or deepen an existing talent to the next rank.

**The Location:**
1.8 CE page 34

**Comment by Qwertronix** [comment]
Ran into this issue also in the 1.8.5 Pre-Release book. Got confused and only realized characters started with Talents already at LL0 thanks to Comp/Con.

**Comment by Ffzdf** [comment]
Should be resolved as of PR2, pg. 33 for leveling and pg. 52 for LL0 character creation both mention talent points now.
