### ISSUE TITLE
[Typo] 1.8.5: Sparri Lore Section Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#148]
**The Problem:**
"In 3348U, a Union Colonial Mission Evident Recontact **(UCM/ER)** team crashed on Sparr, going down just outside of Ynn’s sphere of influence. The already half-dead team was slaughtered by the warband that arrived to greet them; their ship and NHP, Prudent Interval, were hauled away to Ynn as war spoils.

With no guarantee of its own survival, and seeing limited avenues to pursue its primary goal of
contacting Union, Prudent Interval took an unconventional approach: it used all collated pre- and
post-Fall data on the Yggdrasil and assumed sociocultural/theologic permutations to portray itself
as the local prime deity, Ynneval, and the **U-DoJ/HR** team that had transported it as her djevel -- her demon-jailers that had kept her people from her."

**The Solution:**
The reference to the U-DoJ/HR in the second paragraph should probably be replaced with UCM/ER instead as per the initial paragraph.

**The Location:**
Pages 561-562

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.
