### ISSUE TITLE
[RAI] Assassin NPC Explosives Knives: trait vs system

### ISSUE THREAD

**Issue by Ffzdf** [AshleyMoni/Lancer-Community-Edition#149]
**The Problem:**
The Assassin's Explosive Knives is neither a trait nor a system

**The Solution:**
It seems like it's meant to be a system, mostly because it's Limited. There are other NPC modules that are neither traits nor systems, but it's unclear if this omission is intentional (here or otherwise).

**The Location:**
pg. 366, bottom

**Comment by KaiTave** [comment]
Clarified as of the prerelease.
