### ISSUE TITLE
[Errata] NPC Attack Action Reference

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#151]
**The Problem:**
Both the Ronin's Carbon Fiber Sword and the Ultra template's Hellfire Projector still reference the attack action, which is now depreciated.
**The Solution:**
Clarification to explain how these are intended to work with the new npc Skirmish and Barrage actions.
**The Location:**
pg 406 for the Ronin, 439 for the Ultra template

**Comment by KaiTave** [comment]
Also the Hellfire Projector currently lacks to-hit information in its statblock.

**Comment by KaiTave** [comment]
Corrected in the prerelease.
