### ISSUE TITLE
[RAI] 1.8.5: Balor Swarm Body Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#152]
**The Problem:**
The Balor's Swarm Body system has two clauses that may require additional clarification:

1). "If your mech doesn’t move before the end of this turn, at the end of your turn you project a burst 1 area around your mech."  Does this mean you can move and/or boost and THEN activate this system as your last action of the turn and it still functions, or are you not allowed to move at all on the turn you decide to use this system?

2). "For each turn your mech remains immobile past the first, its damage increases by 3, up to a maximum of 9."  Is this meant to be for each of YOUR turns you remain immobile past the first, or is it including other actors' turns as well similar to how Infiltrator III currently works?

**The Solution:**
Designer input for both of these clauses would make the use of this system much clearer as currently there's some debate over its exact functionality.

**The Location:**
Page 237-238

**Comment by lenaleciel** [comment]
The turn count damage increase has been addressed as of November Release, not entirely sure about the first bullet point.
