### ISSUE TITLE
[Typo] 1.8.5: Typo in Ace Talent

### ISSUE THREAD

**Issue by Qwertronix** [AshleyMoni/Lancer-Community-Edition#155]
**The Problem:**
Ace Talent's Rank II bonus, _**Afterburners**_, shows **"(Rank I)"** next to it, making it look like there are two Rank I benefits and no Rank II benefits. 

**The Solution:**
**_Afterburners_ (Rank II)**

**The Location:**
p. 132 (Talents List)

**Comment by KaiTave** [comment]
Corrected in the prerelease.
