### ISSUE TITLE
[RAI] Markerlight clarification

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#163]
**The Problem:**
The markerlight's current text refers to both "a character" and "an ally." With the recent clarification that you are not your own ally, there is uncertainty as to whether or not you are supposed to be allowed to consume your own markerlight bonus.

**The Solution:**
Correct the text to either refer only to a character or an ally.

**The Location:**
pg. 229

**Comment by KaiTave** [comment]
Clarified as of the prerelease.
