### ISSUE TITLE
[Errata] 1.8.5 GMS Integrated Weapon Core Bonus Errata

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#166]
**The Problem:**
According to Tom, the Integrated Weapon Core Bonus which allows you to add an additional Auxiliary weapon to a mount of your choice is supposed to allow you to fire that weapon in addition to the usual weapons permitted during a skirmish or barrage.  In other words, putting it on an Aux/Aux mount to make it Aux/Aux/Aux should allow you to attack with all three Aux weapons in a single skirmish.

**The Solution:**
This needs to be explicitly clarified in the text of the core bonus as otherwise there's nothing to indicate this is the case.

**The Location:**
Page 158

**The Ratification:**
Tom has approved this, if anyone has a screenshot you can paste it here.

**Comment by lenaleciel** [comment]
![image](https://user-images.githubusercontent.com/49732719/56870079-a8a85500-69d7-11e9-945d-defd9b3f76e6.png)

**Comment by KaiTave** [comment]
No longer relevant as of the prerelease.
