### ISSUE TITLE
[RAI] 1.8.5: Line Shape Ambiguity RAW

### ISSUE THREAD

**Issue by SashaOrlov** [AshleyMoni/Lancer-Community-Edition#167]
**The Problem:**

As RAW, you are not required to connect the 'short edge' of a Line attack to the edge of your mech, you can connect the long edge. This results in being able to fine in various shapes which I can only assume is unintentional.

Example [x] is mech, O is line. Line 5 weapon
OOOOO
.  . [x] .  .
.  .  .   .  .

Related issue: Throughbolt Rounds (pg192) may or may not be subject to this as well.

**The Solution:**
Explicit statement that Line weapons need to connect their 'short edge' to the origin point (usually the mech). Throughbolt Rounds (pg192) may also need the wording corrected to reflect this, although it may also be inspirational to the corrected phrasing required (Throughbolt seems to be less ambiguous about its shape)

**The Location:**
pg 100 Line under Range and Patterns, and possibly where Lines are referenced

**Comment by KaiTave** [comment]
This will likely be clarified further as example illustrations are refined.

**Comment by Ffzdf** [comment]
Illustrations added on pg 99. Possible ambiguity may still exist as "origin" spaces are not specified.
