### ISSUE TITLE
[Typo] 1.8.5: Burn's Column Location on Profiles (and Ambiguity)

### ISSUE THREAD

**Issue by SashaOrlov** [AshleyMoni/Lancer-Community-Edition#168]
**The Problem:**
There is a current lack of consistency to the location of where Burn is written in a weapon/ system's profile. Sometimes it is written in the damage (most weapon entries eg. xd6 + y Burn), but it also shows up as a weapon property in a profile (eg. Tachyon Lance). There should be a consistency throughout profiles as to where Burn is indicated. 

This also creates some ambiguity as Burn causes Burn damage to be inflicted, but Burn damage not necessarily cause Burn condition (pg. 81).

**The Solution:**
Since Burn is a weapon property and a damage type, all weapons that cause Burn should indicate in their weapon profiles in the weapon tag column and not the damage column.

**The Location:**
Various. Weapons and Systems which inflict Burn

**Comment by KaiTave** [comment]
"This also creates some ambiguity as Burn causes Burn damage to be inflicted, but Burn damage not necessarily cause Burn condition (pg. 81)."

You can't take Burn damage without having the Burn condition.  The failed Engineering check doesn't apply the condition, the condition is applied upon being hit by a weapon with Burn.  The check is only to _clear_ the condition.

**Comment by lenaleciel** [comment]
This appears to be fixed as of November Release.
