### ISSUE TITLE
[RAI] Lancaster MULE Harness Inconsistency

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#17]
**The Problem:**
The Lancaster's MULE Harness system says it "carry a total number of actors whose total size is less than your own" but the given parenthetical example contradicts this by giving examples which imply that you can carry a number of actors whose total size is EQUAL TO or less than your own (so size 1 = 1 size 1 actor, two size 1/2 actors).

**The Solution:**
We need a ruling on which of these is correct, less than or equal to/less than.

**The Location:**
Page 167

**Comment by Ffzdf** [comment]
Rereading it, it seems like the intention might be that the parenthetical is meant to clarify how to count the size of the actors riding on the mech, not how much capacity it has. Still needs Tom's input tho

**Comment by KaiTave** [comment]
This formula has changed as of 1.8.5
