### ISSUE TITLE
[RAI] Stunned and Automatically Failed Checks

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#170]
**The Problem:**
The latest version of stun found in the prerelease says that a stunned mech automatically fails all hull and agility saves only, while previous versions specified hull and agility checks, suggesting that the intended effect is to have stunned mechs fail both checks and saves, as the concept of saves was just added last edition.

**The Solution:**
Amend the rules text for stunned to include both checks and saves.

**The Location:**
Pg. 115, under the condition stunned

**Comment by KaiTave** [comment]
Corrected in the prerelease.
