### ISSUE TITLE
[Typo] GMS Drone Nexuses Naming

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#171]
**The Problem:**
Currently, the GMS nexus weapons still contain the word Drone in their names even after the 1.8.5 change in naming convention to call weaponized drones Nexuses, despite these weapons having no interaction with the Drone tag.

**The Solution:**
Rename the 2 weapons to something else without Drone in the name, such as the GMS Hunter-Killer Nexus or the GMS Light Nexus, or something similar.

**The Location:**
pg. 160

**Comment by KaiTave** [comment]
Corrected in the prerelease.
