### ISSUE TITLE
[RAI] 1.8.5 Synthetic Muscle Netting Clarification wrt Large Group Grappling Situations

### ISSUE THREAD

**Issue by SashaOrlov** [AshleyMoni/Lancer-Community-Edition#177]
**The Problem:**
Synthetic Muscle Netting
"When grappling or ramming, you always count as the same size as your opponent if your opponent is larger than you, and larger than your opponent if they are the same size or smaller. Your lifting and dragging capacity doubles (your mech can lift objects twice its size and drag objects up to four times its size).

Grapple Rule:
If there are multiple parties involved in a grapple, the same rules apply, but when counting size, count up all opponents of a side in a grapple. For example, if my all and I are both size 1 and grappling a size 2 target together, we would count our total size (2) and could attempt to drag our target around. 

The interaction between a mech with SMN in a large grapple is not clear (does SMN scale to match multiple opponents eg. 2 size 1 vs Blackbeard = Blackbeard size 2?)
There is also the interaction where there are allies from the SMN mech (eg. 4 size 1 vs Blackbeard + 1 size 1 ally. Is the Blackbeard counted as size 3 or 4 in this case?)

**The Solution:**
Wording clarification is needed for SMN entry, but without knowing the RAI for the scale of SMN's grapple size scaling effect I cannot make a suggestion.

**The Location:**
Synthetic Muscle Netting (pg. 170)
Grapple rules (pg. 104-105)

**Comment by KaiTave** [comment]
Clarified as of the prerelease.
