### ISSUE TITLE
[Typo] 1.8.5: Synthetic Muscle Netting Description RAW

### ISSUE THREAD

**Issue by SashaOrlov** [AshleyMoni/Lancer-Community-Edition#178]
**The Problem:**
"When grappling or ramming, you always count as the same size as your opponent if your
opponent is larger than you, and larger than your opponent if they are the same size or smaller. Your lifting and dragging capacity doubles (your mech can lift objects twice its size and drag objects up to four times its size)."

Wording as is implies that it is a continuous check which results in every situation leading to the SMN user being treated as larger size than the opponent.
(If opponent size > you, you == opponent size. 
Then if opponent size = you, you > opponent size)

**The Solution:**
Possible solution:
Reverse the checks. "When grappling or ramming, you always count as larger than your opponent if you are both the same size or smaller, and the same size as your opponent if you are smaller. Your lifting..." This keeps the RAW wording as is, but closes the possible misinterpretation of the original reading.

Other possibilities include formatting for clarity, or separating the sentences to prevent them from running on each other.

**The Location:**
Synthetic Muscle Netting (pg. 170)

**Comment by KaiTave** [comment]
Similarly clarified.
