### ISSUE TITLE
[RAI] Latch Drone Attack Roll

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#179]
**The Problem:**
The latch drone's text says to make an attack roll without saying what kind of attack roll, and thus doesn't specify whether to add grit.

**The Solution:**
Change the text to say "make a ranged attack roll vs evasion 8" or if it's intentionally meant to be a typeless attack roll so as to not interact with anything that interacts with ranged attacks, specify that you add grit to the attack roll.

**The Location:**
Page 178, the Lancaster's Integrated Mount

**Comment by KaiTave** [comment]
Clarified in the prerelease.
