### ISSUE TITLE
[Typo] Inconsistant ordering of systems on Iskander

### ISSUE THREAD

**Issue by grandar-lr** [AshleyMoni/Lancer-Community-Edition#181]
**The Problem:**
Grounding Charges and Repulsor Field appear in one order in the text, and the other in the summary itemization at the top.

**The Solution:**
The ordering should be consistent between them.

**The Location:**
Where can we find it? Page numbers?
pg280 pg281

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.
