### ISSUE TITLE
[Typo] Prerelease: Soft Cover Section Typo

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#187]
**The Problem:**
Soft cover, as the name implies, is typically not solid enough to reliably block ﬁre, but 
causes enough visual interference or reduces proﬁle enough to make aiming **diﬃculty**.

**The Solution:**
Difficulty should read Difficult

**The Location:**
Lancer Core Page 104 in the Prerelease PDF

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.
