### ISSUE TITLE
[RAI] Possible bad-faith Invasion interpretation

### ISSUE THREAD

**Issue by Techhead0** [AshleyMoni/Lancer-Community-Edition#188]
**The Problem:**
The phrase "On hit, your target takes 2 heat and you can choose one of the following, in addition to other options:" being included  can be read as dealing 2 heat and picking an option per invasion system you have installed. Again, absolutely not an intended interpretaion of the rules, I just found it funny.

**The Solution:**
Don't include this boilerplate on every Invasion system, Hacker 2's version is fine.

**The Location:**
Many pages, but Goblin license is demonstrative.

**Comment by Ffzdf** [comment]
My suggestion for the Invasion boilerplate would be as follows:

"Gain the following options for invasion, which you may choose from in addition to other options you have available:"
