### ISSUE TITLE
[RAI] Prerelease: Taro Oda LL0 Build Discrepancies

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#191]
**The Problem:**
The example LL0 build for Taro Oda uses an assortment of equipment that does not work with the stated point costs in the actual GMS equipment catalogue.  At LL0 Oda has 6 SP to spend, and the book gives his example loadout as:

(2) GMS Pattern A “Hex” charges
(1) GMS Burst type Jump Jet system
(1) Personalizations
(2) GMS Shield Type I

However, the Jump Jets are actually 2 SP, not 1, which means that Oda's loadout is 1 SP overcosted.

**The Solution:**
The listed loadout should be changed in some fashion to line up with the SP totals listed in the GMS catalogue so as to be correct for a LL0 Everest.  Other discrepancies in the sample character creation section may be present as well.

**The Location:**
Page 54

**Comment by Ffzdf** [comment]
https://docs.google.com/spreadsheets/d/1d0fBPNRrhVdjlnEIgi8R9aX_Cx8zvAA0PG34M3ik6ic/edit?usp=sharing

Suggested LL0 build for Oda. Replaced Jump Jets with Custom Paint Job. Added Light Alloy/Composite Weapon (Survival Knife), Patch, and Wilderness Survival Kit to his pilot gear, replacing "cooking gear."

**Comment by Ffzdf** [comment]
https://docs.google.com/spreadsheets/d/1t0I0u61iNpem2jeUu62jmWJKBYldRMDu2n2BWJy2yS0/edit?usp=sharing

Suggested LL3 build for Oda. HP up to 27 from 26 (Raleigh base HP increased by 1, up to 10). Save target up to 12 from 10 (adding 2 from GRIT). Talent rank shifted from Leader to Crack Shot (now Leader 2, Crack Shot 3). Raleigh 3 (unused) shifted to Vlad 1 (showcasing license mixing), taking Snare Trap in place of Jump Jets.
