### ISSUE TITLE
[RAI] Prerelease: Lancaster Combat Repair Trait Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#194]
**The Problem:**
The Lancaster's Combat Repair trait essentially allows it to repair a destroyed mech in the middle of a scene rather than waiting for a chance to repair it properly, returning it to 1 structure and 1 HP.  However on page 120 it states "Once repaired, the mech is returned to 1 structure and 1 reactor stress at full HP, no matter how much it had before." 

**The Solution:**
Should the Combat Repair trait be amended to line up with this, or are they meant to have separate effects?

**The Location:**
Page 120, 189

**Comment by BurstingEagernessSoul** [comment]
Clarification wrt Briareous interactions would be good as well. Can Combat Repair repair someone out of CRITICAL mid-combat?

**Comment by lenaleciel** [comment]
Has been changed to say "1 STRUCTURE, 1 STRESS, and 1 HP." as of November Release
