### ISSUE TITLE
[RAI] Prerelease: BRIAREOS Frame Reinforcement Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#195]
**The Problem:**
The current text for BRIAREOS Frame Reinforcement reads in part "When it’s reduced to 0 HP, it is not destroyed, but instead makes a structure check each time it takes damage and cannot regain HP."

**The Solution:**
For clarity's sake, I would like to suggest that the clauses in this sentence be changed so it reads "When it's reduced to 0 HP it is not destroyed, but it cannot regain HP and instead makes a structure check each time it takes damage" or something along those lines.  This is to prevent confusion over whether the "and cannot regain HP" is actually something modifying the preceding "makes a structure check" clause, i.e. you only make a structure check IF you cannot regain HP.

**The Location:**
Page 177

**Comment by lenaleciel** [comment]
Fixed by splitting the "can't gain HP" bit into a new sentence as of November Release.
