### ISSUE TITLE
[Typo] Prerelease: UNCLE Fluff Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#196]
**The Problem:**
"but pilots lucky enough to field stable systems **sweared** by UNCLE’s task efficacy and parallel-track reasoning."

**The Solution:**
"but pilots lucky enough to field stable systems **swore** by UNCLE’s task efficacy and parallel-track reasoning."

**The Location:**
Page 200

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.
