### ISSUE TITLE
[RAI] Prerelease: UNCLE-class Comp/Con Classified As Full AI, Can Be Unshackled

### ISSUE THREAD

**Issue by Amets-Estibariz** [AshleyMoni/Lancer-Community-Edition#197]
**The Problem:**
The last paragraph of UNCLE's rules text states it is a full AI and can be unshackled in combat, neither of which are true for a Comp/Con unit. "UNCLE is a full AI but can’t control your mech if it becomes unshackled, just the associate weapon. Instead, if UNCLE becomes unshackled, it chooses the target of this attack (and whether to make an attack or not)"

**The Solution:**
Remove the reference to UNCLE as a full AI. Either make it unable to be unshackled like the Dummy Plug or add clarification that unshackling UNCLE is not narratively the same as unshackling a true NHP.

**The Location:**
Page 201, UNCLE-class C/C

**Comment by melodycwatson** [comment]
This has been clarified (UNCLE can no longer become unshackled).
