### ISSUE TITLE
[RAI] Prerelease: Bonus Damage Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#198]
**The Problem:**
One of the longer standing questions and ambiguities surrounding bonus damage has been whether or not bonus damage can be applied to things that do not normally deal bonus damage such as tech attacks, grapples, etc.  The given rule of thumb which has been followed has generally been "not if the attack in question deals no damage" as untyped bonus damage, which is most of it, has to be of a type that the attack itself deals, and if that attack deals no damage then there's no type of damage for the bonus damage to be.

However Nuclear Cavalier 2 has been changed to specifically be Energy damage, which now suggests it may be compatible with tech attacks, grapples, etc.  So while this could simply be an issue focused on that talent in particular, it may also something that needs broader clarity when defining how bonus damage works in general.

**The Solution:**
Is something like Nuclear Cavalier 2 meant to work with non-damaging attacks?  If non-damaging attacks aren't meant to benefit from bonus damage then that may need to be explicitly stated in the definition for how bonus damage works.

**The Location:**
Page 96

**Comment by lenaleciel** [comment]
![image](https://user-images.githubusercontent.com/49732719/63717503-6e7c8200-c816-11e9-9789-d95d910960b3.png)
Tom has weighed in on this during a conversation on whether or not Nuclear Cavalier applied to rams and grapples. He didn't say anything specifically about how untyped bonus damage would work with non-damaging attacks though.

**Comment by lenaleciel** [comment]
As of November Release, Bonus Damage now explicitly only can apply to Melee and Ranged attacks, and if there's no specified damage type, it defaults to Kinetic. Presumably this means things like Rams and Grapples can now get Bonus Kinetic Damage without some sort of Siege Ram work around.
