### ISSUE TITLE
[RAI] Prerelease: Kai Bioplating Affecting Only Checks

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#199]
**The Problem:**
Kai Bioplating currently only gives its bonus to Agility checks instead of checks and saves as the other stat-related core bonuses do.

**The Solution:**
This should likely be amended to affecting both checks and saves in line with the other similar core bonuses.

**The Location:**
Page 199

**Comment by lenaleciel** [comment]
Fixed as of November Release.
