### ISSUE TITLE
[Typo] Engagement roll mention

### ISSUE THREAD

**Issue by Techhead0** [AshleyMoni/Lancer-Community-Edition#2]
**The Problem:**
Narrative play contains the line: "Once you’ve made your engagement roll"
Engagement rolls do not exist.

**The Solution:**
Change text to "Once you've been breifed" or similar? I don't have an exact replacement wording at the moment.

**The Location:**
Narrative play, first paragraph, page 43

**Comment by AshleyMoni** [comment]
Hmmmm, we may want to pass this by Tom.

**Comment by aritsune** [comment]
Isn't this referring to the optional engagement roll in the GM toolkit (page 318)?

**Comment by KaiTave** [comment]
As of 1.8.5, the "engagement roll" mention no longer appears to be a thing.
