### ISSUE TITLE
[Typo] Stasis Barrier Flavor Text Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#20]
**The Problem:**
"a Stasis Barrier is a **deplorable** wall of antigravity"

**The Solution:**
"a Stasis Barrier is a **deployable** wall of antigravity"

**The Location:**
Page 279

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.

**Comment by KaiTave** [comment]
Noted as amended by the editor.
