### ISSUE TITLE
[Errata] Prerelease: Drake's Blast Plating Should Resist Bursts

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#200]
**The Problem:**
The Drake's Blast Plating trait does not currently resist bursts.  

**The Solution:**
This should be included.

**The Location:**
Page 185.  There may be other instances throughout the book of "resistance to AoE damage/resistance to non-AoE damage" that needs to be updated to include bursts as well, such as the Infantry Squad NPC for example.

**The Ratification:**
rules boyToday at 1:53 PM
OH
drake should resist bursts
that's an omission

**Comment by lenaleciel** [comment]
Fixed as of November Release to include Blast, Burst, Line, and Cone on both the Drake and the Squad NPC.
