### ISSUE TITLE
[RAI] Prerelease: Hydra Hunter Drone Still Rolls to Lock On

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#202]
**The Problem:**
The Hydra's Hunter Drone, one of its OROCHI drones, currently reads "Characters adjacent to this drone cannot benefit from invisibility. In addition, on its turn, the Drone can make a Lock On attack using your systems score at a character adjacent to it."  However Lock On is no longer an attack, instead being a deterministic action.

**The Solution:**
This drone's text should likely be revised to take this change to Lock On into account.

**The Location:**
Page 270

**Comment by lenaleciel** [comment]
Fixed in November release, changed to force System Saves to inflict Lock On rather than to use the Lock On action.
