### ISSUE TITLE
[RAI] Prerelease: Shroud Mine Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#203]
**The Problem:**
The Shroud Mine option for the GMS Pattern-A Smoke Charges currently reads "The affected area becomes soft cover for all characters and objects within. **Lasts until the end of the activating character’s turn**, then disperses."  As written, this means that at the end of the same turn in which the mine is activated it immediately disperses, providing no benefit.

**The Solution:**
This should likely read "The affected area becomes soft cover for all characters and objects
within. **Lasts until the end of the activating character’s next turn**, then disperses." instead but designer input should clarify.

**The Location:**
Page 174

**Comment by lenaleciel** [comment]
Fixed as of November Release.
