### ISSUE TITLE
[RAI] Armor Lock Grapple Interaction Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#204]
**The Problem:**
The Nelson's Armor Lock system reads "When you take the Brace reaction, until the end of your following turn, any attacks against you are made with 1 additional Difficulty, you can’t fail agility or hull saves or contested checks, be knocked back, grappled, knocked prone, or moved by any external force smaller than size 5. **You also immediately end any grapples currently affecting you.**"  However most mechs, while grappled, can't use reactions which makes this clause somewhat unusable.

**The Solution:**
Tom has stated this may be an oversight, so official clarification or removal of the text in question may be necessary.

**The Location:**
Page 195

**Comment by lenaleciel** [comment]
This has been fixed as of November Release.
