### ISSUE TITLE
[RAI] Prerelease: Paracausal Weapon Mod and Systems/Talents Which Self-Reduce Damage

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#205]
**The Problem:**
The Paracausal Weapon Mod states "Choose one weapon. This weapon gains the Overkill tag and damage from this weapon cannot be reduced in any way, by armor, resistance, or any other kind of damage reduction."  Does this include talents and systems which cause attacks to deal half damage as a tradeoff, such as Heavy Gunner or SCYLLA?

**The Solution:**
Designer clarification as to the intent of this interaction is required as there is currently some confusion over it given that various talents and systems which did not used to self-reduced damage now do so.

**The Location:**
Page 315

**Comment by Ffzdf** [comment]
It's unclear if halving damage is meant to count as a "reduction," similar to how immunity doesn't reduce damage (and therefore cannot be bypassed by paracausal mod).
