### ISSUE TITLE
[RAI] Snare Trap Check/Save Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#207]
**The Problem:**
The Vlad's Snare Trap states "The target must pass a **hull check** or take 1d6 AP kinetic damage and become immobilized."  Should this be a hull save instead?

**The Solution:**
Designer input to clarify whether this is meant to be a save or actually a check is required.

**The Location:**
Page 209

**Comment by lenaleciel** [comment]
Fixed, changed to a Hull Save in November Release.
