### ISSUE TITLE
[RAI] Prerelease: Hacker Level 2 Talent Heat Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#208]
**The Problem:**
The level II Hacker talent Safecracker gives players a number of options for Invasion.  As of the prerelease draft, most systems and abilities which grant such additional options also explicitly deal 2 heat when used, but Safecracker currently does not.  Should it also deal 2 heat on hit as well?

**The Solution:**
Designer input would help clarify whether this is an intentional design decision or an oversight to be amended.

**The Location:**
Page 156

**Comment by lenaleciel** [comment]
Fixed as of November release, with all Invasion options being unified in granting options and not including anything about the base 2 heat.
