### ISSUE TITLE
[RAI] Prerelease: Beckoner and Drones Interaction Clarification/Amendment

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#211]
**The Problem:**
Currently various Invasion options work on drones without restrictions, including Beckon, which allows one to teleport and reposition with placed allied drones.  Per Tom, this is not an intended interaction.

rules boyToday at 9:39 PM
yeah you shouldn't be able to beckon drones

**The Solution:**
Designer input to head off this interaction, and possibly other similar interactions as well, is required.

**The Location:**
Page 276

**Comment by BurstingEagernessSoul** [comment]
The change should probably be to Beckon specifically, since being able to drop Logic Bomb or Summon on a drone seems RAI.

**Comment by lenaleciel** [comment]
Fixed as of November Release, Beckoner explicitly targets Mechs your size or larger now.
