### ISSUE TITLE
[RAI] Prerelease: Integrated Ammo Feeds, Grease Monkey I and III Clarifications

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#213]
**The Problem:**
Presently there has been some confusion keeping straight the various specific functions of these three items in the current draft as while they all serve to add additional uses of limited equipment, what they restore is all different within each one:

Integrated Ammo Feeds: Limited Systems and Deployables

Grease Monkey I: Limited Weapons and Deployables

Grease Monkey III: Limited Weapons and Systems

In addition to this, "Systems" and "Deployables" being separate entries is unintuitive because there is, that I am aware, no such thing as a non-system Deployable.  All Deployables are Systems, though it's true that not all limited Systems are Deployables.  But in the case of Integrated Ammo Feeds specifically there is a redundancy present as simply saying "limited Systems" could cover Deployables by default.

**The Solution:**
These specific divisions between what each of these options provides may be designer intended.  Nonetheless I would like to request designer input to determine if any confusing redundancies can be cleared up, or if any changes are desired in the implementation of these core bonuses and/or talents.

**The Location:**
Page 155-156, page 289

**Comment by lenaleciel** [comment]
As a related note, the name "Integrated Ammo Feeds" specifically not affecting weapons is rather bizarre, the things that would presumably be using ammo. The fluff sort of addresses things, but if the intent is to only cover systems and deployables, it may be a good idea to change the name.

**Comment by lenaleciel** [comment]
All three have been changed to specify Weapons and Systems as of November Release, except for Grease Monkey I, which said Limited and Deployable Weapons and Systems. However, that seems to have been addressed in #493 so this issue appears to be fixed.
