### ISSUE TITLE
[RAI] Prerelease v.2 Annihilator and Arc Projector

### ISSUE THREAD

**Issue by BurstingEagernessSoul** [AshleyMoni/Lancer-Community-Edition#214]
**The Problem:**
Unclear how both interact with bonus damage. Also, unclear if the Annihilator rolls a separate attack for the Burst 1 or uses the original.

**The Solution:**
More precision in text for both. Potentially a specific callout for how they interact with bonus damage.

**Comment by Ffzdf** [comment]
Current wording also suggests that the Annihilator's attacks can proc indefinitely.

Should probably specify that only the initial attack can proc the Burst, unless infinite recursion is intended (doubtful). Clarification is also needed on heat generation for the Annihilator.

**Comment by lenaleciel** [comment]
Bonus Damage is clarified for both weapons as of November release.

**Comment by lenaleciel** [comment]
Leaving a comment so that Kai can close this, opening a new November release issue specifically for the Annihilator's recursion and heat. It's #584
