### ISSUE TITLE
[RAI] Prerelease: Construct Eidolon Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#216]
**The Problem:**
Presently the Goblin's Construct Eidolon invasion option reads "The construct is a size 3 object that can look like almost anything. It can be used as hard cover by allies, but not enemies,"  Bearing in mind that as established in prior versions of the game that you do not count as "an ally" for purposes of systems which affect allies, as written someone who uses Construct Eidolon cannot themselves benefit from the cover it creates.  Is this intentional or an oversight?

**The Solution:**
Designer clarification would be helpful in determining the intent of this.  If it's meant to allow the user to benefit from the created cover, a simple fix is to simply say "it can be used as hard cover by yourself and allies" or something along those lines.

**The Location:**
Pages 259-260

**Comment by melodycwatson** [comment]
This wording has been clarified.
