### ISSUE TITLE
[RAI] Prerelease: Lack of Explicit "You Are Not Your Own Ally" Explanation

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#217]
**The Problem:**
In the prior draft of the game the game explicitly stated "You do not count as an allied character to yourself" but in the current version of the rules this sentence no longer appears to be present.

**The Solution:**
I would suggest adding this clause back into the text as it is a common question which frequently arises and being able to specifically point to something which clarifies this has been tremendously useful.  I recommend the section on Characters and Objects as a suitable place.

**The Location:**
Page 86

**Comment by BurstingEagernessSoul** [comment]
Related, a note that your *mech* counts as your ally (and vice versa) while you are on foot would probably be good.

**Comment by melodycwatson** [comment]
This has now been clarified.
