### ISSUE TITLE
[RAI] Prerelease: Custom Paint Job Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#218]
**The Problem:**
Currently the way the Custom Paint Job system works is open to a potentially abusive interpretation where even once it's been expended you could still opt to destroy it as part of a critical damage result because it isn't technically an expended Limited system.  While this is clearly not the intent, the wording at present leaves it a bit ambiguous.

**The Solution:**
My suggestion for a rewording is as follows: "When you take a point of structure damage, roll a d6. On a 6, you don’t take the structure damage, and heal to 1 HP, as the hit simply ‘scratched your paint’ instead. This system is then destroyed and can only be repaired during a full repair."

**The Location:**
Page 173

**Comment by BurstingEagernessSoul** [comment]
Could also use the slight clarification that the system is "spent" when you roll a 6, not just when you roll the die, if that is the intended case.

**Comment by melodycwatson** [comment]
This wording has now been clarified.
