### ISSUE TITLE
[Typo] Lancaster Cable Winch Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#220]
**The Problem:**
"Characters using the cables to climb without a speed penalty."

**The Solution:**
"Characters can use the cables to climb without a speed penalty." or "Characters using the cables to climb do so without a speed penalty."  In the previous draft this sentence read "Characters using the
cables to climb move at normal speed." which might also work.

**The Location:**
Page 191

**Comment by melodycwatson** [comment]
Fixed. :)
