### ISSUE TITLE
[RAI] Prerelease: Swallowtail Cloaking Field Clarification/Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#221]
**The Problem:**
The changelog for the prerelease draft states the Swallowtail's "Cloaking Field now slows instead of immobilizes."  However in the actual text for the system, it currently neither slows nor immobilizes, allowing users to move and boost unhindered with it active.

**The Solution:**
Was this intended, or an oversight?  If the Cloaking Field is intended to slow the user while active, it needs to have that clause added to the final text.

**The Location:**
Page 247

**Comment by melodycwatson** [comment]
This has now been clarified (it causes Slowed).
