### ISSUE TITLE
[RAI] Prerelease: Reliable Miss Damage Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#222]
**The Problem:**
The description on the Reliable tag is currently ambiguous on whether the damage dealt when a Reliable attack misses inherits the weapon's other properties such as the AP tag.

**The Solution:**
Tom has stated in the past when asked that the answer is that the miss damage on Reliable weapons does not benefit from tags such as AP, but this should probably be clarified in the tag itself.

**The Location:**
Page 128

**Comment by melodycwatson** [comment]
This is now clarified.
