### ISSUE TITLE
[RAI] Prerelease: Jockeying Maintenance Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#223]
**The Problem:**
It is presently slightly ambiguous what action, if any, is required to maintain a jockey on a mech.  The section reads "Attempting to jockey takes a full action. The turn you successfully jockey, you can choose one of the below for free, and repeat one each turn after that you continue to jockey as a full action." and some confusion has arisen over the phrase "that you continue to jockey as a full action," which could imply that jockeying requires a full action to maintain in addition to another interpretation which is that remaining jockeying is free, but choosing an option to inflict on the mech you're riding is a full action.

**The Solution:**
A clarification as to whether maintaining jockeying requires the expenditure of a full action or is maintained for free would help disambiguate this.

**The Location:**
Page 112

**Comment by melodycwatson** [comment]
This has now been clarified.
