### ISSUE TITLE
[Typo] Prerelease: Anti-Material Rifle Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#224]
**The Problem:**
In several places throughout the book there are entries for an Anti-Material Rifle.  However, the actual correct spelling for this particular weapon should be Anti-Materiel Rifle with an "e."

**The Solution:**
Replace all extant mentions of an "Anti-Material Rifle" with "Anti-Materiel Rifle."

**The Location:**
Pages 53 (sans hyphen), 54 (sans hyphen), 171, 432 (both with and sans hyphen), 433

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.

**Comment by KaiTave** [comment]
Noted as amended by the editor.
