### ISSUE TITLE
[Typo] Prerelease: Sylph Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#225]
**The Problem:**
In the pilot gear section, the SSC Sylph is misspelled as SSC **Slyph**

**The Solution:**
This should be "Sylph."

**The Location:**
Page 156

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.

**Comment by KaiTave** [comment]
Noted as amended by the editor.
