### ISSUE TITLE
[RAI] Prerelease: Exposed and Burn Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#226]
**The Problem:**
In the prerelease draft burn is now described as a "special damage type."  This has led to a bit of ambiguity regarding how burn interacts with things which reduce or double damage, such as the new Exposed status.  It's implied via the rules for Brace that if something is meant to reduce burn that it has to explicitly say so instead of simply saying "damage," but for clarity's sake it would perhaps be useful to state that Exposed does not double the amount of burn taken.

**The Solution:**
"Exposed
- An exposed character takes double damage (not burn or heat)" 

is one possible way of simply clarifying matters if this is indeed the intent.

**The Location:**
Page 113

**Comment by Ridiculon** [comment]
Updated terminology may help resolving this issue

**Comment by lenaleciel** [comment]
Exposed now explicitly doubles Kinetic, Explosive, and Energy damage.

**Comment by lenaleciel** [comment]
...And thus this issue is fixed. Double commenting so that Kai can catch this in my current November Release issue run.
