### ISSUE TITLE
[RAI] Prerelease: NPC Weapon, System, and Trait Consistency

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#227]
**The Problem:**
All NPC abilities should fall under one of three broad categories, Weapons, Systems, or Traits.  This is both for clarification as well as interaction with various rules such as critical system damage or abilities which mention weapons or systems specifically.  However, currently many NPC abilities are not tagged with any of these.  Weapons are generally easy to identify given that they come with specific statblocks, but examples of entries missing the System or Trait tag include things such as the Barricade's Rapid Extruder and Mag Mines.

**The Solution:**
For consistency and rules interaction, all NPC modules which are not weapons should be appended as either Systems or Traits where necessary.

**The Location:**
A rough list courtesy of Ffzdf can be found at the following gdocs link: https://docs.google.com/document/d/1Lye2PDMqXeEZ3N4g5Nw2JfYZeWmlq0m_JgzMMEpgaOI/edit

**Comment by melodycwatson** [comment]
All NPC abilities have now been classified. :)
