### ISSUE TITLE
Potential Timing Clarification with Lock ON

### ISSUE THREAD

**Issue by william-w-armstrong** [AshleyMoni/Lancer-Community-Edition#232]
There are some potential timing issues around a few non-'reaction' reactions. For the most part, these are triggers that modify an existing attack or action, rather than trigger a new one. 

I asked on the Discord and got two answers from two purple names, so it seems there is some genuine confusion here.

The general rule is - 

"Actions and reactions themselves cannot be split into parts, and each action must resolve before the next takes effect. Reactions, for example, usually resolve after their triggering action
completes."

The Specific Rule for Hacker 1 - 
"Snow_Crash (Rank I): When you consume Lock On as part of a tech attack, on hit, your target chooses whether it takes an additional 2 heat or is pushed 3 spaces in a direction of your choice."

Does this happen before the Hacker decides which tech attack to use? Or which version of Invade to trigger? Is it the moment the LockOn is consumed? Or should this read, "After a successful Tech Attack in which you consumed a Lock On....."

Same issue with Drone Commander 2 - "Energized Swam (Rank II): Once a round, when you consume Lock On with any attack..."
Does this resolve before or after the attack?

Suggested Fix - alter these to specify before or after as desired. Or, add a general case rule from many other games that says something to the effect of :
"When an action triggers multiple effects, the acting player chooses the order they are resolved in unless the rules specify when they occur. For example, 'When consuming Lock On' could be at any point during the action that consumes the Lock On, while 'After you attack, but before you roll to hit' would be after the action is taken and a target declared, but before any dice are rolled or results applied."

**Comment by melodycwatson** [comment]
These instances have been clarified, and a general clause about action resolution has been added.
