### ISSUE TITLE
[RAI] Cone Template Illustration Clarification/Suggestion

### ISSUE THREAD

**Issue by Ffzdf** [AshleyMoni/Lancer-Community-Edition#233]
**The Problem:**
The Cone 5 illustration is not consistent with the Cone 3 illustration, also has an effective range of 6 to certain spaces which doesn't seem correct.

**The Solution:**
The top two hexes should not be included, and the leftmost and rightmost hexes should be shifted down one space. Additionally, the left and right hexes of the Cone 3 pattern should be included in the same spots in the Cone 5 pattern.

**The Location:**
pg. 99, AoE illustrations on hexes

**Comment by KaiTave** [comment]
Illustrations of a Cone 7 would be helpful as well, along with potential illustrations showing sizes and AoE templates for square grid maps as well.

**Comment by Ffzdf** [comment]
Courtesy of Zahel from pilotNET, Cone 5 and Cone 7, respectively
![](https://cdn.discordapp.com/attachments/426288556902842368/593588610419261468/unknown.png)

![](https://cdn.discordapp.com/attachments/426288556902842368/593585113686605824/unknown.png)
