### ISSUE TITLE
[RAI] Protocol duplication.

### ISSUE THREAD

**Issue by Saytael** [AshleyMoni/Lancer-Community-Edition#234]
**The Problem:**
Protocols, as free actions, are legally allowed to be duplicated within a given turn. For some systems this is a non-issue, but becomes problematic in the case of systems such as the AMATERASU-class NHP and Annihilation Nexus.

**The Solution:**
1A. Limit problematic protocols specifically to 1/round activation, or
1B. Make each protocol inherently non-duplicable within a turn,
2. Limit Annihilation Nexus protocol to trigger only on firing from the barrage action, not just firing it. 

**The Location:**
Action limitations are outlined on pg. 91.
Amaterasu class NHP is located on pg. 329-30.
Annihilation Nexus is located on pg 276-77.

**Comment by Koleos4** [comment]
The Protocol tag is also defined on page 129, FWIW.

**Comment by lenaleciel** [comment]
Clarification in whether or not you are allowed to use multiple different protocols in a turn in general and whether it still counts as "at the start of your turn" after using a protocol and nothing else would be appreciated for the sake of limiting confusion.

**Comment by lenaleciel** [comment]
As of December Release, each Protocol can only be taken once per turn.
