### ISSUE TITLE
[RAI] Perma-locked GMS CORE Bonus weapon choice?

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#236]
**The Problem:**
The rule for Integrated mounts says that the weapon installed in the mount cannot be "removed, modified, or duplicated in any way."

The GMS CORE Bonus "Integrated Weapon" gives you a mount "with the capacity for one auxiliary weapon". As written this weapon cannot ever be removed, modified, or duplicated once it has been chosen.

**The Solution:**
Is this interaction intended? If not then some clarification is needed (probably in the CORE Bonus wording).

**The Location:**
Integrated Mount rule pg. 49

Integrated Weapon CORE Bonus pg. 168

**Comment by Ffzdf** [comment]
Should also add clarification on whether or not the mount granted by Integrated Weapon can be used as the "secondary" mount for a Superheavy weapon (likely not intended).

**Comment by Ridiculon** [comment]
![image](https://user-images.githubusercontent.com/1812965/58972859-25bbac80-8784-11e9-9afd-c72059ef6af1.png)
