### ISSUE TITLE
[RAI] Chain Axe Crit Effect Duration Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#237]
**The Problem:**
The Blackbeard's Chain Axe currently reads "On a critical hit with this weapon, your target is Shredded until the end of your current turn" which causes some ambiguity if the chain axe were to critically hit on someone else's turn, such as via an overwatch attack.

**The Solution:**
Tom has stated that the Chain Axe should read "On a critical hit with this weapon, your target is Shredded **until the end of the current turn**" instead.

**The Location:**
Page 181

**Comment by Ffzdf** [comment]
Should be tagged [Errata]?

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.

**Comment by KaiTave** [comment]
Noted and amended by the editor.
