### ISSUE TITLE
[RAI] Annihilator and Annihilation Nexus Ambiguity

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#238]
**The Problem:**
Both the Annihilator and Annihilation Nexus are weapons which, as a consequence of use, can produce secondary attacks.  Currently the way these weapons are worded may lead some to interpret them as allowing for potentially endless recursion of attacks triggering additional attacks, which themselves trigger additional attacks, etc.

**The Solution:**
Both of these weapons merit some sort of clarification to their wording to ensure that it is clear that the secondary attacks generated by their use do not themselves generate further chaining attacks the same way that the Arc Projector does.

**The Location:**
Page 272-273, 323

**Comment by lenaleciel** [comment]
Annihilation Nexus is fine, Annihilator is still ambiguous. Opening a new issue specifically for the Annihilator here. Check #584
