### ISSUE TITLE
[Errata] GMS Turret Drone Clarifications v.2

### ISSUE THREAD

**Issue by BurstingEagernessSoul** [AshleyMoni/Lancer-Community-Edition#242]
**The Problem:**
Turret drone is ambiguous on who needs to be near it.

**The Solution:**
Tom-approved wording from Ffzdf
"This system fires a Turret Drone (size 1/2, 10 HP, 10 Evasion/E-defense) that attaches to any object or surface within sensor range. While attached, you can make the following reaction once for each turret per round.
Turret Attack
Reaction, 1/round per turret
When an allied character within range 10 of a turret hits with an attack, you can cause the turret to deal 3 kinetic damage to that target, as long as the turret has line of sight to that target."

**The Location:**
P 174-175

**The Ratification:**
Tom approved
![Screenshot_20190607-141505_Discord](https://user-images.githubusercontent.com/10291613/59128046-ad451f00-892e-11e9-8cc7-0dc6c2c16ec2.jpg)

**Comment by lenaleciel** [comment]
Fixed as of November Release with the new formatting for Reactions.
