### ISSUE TITLE
[RAI] Prerelease: Tokugawa Core Power Duration Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#244]
**The Problem:**
The Tokugawa's core power, Radiance, presently doesn't list a duration.

**The Solution:**
It should most likely last until the end of the scene.

**The Location:**
Page 323

**Comment by lenaleciel** [comment]
Similar checks should probably be done with each core power: For example, the Barbarossa doesn't explicitly say that you stop charging at the end of the scene, and the Drake doesn't specify a duration either, though the latter may be intentional.

**Comment by lenaleciel** [comment]
Fixed for the Tokugawa and the Drake as of November Release.

**Comment by lenaleciel** [comment]
Issue made specifically for the Barbarossa #586 , you may close this one.
