### ISSUE TITLE
[Typo] Prerelease: Swallowtail Low Profile Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#245]
**The Problem:**
"Your mech can still take other actions as normal (hiding, activating systems, etc) can end this
effect as a quick action."

**The Solution:**
"Your mech can still take other actions as normal (hiding, activating systems, etc) **and** can end this effect as a quick action."

**The Location:**
Page 246

**Comment by melodycwatson** [comment]
Melody here. Dropping in to let you know this has been noted and amended. :)

**Comment by KaiTave** [comment]
Amended per Melody.
