### ISSUE TITLE
[RAI] Prerelease: Burst Launcher Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#248]
**The Problem:**
The Burst Launcher's rules text states "On a critical hit, a target struck by this weapon is impaired until the start of your next turn."  This is a bit unusual since most weapons with on hit/crit effects such as this tend to last until the end of the target's next turn.

**The Solution:**
Is there a particular gameplay or balance reason for this weapon to work this way?  It does mean the debilitating effect of the Burst Launcher's crit effect is less long lasting, and it's also strangely inconsistent with most other similar examples, potentially leading to confusion.  Should it be changed to function "until the end of their next turn" instead?

**The Location:**
Page 227

**Comment by lenaleciel** [comment]
Changed to end of the target's next turn in November Release, fixed
