### ISSUE TITLE
[Typo] Movement Clarification

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#250]
**The Problem:**
Movement does not use any special calculations for diagonals in Lancer, 1 Diagonal = 1 Space of movement.

The only place this is explicitly stated is the Quick Combat Reference. 

**The Solution:**
This should be explained in slightly more detail in the actual movement section to prevent confusion.

**The Location:**
Quick Combat Reference pg. 90
Movement Section pg. 92

**Comment by Ffzdf** [comment]
Currently, it seems to be up to the table to decide how to handle it, and I think it's fine that way. But whether or not that's meant to be the case, I agree that it should be clarified.
