### ISSUE TITLE
[RAI] Infantry Squad controls 4 vertical spaces

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#253]
**The Problem:**
The Infantry Squad's size 4 means they control 4 spaces up from their 4x4 horizontal spaces. This leads to some situational dissonance when determining weapon range and LoS to/from the squad (e.g. they can see over size 3 walls, flying mechs with War Pikes can melee them at height 7, etc.)

**The Solution:**
A line stating that the squad is considered size 1/2 for spaces it controls vertically. Or just that it is 1 space tall.

**The Location:**
Page 460 in PR2 itch.io PDF

**Comment by Ffzdf** [comment]
I've actually been considering that it might be nice to overhaul how Infantry Squad size works.

1. have them take up a number of spaces that don't have a set shape, but just all need to be connected to at least one other space of the squad

2. have the number of spaces they occupy scale up and down with their current HP to represent squad members being neutralized (similar to how they fire fewer shots at half HP)

3. consider making them smaller overall
