### ISSUE TITLE
[RAI] Pre-release: Hydra's Hunter Drone references it's own turn.

### ISSUE THREAD

**Issue by hellowitchy** [AshleyMoni/Lancer-Community-Edition#255]
**The Problem:** The Hydra's OROCHI Hunter Drone currently reads "In addition, on its turn,
the Drone can make a Lock On attack using your systems score at a character adjacent to it". But Drones do not have their own turns, instead acting on the players turn if they have any actions. Language could lead to confusion.

**The Solution:** It should instead read "In addition, on your turn, ..."

**The Location:** Page 270

**Comment by lenaleciel** [comment]
Fixed in November Release, now works as a Reaction on the turns of other characters that get close.
