### ISSUE TITLE
[RAI] Prerelease: Pilots Still Lack a Loading Action

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#256]
**The Problem:**
Pilots currently still have no way to reload weapons with the Loading tag such as heavy pilot weaponry given that they utilize a specific set of curated actions which does not include Stabilize.

**The Solution:**
Tom has stated before that Pilots should have their own particular Reload action but this does not appear to have been incorporated into the game yet.

**The Location:**
Page 111

**Comment by Ffzdf** [comment]
![image](https://user-images.githubusercontent.com/46762018/59658850-6e9f3800-916a-11e9-856e-8f2ec3c5ca8e.png)
This screenshot dates to 1.8, but I believe it is still the intended way for pilots to reload their weapons.

**Comment by lenaleciel** [comment]
Finally fixed in November Release!
