### ISSUE TITLE
[RAI] Prerelease: Engineer Talent Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#257]
**The Problem:**
The Remove Reactor Shielding option under Engineer II states "Removing reactor shielding
A ranged prototype weapon can fire as a cone 3 weapon, a line 5 weapon, **or a blast 1
weapon (choose when you fire).**"  Ranged blast weapons generally need a range value as well in order to determine how far away the blast can be placed.

**The Solution:**
Designer input is necessary to clarify how this functions.  Should it be a blast 1 weapon within range 10?  If so, that may need to be stated clearly to avoid confusion.

**The Location:**
Page 154

**Comment by Jay-Iles** [comment]
Fixed, confirming the Range 10 remains in place.
