### ISSUE TITLE
[Typo] Prerelease: IPS-Northstar Chapter Opener Typos

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#258]
**The Problem:**
"once competing firms, **each balanced opposed to one another**"

**The Solution:**
I'm unsure what the actual correction ought to be, but the highlighted portion is a bit awkward and likely could benefit from a minor rewrite.

In addition there are several instances in this section of "IPSN" when the abbreviation/acronym used throughout most of the book is hyphenated, i.e. "IPS-N" including within this very same section.

**The Location:**
Page 176

**Comment by melodycwatson** [comment]
Fixed. :)
