### ISSUE TITLE
[Typo] Prerelease: Drone Commander 3 Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#259]
**The Problem:**
"Allied characters and drones hit by this line can heal 1d6 HP, **and hostile characters caught in the line of effect are damage from the same amount as energy damage (no roll required).**"

**The Solution:**
This should probably read something along the lines of "Allied characters and drones hit by this line can heal 1d6 HP, **and hostile characters caught in the line of effect take 1d6 energy damage (no attack roll required).**"  The designers may want to weigh in on this to double check for precise wording.

**The Location:**
Page 153

**Comment by melodycwatson** [comment]
Fixed. :)
