### ISSUE TITLE
[Errata] //SCORPION v. 70.1 Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#26]
**The Problem:**
Currently the wording of the Gorgon's //SCORPION v. 70.1 is ambiguous and open to misinterpretation.  It reads "If any hostile tech action or attack attempt on you or any adjacent ally fails or misses" which suggests that it might trigger off of ranged or melee attacks, but in prior editions this system has always only ever triggered off of tech-related actions.

**The Solution:**
The sentence should probably read "if any hostile tech action or **tech attack** attempt on your or any adjacent ally fails or misses" instead.  This is confirmed by Tom, but further dev input may be forthcoming.

**The Location:**
Page 240

**Comment by Techhead0** [comment]
![Tom on Scorpion](https://i.gyazo.com/dce83b2276ec4ac9dcc5aa434a42a34e.png)
Supported by Tom, but he's also said "oh yeah I gotta fix scorpion" so dev input tag is staying.

**Comment by KaiTave** [comment]
Fully clarified as of prerelease version.
