### ISSUE TITLE
[RAI] Prerelease: Additional Construct Eidolon Clarifications

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#260]
**The Problem:**
Presently Construct Eidolon's rules text does not specify a range or whether the area of its deployment needs to be a free and open space or not.

**The Solution:**
The text should likely clarify that the deployment range of the construct is within sensor range, as most tech actions tend to be, and specify whether or not the construct needs to be placed in a free space.  In addition to these questions, there have been several other requests for general clarification as to how the construct functions, such as whether it obstructs involuntary movement like knockback for the purpose of interaction with talents such as Juggernaut and so on.

**The Location:**
Page 260

**Comment by Ridiculon** [comment]
I think the Quick Tech rule block saying: "**All tech actions must choose a target within Sensor Range to be effective**, and roll tech attack vs. e-defense if they are an attack." should cover the sensor range issue? Although it should be separated from the tech attack clarification probably.

This line might also do it (and could also use some clarification): "To use a tech action, choose a target in your sensor range (including yourself) and choose one of the following options: [list of universal tech action options]"

**Comment by lenaleciel** [comment]
Reworked into "Construct Other: Ideal Image" in November Release and clarified in all of these regards.
