### ISSUE TITLE
[RAI] Does the Autopod's auto-hit count as an attack?

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#262]
**The Problem:**
There is some ambiguity about whether Autopod's damage counts as an attack when it "automatically hits". The Omnigun is comparable; it does NOT count as an attack, but there is also wording specifying that, along with other rulings that make it a very special case. It still seems unclear as to whether that applies to the Autopod, and thus whether stuff like Hunter Lock would apply to its damage.

**The Solution:**
Specific wording at the end of the descriptive text that states "This does/does not count as an attack.

**The Location:**
Page 263 in PR2 itch.io PDF

**Comment by lenaleciel** [comment]
General clarification as to whether or not things such as burnout insulation, steel assassin, aggressive heat bleed, and fusion hemorrage are meant to work with the autopod would also be appreciated, as the wording between many similar options are not consistant and "it automatically hits but is not an attack" would have different implications for each, Burnout not mentioning attacks at all and only saying on hit, Steel Assassin only referring to attacks and not hitting at all, and the Nuclear Cavalier options explicitly calling out "attack roll(s) that hit."

**Comment by Ffzdf** [comment]
It was also pointed out by Grey that in the Bonus Damage section of the rules, it says it can only be applied to "attacks." However, BURNOUT in this case could still be argued to apply to a non-attacking weapon as a case of specific overriding general.

**Comment by Ffzdf** [comment]
During a recent voice hangout, Tom confirmed that the Autopod _does_ count as an attack. However, this may still be subject to change in the final version.

**Comment by melodycwatson** [comment]
The text has been clarified to state that the autopod does count as an attack.
