### ISSUE TITLE
[RAI] FADE Cloak 'physical' language clarification.

### ISSUE THREAD

**Issue by hellowitchy** [AshleyMoni/Lancer-Community-Edition#263]
**The Problem:** The text in FADE Cloak reads "You cannot interact with the physical world, but neither can it affect you (in terms of damage, etc)." However, physical is not a word within the language of the game. Outside of 'in terms of damage' this is very nebulous about how FADE cloak interacts with other things like tech actions (such as scan, lock on, beneficial ones from either allies or yourself, systems like Sisyphus' _Bend Probability_ , ability to use comms, etc), since there is ample room for interpretation whether these are physical or not.

**The Solution:** Clarify what counts as 'physical' as this is not a word within the game rules language, or reword the system with a list of actions/effects that no longer affect the user.

**The Location:** Page 242.

**Comment by melodycwatson** [comment]
Text has been clarified.
