### ISSUE TITLE
[Typo] Prerelease: "Corpro-State" Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#265]
**The Problem:**
The default term that the Lancer prerelease draft uses for this particular concept is "corpro-state."  There are several typos/inconsistencies to be found such as "**corpo**-state" or "**copro**-state"

**The Solution:**
All instances should read "**corpro**-state."

**The Location:**
Page 462

**Comment by melodycwatson** [comment]
Fixed. :)
