### ISSUE TITLE
[RAI] Drone Commander 3: Usage out of combat

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#267]
**The Problem:**
There doesn't seem to be any limits to the usage of mech systems/traits out of combat beyond the limits they would have in-combat. This isn't a concern except for Drone Commander 3, which would allow the user and its drones to heal the party to full HP without the use of repairs or rests; there are no limits to the healing use.

**The Solution:**
If this isn't intentional, then either we need explicit limits on using mech systems/traits out of combat (would affect ATHENA, Scout Drone, and Siege Ram's potential out of combat), or an explicit limit to this talent rank (e.g. it instead grants stacking/non-stacking temp HP that lasts till the end of the scene; let the blurb on Mech Combat Length page 340 handle "end of scene")

**The Location:**
Page 155 in PR2 itch.io PDF

**Comment by KaiTave** [comment]
If this is an issue then an easier way to address it would be to simply state that Invigorate can only be used in combat.

**Comment by VertigoCharades** [comment]
Seems like Tom weighed in on this a while back: https://cdn.discordapp.com/attachments/426288556902842368/593207330842345482/Screenshot_20190625-173347.jpg
