### ISSUE TITLE
[Typo] Prerelease: Ultra Module Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#268]
**The Problem:**
The Ultra NPC template module Extra Deadly reads "The first Critical Hit the Ultra deals per turn does +1d6 bonus damage/tier **instead just just +1d6**"

**The Solution:**
This should likely read "The first Critical Hit the Ultra deals per turn does +1d6 bonus damage/tier **instead of just +1d6**"

**The Location:**
Page 450

**Comment by melodycwatson** [comment]
Fixed. :)
