### ISSUE TITLE
[RAI] Hidden breaks illogically, needs one more line

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#269]
**The Problem:**
Hidden reads:

 "You immediately lose hidden if you lose the benefit of cover due to line of sight (ie, a mech comes around a wall and can now draw unbroken line of sight to you) or if your cover disappears or is destroyed. If you’re hiding and invisible, you lose hidden if you lose invisibility."

As I read it, this means that if you are both in cover and invisible, you will lose hiding if either of these conditions are met.  

**The Solution:**
Add another line that requires both break conditions to be met if you are both in cover and invisible.

**The Location:**
Hide section, pg. 105

**Comment by Ffzdf** [comment]
There is a discrepancy between the description of the Hide action and the Hide status as listed on pgs 107 and 115 respectively of the latest version of the book.

The Hide action says Boosting breaks the Hidden status, but the Hidden status description lacks this restriction.
