### ISSUE TITLE
[RAI] Heat (Self) timing for non-weapons/Overcharge

### ISSUE THREAD

**Issue by Saytael** [AshleyMoni/Lancer-Community-Edition#270]
**The Problem:**
The Heat (Self) entry in the gear tags on pg. 129 only specifies the timing of the heat gain on weapon attacks, not for other actions, and overcharging.  The timing of heat gain on non-attack actions is ambiguous.

**The Solution:**
-The Heat (Self) gear tag should clarify the heat timing for non-weapons (Protocols, etc)/
-The Overcharge action should clarify whether heat is gained before or after the action is taken.

**Comment by melodycwatson** [comment]
The tag has now been clarified to state that it applies to both weapons and systems.
