### ISSUE TITLE
[Typo] "discretely" should be "discreetly"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#271]
**The Problem:**
In the Mission Goals table on p. 62-63, row 10 of the table reads (emphasis mine): "Assassinate a VIP, **discretely**, or in broad daylight, to send a message"

**The Solution:**
It should read: "Assassinate a VIP, discreetly, or in broad daylight, to send a message"

**The Location:**
p. 63, row #10 of the table

**Comment by melodycwatson** [comment]
Fixed. :)
