### ISSUE TITLE
[Typo] Inconsistent punctuation in Mission Goals table

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#272]
**The Problem:**
In the Mission Goals table, the last 2 entries in the table end in a period, while the others have no punctuation at the end.

**The Solution:**
Either all of the entries in the table should have periods, or none of them should.

**The Location:**
"Mission Goals" table, p. 62-63

**Comment by melodycwatson** [comment]
Fixed. :)
