### ISSUE TITLE
[Typo] Missing period on p. 57

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#273]
**The Problem:**
On the page titled "The Basic Structure of LANCER: Narrative Play", the last sentence is missing a period at the end of the sentence: "The following sections will explain each step in a little more detail. We’ll go in the order you’d usually go during your first session"

**The Solution:**
Add a period, of course: "The following sections will explain each step in a little more detail. We’ll go in the order you’d usually go during your first session."

**The Location:**
p. 57, last sentence

**Comment by melodycwatson** [comment]
Fixed. :)
