### ISSUE TITLE
[Typo] Missing period on p. 63

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#274]
**The Problem:**
The first sentence of the "Stakes" section is missing a period at the end of the sentence: "Once your mission goal is established, you need to determine its **stakes**"

**The Solution:**
Add a period: "Once your mission goal is established, you need to determine its **stakes**."

**The Location:**
p. 63, last sentence

**Comment by melodycwatson** [comment]
Fixed. :)
