### ISSUE TITLE
[Typo] "succesfully" should be "successfully"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#276]
**The Problem:**
The 3rd bullet point under "Stakes" reads (emphasis mine): "Will the players **succesfully** escort the Union DoJ/HR Salvation convoy through the raider-plagued Shatir Reef, or will the humanitarian convoy be torn to pieces like so many others?"

**The Solution:**
It should read (emphasis mine): "Will the players **successfully** escort the Union DoJ/HR Salvation convoy through the raider-plagued Shatir Reef, or will the humanitarian convoy be torn to pieces like so many others?"

**The Location:**
p. 64, 3rd bullet point

**Comment by melodycwatson** [comment]
Fixed. :)
