### ISSUE TITLE
[Typo] Missing hyphens in paragraph 4 of "The Cavalry" (p. 24)

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#277]
**The Problem:**
A sentence in the "The Cavalry" section reads (emphasis mine): "You could be the chosen heir of a **centuries long** atemporal monarchy, destined to inherit your polypatriarch’s chassis."

There's another missing hyphen later in the paragraph (emphasis mine): "A facsimile of a **long dead** pilot, grown in batches of thousands."

**The Solution:**
The first quoted sentence should read (emphasis mine): "You could be the chosen heir of a **centuries-long** atemporal monarchy, destined to inherit your polypatriarch’s chassis."

The other quoted sentence should read (emphasis mine): "A facsimile of a **long-dead** pilot, grown in batches of thousands."

**The Location:**
p. 24, paragraph 4 under "The Cavalry"

**Comment by melodycwatson** [comment]
Fixed. :)
