### ISSUE TITLE
[Typo] Missing word "in" on p. 24

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#278]
**The Problem:**
Under "The Cavalry", the fifth paragraph starts (emphasis mine): "However your character came to **sit the cockpit** of their mech, they are the sum of many parts."

**The Solution:**
It's missing the word "in", before "the cockpit". It should read (emphasis mine): "However your character came to **sit in the cockpit** of their mech, they are the sum of many parts."

**The Location:**
p. 24, fifth paragraph, first sentence

**Comment by melodycwatson** [comment]
Fixed. :)
