### ISSUE TITLE
[Typo] Inconsistent bullet formatting under "Boots on the Ground"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#279]
**The Problem:**
The bulleted list of examples is not actually formatted using proper bullets (it seems to use hyphens instead), and the indentation is inconsistent. (The issue with indentation can't be easily demonstrated here.)

There's also a missing period at the end of the second bullet point, after "in the distance".

**The Solution:**
The proper bulleted formatting (though I'm using Github's formatting options to format this, so you'll have to figure out the proper way to do this in whatever application you're using to typeset it):

> - The mission is to infiltrate a Crownmont — one of the Premier’s city-fortresses — and find a way to open an obscure gate, allowing the rest of their team to sneak in, avoiding a siege. The mission starts as players are creeping up to the facility, advancing under the cover of night through ancient siege trenches, swept by klieg lights and enemy patrols.
> 
> - The mission is to scout for missing colonists in a newly founded colony planet. The mission starts as players are making their way through the jungle and hear unearthly howls rising through the trees in the distance.
> 
> - The mission is to help guard a diplomatic summit, an R&R assignment gifted to them by their contract officer. The mission starts as the players see a suspicious figure dart away from the crowd during the opening ceremony.

**The Location:**
p. 65-66, under "Boots on the Ground"

**Comment by melodycwatson** [comment]
Fixed. :)
