### ISSUE TITLE
[Typo] Punctuation errors in "moment to moment action"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#280]
**The Problem:**
The last sentence of paragraph 2 under "Making Skill Checks" says:

"Or, you could instead cover the moment to moment action - sneaking into vents, hacking doors, disabling guards, etc."

There are actually a few different issues here. "Moment-to-moment action" should be properly hyphenated. In addition, the hyphen in this sentence should instead be an en dash (surrounded by spaces) or an em dash (with no spaces around it). Finally, there shouldn't be a comma after "Or" (even if it is a sentence fragment regardless).

**The Solution:**
The sentence should read:

"Or you could instead cover the moment-to-moment action—sneaking into vents, hacking doors, disabling guards, etc."

**The Location:**
p. 68, paragraph 2, last sentence

**Comment by melodycwatson** [comment]
Fixed. :)
