### ISSUE TITLE
[Typo] Punctuation errors in bulleted list under "Making Skill Checks"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#281]
**The Problem:**
The first bulleted list under "Making Skill Checks" has a few punctuation issues. First off, some of the items (the first and fourth items) are missing a period at the end. Secondly, the first sentence of the second bullet point has some extraneous punctuation at the end:

"Then, figure out consequences if you fail (you lose time, you alert the guards, you get shot, etc), ."

Finally, the bulleted lists in the PDF in general seem inconsistently formatted and indented. The two on this page are properly indented, but use a different format from the list on p. 64, and some of the other lists aren't properly formatted as bulleted lists at all.

**The Solution:**
Obviously, for the first issue, you can fix it by adding periods at the end of bullet points 1 and 4. You can fix the second issue by getting rid of the comma and space near the end of the first sentence of the second bullet:

"Then, figure out consequences if you fail (you lose time, you alert the guards, you get shot, etc)."

The final issue requires looking over the PDF as a whole and making sure each of the bulleted lists use the same formatting.

**The Location:**
p. 68, first bulleted list under "Making Skill Checks"

**Comment by melodycwatson** [comment]
Fixed. :)
