### ISSUE TITLE
[Typo] "effective" repetition under "Consequences"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#282]
**The Problem:**
The first sentence of the second paragraph under "Consequences" reads (emphasis mine): "Complications and consequences are the main **effective** ‘response’ a GM has **effectively** to player action, since NPCs do not act on their own."

**The Solution:**
It should instead read (emphasis mine): "Complications and consequences are **effectively** the main ‘response’ a GM has to player action, since NPCs do not act on their own."

**The Location:**
p. 69, paragraph 2 under "Consequences"

**Comment by melodycwatson** [comment]
Fixed. :)
