### ISSUE TITLE
[Typo] Possible phrasing issue under "Heroic Rolls"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#283]
**The Problem:**
The first sentence under "Heroic Rolls" says (emphasis mine): "If the GM decides a roll is so difficult that risky cannot adequately describe it, but **still want players to attempt the roll, they can** make it heroic."

This seems strange, especially when the next page clarifies that "the GM can never ask for a roll unless prompted by the players". So how can it be that the GM wants players to attempt the roll? In addition, the word "they" here is ambiguous.

**The Solution:**
I think what is actually meant by this sentence is (emphasis mine): "If the GM decides a roll is so difficult that risky cannot adequately describe it, but **the player still wants to attempt the roll, the GM** can make it heroic."

This makes it clear that it is the player that wants to make the roll and the GM that makes it heroic.

Alternately, if the intent is to emphasize that the GM wants the player to be able to succeed on the roll, it could be phrased as follows (emphasis mine): "If the GM decides a roll is so difficult that risky cannot adequately describe it, but **still wants the player to be able to succeed on the roll, the GM** can make it heroic."

**The Location:**
p. 70, first sentence under "Heroic Rolls"

**Comment by melodycwatson** [comment]
Fixed. :)
