### ISSUE TITLE
[Typo] Punctuation in bulleted list under "Skill Challenges"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#284]
**The Problem:**
In the second example in the bulleted list under "Skill Challenges", the first sentence is missing a period at the end: "All players roll a skill check (example triggers: charm, but could also be to threaten the baron, or perhaps read the situation)"

In addition, the first two bullets contain a sentence following the format "Success means [X], failure means [Y].":

"Success means they all get in unnoticed, failure means the guards are alerted."

"Success means the players gain a private audience with the Baron, failure means the players’ meddling is noticed by rival nobility and they are thrown out."

The commas here should actually be either periods or semicolons. The third bullet point correctly formats these as 2 separate sentences: "Success means they cross the wastes unharmed. Failure means they cross the wastes, but it is a harrowing journey and they arrive there with no repairs or supplies left and lacking food and water."

**The Solution:**
Add a period: "All players roll a skill check (example triggers: charm, but could also be to threaten the baron, or perhaps read the situation)."

And change the commas in the second and third bullets to either semicolons or periods (though consistency is ideal):

"Success means they all get in unnoticed; failure means the guards are alerted."

"Success means the players gain a private audience with the Baron; failure means the players’ meddling is noticed by rival nobility and they are thrown out."

**The Location:**
p. 71, under "Skill Challenges"

**Comment by melodycwatson** [comment]
Fixed. :)
