### ISSUE TITLE
[Typo] Extraneous space under "Combat in Narrative Play"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#285]
**The Problem:**
In the bulleted list of examples, the last bullet about Zaid contains the sentence (emphasis mine): "The GM decides the maneuver is almost impossible, but so daring that they allow a Heroic **roll .**"

**The Solution:**
The space should be removed: "The GM decides the maneuver is almost impossible, but so daring that they allow a Heroic **roll.**"

**The Location:**
p. 72, "Combat in Narrative Play", last bullet, sentence 2

**Comment by melodycwatson** [comment]
Fixed. :)
