### ISSUE TITLE
[Typo] "HP" should be consistently capitalized

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#286]
**The Problem:**
"HP" is sometimes written in lowercase ("hp"), and sometimes in uppercase ("HP"). Presumably uppercase is the intended format.

**The Solution:**
It should be consistently written in uppercase ("HP").

**The Location:**
p. 30
p. 51 (1st bullet under "HULL")
p. 73 (last sentence)
p. 75 (end of 1st paragraph under "Rests and Full Repair")
p. 116 (next to "Grit")
p. 131 (last sentence next to "Deployable", and last sentence next to "Drone")
p. 176 (2nd sentence under "Personalizations")
p. 222 (last paragraph under "Mag Deployer")
p. 366 (end of 3rd sentence next to "Dangerous Flora and Fauna")
p. 371 (last sentence of 2nd paragraph under "NPCs, damage, and heat")
p. 393 (under "Snare Drone")
p. 459 (3rd bullet under "Human")
p. 472 (end of very 1st sentence)
p. 476 (2nd sentence under "Scout Drone")
and p. 479 (last sentence under "Sealant Trap")

**Comment by melodycwatson** [comment]
Thank you for the detailed list! Fixed. :)
