### ISSUE TITLE
[Typo] "Hit points" should be properly capitalized on p. 74

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#287]
**The Problem:**
The first sentence under "Pilot Hit Points, damage, and injury" states (emphasis mine): "Pilots normally only care about **Hit points**, also called HP (how much damage your pilot can take before they are out of the action!) during mech combat, but they might also take damage as a result of complications during skill checks."

**The Solution:**
Both words I pointed out should be properly capitalized. In addition, there should be a comma after the parenthetical. Pilots normally only care about HP during mech combat; it's not "also called HP" only during mech combat.

The sentence should read (emphasis mine): "Pilots normally only care about **Hit Points**, also called HP (how much damage your pilot can take before they are out of the action!)**,** during mech combat, but they might also take damage as a result of complications during skill checks."

**The Location:**
p. 74, first sentence

**Comment by melodycwatson** [comment]
Fixed. :)
