### ISSUE TITLE
[Typo] Missing periods (after "etc") at end of each bullet in damage examples

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#288]
**The Problem:**
The descriptions of levels of damage in narrative play are each followed by an example:

"Minor damage is 1-2 damage. This could be something like getting shot by small arms fire, stabbed, unarmed combat, hit by a flying rock, etc
Major damage is 3-5. This is getting shot by assault or heavy weapons, a long fall, breathing in toxic gas, being exposed to vacuum, etc
Lethal damage is 6+. This is something like having a mech fall on you, getting hit by a mech scale weapon, having a grenade blow up right under you or something similarly catastrophic"

Throughout the PDF, there is no period after "etc" most of the time. It seems that not including periods after the abbreviation "etc" is a British custom, so that's understandable (if distracting to me...). But each of these lines is a sentence, and each should end with a period regardless.

**The Solution:**
It should read, with periods added at the end of each bullet:

"Minor damage is 1-2 damage. This could be something like getting shot by small arms fire, stabbed, unarmed combat, hit by a flying rock, etc.
Major damage is 3-5. This is getting shot by assault or heavy weapons, a long fall, breathing in toxic gas, being exposed to vacuum, etc.
Lethal damage is 6+. This is something like having a mech fall on you, getting hit by a mech scale weapon, having a grenade blow up right under you or something similarly catastrophic."

**The Location:**
p. 74, under "Pilot Hit Points, damage, and injury"

**Comment by melodycwatson** [comment]
Good spotting! Fixed. :)
