### ISSUE TITLE
[Typo] Wrong "its" under "Down and out"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#289]
**The Problem:**
The first bullet point reads (emphasis mine): "On a 6, you barely shrug off the hit (or **its** a close call), returning you to 1 HP."

This is the wrong "its". The word "its" is a possessive pronoun, whereas "it's" is a "contraction of "it is".

(The bulleted list formatting is also off.)

**The Solution:**
This sentence should read (emphasis mine): "On a 6, you barely shrug off the hit (or **it's** a close call), returning you to 1 HP."

**The Location:**
p. 75, first bullet under "Down and out"

**Comment by melodycwatson** [comment]
Fixed. :)
