### ISSUE TITLE
[Typo] Prerelease : Technophile Typo

### ISSUE THREAD

**Issue by SalsaDeGranada** [AshleyMoni/Lancer-Community-Edition#290]
**The Problem:**
"Servant Fragment (Rank I): Your mech gains a custom NHP with the AI tag (it costs 0 SP and
comes with any mech you print). It can speak to you and has a personality but is not as developed as more advanced NHPs and not capable of independent **through**, relying on your instructions to act. It is obedient to you alone. When acting alone it follows the last direction given and defends itself but has limited initiative on its own, it cannot benefit from your talents as normal."

'independent through' makes no sense given the context.
**The Solution:**
through --> thought
**The Location:**
Page 146 on Prerelease V2 PDF.

**Comment by melodycwatson** [comment]
Fixed. :)
