### ISSUE TITLE
[Typo] Prerelease: Smart Gun/Smartgun Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#291]
**The Problem:**
There's a discrepancy in the name of one of the Pegasus systems, with the summary listing it as a "Smartgun" while the longform description lists it as a "Smart Gun."

**The Solution:**
It's unclear which version Tom and Miguel would prefer to use, so you may wish to consult them on the matter of consistency in this particular case.

**The Location:**
Pages 284-285

**Comment by melodycwatson** [comment]
Fixed. :)
