### ISSUE TITLE
[RAI] Order of operations for simultaneous effects

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#292]
**The Problem:**
There isn't any specific text that clarifies what occurs first for effects that happen at the same time. For example, if you have Hacker rank 1 and you hit with an invasion that consumed a Lock On, which occurs first: choosing and implementing an invasion option, or Hacker 1's effect? There can be times where the order matters due to the different situations that the victim's heat, position, and choice under Hacker 1 would create.

**The Solution:**
Presumably, simultaneous effects like this should go in order of preference from the effects' originator. However, I uh have no idea where this clarifying text would go...under Attacks if such simultaneous effects tend to/always occur from attacks.

**The Location:**
N/A; this is a more general issue

**Comment by melodycwatson** [comment]
There is now a brief section under Actions>Action Resolution that covers this. :)
