### ISSUE TITLE
[Typo] Prerelease: HAVOK Charges Typo/Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#294]
**The Problem:**
The Napalm Grenade reads "Affected characters must pass an agility save **or take 3 burn and 1 burn on a successful save."**  This is somewhat unclearly written, though the intent can be discerned by comparing it to other similar systems.

**The Solution:**
For clarity, this could possibly read something along the lines of "Affected characters must pass an agility save or take 3 burn **or** 1 burn on a successful save." or "Affected characters must pass an agility save or take 3 burn, **taking 1 burn on a successful save."**

**The Location:**
Page 299

**Comment by V2Blast** [comment]
I think the clearest way to phrase it would be to split it into two sentences:

"Affected characters must make an agility save. On a failed save, the character takes 3 burn; on a successful save, the character takes only 1 burn."

**Comment by melodycwatson** [comment]
Fixed. :)
