### ISSUE TITLE
[RAI] Difficult Terrain: Cost on merely entering it, or starting movement out of it?

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#295]
**The Problem:**
"1 space of movement through Difficult Terrain costs 2 spaces worth of movement speed" isn't entirely clear on whether that extra cost is incurred when you enter and stop movement the difficult terrain, or when you start movement out of a space with difficult terrain. Do either situations also cost 2 movement instead of 1?

**The Solution:**
If it's only one or the other, then language would be something like "1 space of non-teleporting movement out of/into Difficult Terrain costs 2 spaces worth of movement speed"

**The Location:**
Page 95 in PR2 itch.io PDF

**Comment by VertigoCharades** [comment]
https://cdn.discordapp.com/attachments/426288556902842368/593095015970897931/unknown.png Tom's feedback on this a few months ago

**Comment by Ridiculon** [comment]
This was brought up in March, I forgot to add it to the tracker and i suppose it slipped through the cracks

![image](https://user-images.githubusercontent.com/1812965/60110269-72febe80-9731-11e9-813f-5f87b31f7e61.png)

**Comment by melodycwatson** [comment]
Wording has now been clarified to state that it only costs extra to move *into* a space of difficult terrain.
