### ISSUE TITLE
[RAI] Swarm Body Damage

### ISSUE THREAD

**Issue by ByteSizedSites** [AshleyMoni/Lancer-Community-Edition#296]
**The Problem:**
RAW Swarm body damage increase seems to increase every turn, whether yours, allied, or enemy turn. 

>  For each turn your mech remains immobile past the first, its damage increases by 3, up to a maximum of 9. 

**The Solution:**
If it's RAI that the damage only increases on your turn then it should be specified. 

**The Location:**
P.258

**Comment by KaiTave** [comment]
See unresolved ticket [RAI] 1.8.5: Balor Swarm Body Clarification for further elaboration

The Problem:
The Balor's Swarm Body system has two clauses that may require additional clarification:

1). "If your mech doesn’t move before the end of this turn, at the end of your turn you project a burst 1 area around your mech." Does this mean you can move and/or boost and THEN activate this system as your last action of the turn and it still functions, or are you not allowed to move at all on the turn you decide to use this system?

2). "For each turn your mech remains immobile past the first, its damage increases by 3, up to a maximum of 9." Is this meant to be for each of YOUR turns you remain immobile past the first, or is it including other actors' turns as well similar to how Infiltrator III currently works?

The Solution:
Designer input for both of these clauses would make the use of this system much clearer as currently there's some debate over its exact functionality.

The Location:
Page 237-238

**Comment by V2Blast** [comment]
> 
> 
> See unresolved ticket [RAI] 1.8.5: Balor Swarm Body Clarification for further elaboration
> 
> The Problem:
> The Balor's Swarm Body system has two clauses that may require additional clarification:
> 
> 1). "If your mech doesn’t move before the end of this turn, at the end of your turn you project a burst 1 area around your mech." Does this mean you can move and/or boost and THEN activate this system as your last action of the turn and it still functions, or are you not allowed to move at all on the turn you decide to use this system?
> 
> 2). "For each turn your mech remains immobile past the first, its damage increases by 3, up to a maximum of 9." Is this meant to be for each of YOUR turns you remain immobile past the first, or is it including other actors' turns as well similar to how Infiltrator III currently works?
> 
> The Solution:
> Designer input for both of these clauses would make the use of this system much clearer as currently there's some debate over its exact functionality.
> 
> The Location:
> Page 237-238

For reference, that's issue #152

**Comment by melodycwatson** [comment]
The wording has now been clarified for both points. :)
