### ISSUE TITLE
[RAI] Prerelease: Self-Imposed Condition & Stabilize Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#297]
**The Problem:**
Stabilize currently reads "End a condition on yourself or an adjacent ally that isn’t caused by one of your own systems (or that ally’s systems). Conditions are impaired, shredded, jammed, slowed, immobilized, stunned, or lock on."  While this does make it clear that self-imposed statuses from systems can't be cleared, it may be useful to expand this to include things such as talents, for example Crack Shot requiring a self-Immobilize to work.

**The Solution:**
"End a condition on yourself or an adjacent ally that isn’t caused by one of your own systems, **talents, etc** (or that ally’s systems **or talents).** Conditions are impaired, shredded, jammed, slowed, immobilized, stunned, or lock on."

**The Location:**
Page 107

**Comment by lenaleciel** [comment]
Fixed, according to #591.
