### ISSUE TITLE
[RAI] Prerelease: Tempest Drone Wording Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#298]
**The Problem:**
The Tempest Drone currently reads "The drone persists until recalled. You can move the drone
to a new space within sensor range as a quick action."  This is a bit more vague than other drone systems in terms of what action is required to recall it.

**The Solution:**
A rewording along the lines of that found in the Assassin Drone may help clarify things.  For example, "You can either move the drone to a new space within sensor range or recall it as a quick action."

**The Location:**
Page 272

**Comment by lenaleciel** [comment]
Fixed, alongside the rest of the drones in November Release.
