### ISSUE TITLE
[RAI] Prerelease: Hunter Logic Lacks Unique Tag

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#299]
**The Problem:**
The Mourning Cloak's Hunter Logic system lacks the Unique tag, unlike most every other system which adds options to Invasion.

**The Solution:**
It should most likely be Unique, as all other systems of its type are.

**The Location:**
Page 241

**Comment by lenaleciel** [comment]
This is still an issue as of November Release.

**Comment by lenaleciel** [comment]
New issue made as a reminder, #585 this one may be closed.
