### ISSUE TITLE
[RAI] Prerelease: Clarification on Systems Lacking Unique Tag

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#300]
**The Problem:**
There are a number of non-weapon systems in the game which lack the Unique tag which may or may not require it for balance or clarity purposes.  In no particular order:

-Monitor Module (a player could activate two instances of this system with a quick action each and gain 2d3 reaction attacks)
-Tesseract (a player could activate two separate instances of this system to utilize its effects twice in a single turn)
-Bulwark Mods (there's no balance issue here but also no benefit to having more than one instance aside, perhaps, from redundancy in case of critical damage)
-Mimic Mesh (a player could activate two instances of this system on their turn to gain the movement benefits for two characters)
-Plasma Gauntlet and Stasis Barrier (in general the game seems to have ensured that limited use systems are categorized as Unique to prevent multiplicative stacking, and presently neither of these limited systems are Unique)

**The Solution:**
Designer oversight and input into these particular systems is necessary to determine whether they should be given the Unique tag.  While non-unique systems can present interesting and clever mech design opportunities which do not seem particularly overtuned (there's nothing especially unbalanced about someone using two Ferrous Lashes in a turn, for example) these particular examples stand out as systems that merit additional consideration into whether or not they should remain non-unique.

**The Location:**
Mimic Mesh 265, Monitor Module 266, Bulwark Mods 195, Tesseract 304-305, Stasis Barrier 309, Plasma Gauntlet 324

**Comment by lenaleciel** [comment]
The StunCrown and the Iceout Drone also are not unique, despite having the limited tag.

**Comment by KaiTave** [comment]
Duplicate of #622
