### ISSUE TITLE
[Typo] Prerelease: Mech Names and Capitalization

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#302]
**The Problem:**
A common stylistic decision throughout the Lancer core book is that certain names tend to be written in all capital letters while in other instances they do not appear to be.  For example, in the flavor text for the Iskander's Broad-Sweep Seeder core ability, its name is written as ISKANDER, while in the flavor text for the Tokugawa's Radiance core ability, its name is simply written as Tokugawa.

**The Solution:**
Stylistically I'm not entirely certain if there's a particular pattern that Tom and Miguel have envisioned following but consultation with them may be helpful in formulating a consistent style guide throughout the core book.

**The Location:**
Page 303 and page 323 for the listed examples, but this may require checking throughout the book.

**Comment by melodycwatson** [comment]
Consistent capitalization now applied! :)
