### ISSUE TITLE
[Typo] Prerelease: Potential Reinforced Grapples Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#303]
**The Problem:**
"Woven from incredibly strong nanocarbon/arachosynth+ threading"

**The Solution:**
I believe, but please check with Miguel, that this is meant to be arach**n**osynth, as in arachnid.

**The Location:**
Page 182

**Comment by melodycwatson** [comment]
You are correct. Fixed! :)
