### ISSUE TITLE
[Typo] Wrong "it's" in Plasma Sheathe

### ISSUE THREAD

**Issue by jt-moriarty** [AshleyMoni/Lancer-Community-Edition#305]
**The Problem:**
The description of Plasma Sheathe reads "While the Tokugawa is in the danger zone or suﬀers from the exposed condition, **it’s** attacks with weapons"... I do not believe that this is the intended language since "it is attacks" would not make sense grammatically. 

**The Solution:**
"While the Tokugawa is in the danger zone or suﬀers from the exposed condition, **its** attacks with weapons"

**The Location:**
Page 327 of Lancer Core Book (PR2), in the Traits section of the Tokugawa.

**Comment by melodycwatson** [comment]
Fixed. :)
