### ISSUE TITLE
[Typo] Wrong word in unshackling description

### ISSUE THREAD

**Issue by ashkaun** [AshleyMoni/Lancer-Community-Edition#306]
**The Problem:**
Description of unshackled NHPs says `(or, in a world human)` instead of `or, in a word human`

**The Solution:**
As best Union can tell — Unshackled Non-Human Persons operate at such an advanced cognitive level that they lack empathy for human life -- note that this does not mean they must display *hostility* to human life, just they lack recognizable (or, in a word *human*) empathetic or moral constraints.

**The Location:**
Page 133, first paragraph, second sentence.

**Comment by ashkaun** [comment]
I think there might need to be a comma between "word" and "human" as well but I haven't included it in the suggested solution as I wasn't 100% sure.

**Comment by V2Blast** [comment]
> 
> 
> I think there might need to be a comma between "word" and "human" as well but I haven't included it in the suggested solution as I wasn't 100% sure.

Correct, there should be a comma there as well.

**Comment by melodycwatson** [comment]
Fixed. Thanks for spotting! :)
