### ISSUE TITLE
[Typo] Ultra Reflex Trait Typo

### ISSUE THREAD

**Issue by PickYerPoison** [AshleyMoni/Lancer-Community-Edition#308]
**The Problem:**
Reflex (trait): The Ultra has unlimited overwatch reactions (it can still only **many** 1 reaction per turn).

**The Solution:**
Reflex (trait): The Ultra has unlimited overwatch reactions (it can still only **make** 1 reaction per turn).

**The Location:**
p. 466

**Comment by melodycwatson** [comment]
Fixed. :)
