### ISSUE TITLE
[Typo] Ultra Fortress Trait Typo

### ISSUE THREAD

**Issue by PickYerPoison** [AshleyMoni/Lancer-Community-Edition#309]
**The Problem:**
Tech attacks against the Ultra are made at +3 difficulty and it makes all systems saves at +3 accuracy).

(Extra parenthesis at the end)

**The Solution:**
Tech attacks against the Ultra are made at +3 difficulty and it makes all systems saves at +3 accuracy.

**The Location:**
p. 467

**Comment by melodycwatson** [comment]
Fixed. :)
