### ISSUE TITLE
[Errata] Kobold Supplement - System Point cost and systems tag missing for LL3 systems

### ISSUE THREAD

**Issue by Ironykins** [AshleyMoni/Lancer-Community-Edition#31]
**The Problem:**
In the HORUS KOBOLD Supplement does not have SP costs for its License Level 3 systems.

**The Solution:**
Set the SP cost of both `Purifying Code` and `IMMOLATE` to 2.

**The Location:**
HORUS KOBOLD Supplement. Page 3.

**The Ratification:**
![image](https://user-images.githubusercontent.com/10353708/50990546-898cc280-14cf-11e9-9c58-11cbbbc81b94.png)

**Comment by KaiTave** [comment]
Addressed in the current document.
