### ISSUE TITLE
[Typo] Minotaur Core Active references checks

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#311]
**The Problem:**
The Minotaur's Core Active, Maze, mentions that the target can "repeat this check" despite the effect requiring a save.

**The Solution:**
Edit all instances of "check" in the ability to "save"

**The Location:**
pg. 280/285, Minotaur frame's Core Active

**Comment by melodycwatson** [comment]
Fixed. :)
