### ISSUE TITLE
[RAI] Prerelease: Breacher NPC Flechette Shot Lacks To-Hit Info

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#316]
**The Problem:**
The Breacher's Flechette Shot optional module currently lacks the necessary to-hit information required.

**The Solution:**
This info will need to be added in order to make proper use of this module.

**The Location:**
Page 393

**Comment by msprijatelj** [comment]
It looks like the Flechette Shot to-hit info is still missing in the Jul 01, 2020 version of the Lancer Core Book on itch.io? Unless it's supposed to hit automatically or simply have no attack bonus (COMP/CON data lists the attack bonus as +0/+0/+0).
