### ISSUE TITLE
[RAI] Exposed clarification status vs condition

### ISSUE THREAD

**Issue by ashkaun** [AshleyMoni/Lancer-Community-Edition#317]
**The Problem:**
On page 115 "exposed" is listed as a Status, but the majority of references to "exposed" in the core book -- including the change in the release notes introducing exposed -- say "exposed condition." This makes it unclear whether exposed is intended to function as a status or a condition.

**The Solution:**
Based on the fact that stabilize does not list "exposed" as one of the removable conditions (outside of doing so as part of resetting the heat gauge), and "exposed" being listed as a status on page 115, I think all instances of "exposed condition" should be replaced with "exposed status" in the core book.

**The Location:**
All instances of "exposed condition" throughout the core book.

**Comment by melodycwatson** [comment]
Fixed. :)
