### ISSUE TITLE
[Typo] Prerelease: Pilot Background List Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#318]
**The Problem:**
The random pilot background table lists "Survey Corps" as one of the possible outcomes but this is incorrect, it should actually be Far Field Team to match up with the longform blurbs following the table in question.

**The Solution:**
Replace "Survey Corps" with "Far Field Team" on the random table, realphabetizing as necessary.

**The Location:**
Page 133

**Comment by Ffzdf** [comment]
It seems that "Far Field Team" simply replaced Survey Corps from older versions of the rules, so it's likely that it was overlooked in the random table.

**Comment by melodycwatson** [comment]
Fixed. :)
