### ISSUE TITLE
[RAI] Lich's Time Split and Reactions

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#319]
**The Problem:**
The Lich's Time Split ability says that "The controlling player can also cause a field to disappear as a reaction to the end of any character’s turn," but also says that the new entities can't take reactions.

**The Solution:**
Let the controlling player just end the effect without a reaction.

**The Location:**
Lich PDF

**Comment by Ffzdf** [comment]
The clarification is that the controlling player (or the GM) themself is the one taking the reaction, not the entity that has been "split."
