### ISSUE TITLE
[RAI] Autogun non-benefit talent interactions

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#320]
**The Problem:**
Autogun's restriction on benefiting from talents does not appear to prevent it from activating Siege Specialist 1 or Combined Arms 3.

**The Solution:**
Change the wording of Autogun to be in line with the Apocalypse Rail's "Does not work with talents" language if it isn't meant to work, or leave it alone if it is meant to work that way.

**The Location:**
Core Book Pegasus Section page 288.

**Comment by Breenland** [comment]
Additionally, Brutal 3.
