### ISSUE TITLE
[Typo] Xaoli Combat Sheathe has outdated language for bonus damage

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#321]
**The Problem:**
 (choose which one is the primary target for bonus damage or other eﬀects) text in the description of Xiaoli Combat Sheathe.

**The Solution:**
(Bonus damage and other effects [I'm not totally sure what those other effects are] are halved like other multi-target attacks)?

**The Location:**
Zheng long rim PDF page 3

**Comment by Ffzdf** [comment]
Long Rim mechs were not included in the update to PR2, hence the legacy text.
