### ISSUE TITLE
[Typo] Death's Head's Vulture DMR doesn't display damage type

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#322]
**The Problem:**
The Vulture DMR's damage isn't typed. Going off previous iterations, it seems like this should be kinetic damage.

**The Solution:**
The text should read "1d6+1 kinetic damage"

**The Location:**
Page 227 of PR2 itch.io PDF

**Comment by melodycwatson** [comment]
This has now been corrected. :)
