### ISSUE TITLE
[Typo] Prerelease: Ferrous Lash Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#323]
**The Problem:**
"If you target a willing allied character with this system (in range 8 and line of sight), you can pull
**then** 5 in any direction."

**The Solution:**
"If you target a willing allied character with this system (in range 8 and line of sight), you can pull
**them** 5 in any direction."

**The Location:**
Page 218

**Comment by melodycwatson** [comment]
Fixed. :)
