### ISSUE TITLE
[RAI] Threat 1 weapons and Overwatch

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#324]
**The Problem:**
When overwatching with a threat 1 weapon either it happens when the target is in the space next to the overwatcher, and if the overwatcher was engaged by the target, they still are, or the overwatch happens after the target moves one space, and isn't adjacent to the overwatcher, and threat 1 melee can't overwatch them any more. Are ranged threat 1 weapons intended to suffer the penalty from engagement?

**The Solution:**
I think the ambiguity is whether "starts movement" means that the target has to actually move, or just commit to moving. Something reducing the ambiguity in that language would clean up this issue, and clarify similar things like the Sniper's Driving Fire optional trait. 

Wording like "begins movement but before leaving their current space" might do it.

**The Location:**
Reactions and Overwatch, page 110

**Comment by KaiTave** [comment]
Consolidated ticket with another ticket on the same subject.
