### ISSUE TITLE
[RAI] Prerelease: Overwatch Timing Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#325]
**The Problem:**
A question has arisen over the exact timing of the Overwatch reaction and how it interacts with various weapons.  For a character to trigger overwatch, is the trigger

A). The declaration of movement, i.e. before any movement has occurred at all?  Or
B). After at least one space of movement has occurred?

The reason this is relevant is that if overwatch triggers before the unit has moved at all then threat 1 melee weapons can make overwatch attacks, but ranged weapons will likely receive the +1 difficulty penalty for being in Engagement.  If the overwatch triggers AFTER the unit has moved then ranged weapons will be able to attack without penalty but threat 1 melee weapons cannot be used for overwatch, making them somewhat less useful.

**The Solution:**
It is assumed the intent for overwatch is that the declaration of movement is enough to trigger it, thus allowing all weapons to be able to overwatch even if ranged weapons in point-black range will suffer a penalty.  This is less an overt rules discrepancy and perhaps an area where, pagespace permitting, an example could be appended demonstrating how overwatch functions in play.

**The Location:**
Page 110

**Comment by KaiTave** [comment]
Consolidating tickets, posted by Plastic1d3:

The Problem:
When overwatching with a threat 1 weapon either it happens when the target is in the space next to the overwatcher, and if the overwatcher was engaged by the target, they still are, or the overwatch happens after the target moves one space, and isn't adjacent to the overwatcher, and threat 1 melee can't overwatch them any more. Are ranged threat 1 weapons intended to suffer the penalty from engagement?

The Solution:
I think the ambiguity is whether "starts movement" means that the target has to actually move, or just commit to moving. Something reducing the ambiguity in that language would clean up this issue, and clarify similar things like the Sniper's Driving Fire optional trait.

Wording like "begins movement but before leaving their current space" might do it

**Comment by Breenland** [comment]
This would be good for determining where characters stop when hit by weapons/effects that immobilize them, such as the Nail Gun.

**Comment by Ffzdf** [comment]
The overwatch rules should ideally be described with the same level of specificity as the Heavy Gunner talent currently possesses.

**Comment by Stepnix** [comment]
A similar issue arises with Prepared actions as with Overwatch

**Comment by lenaleciel** [comment]
As of November Release, Overwatch specifies "before they move"
