### ISSUE TITLE
[Typo] Missing period in Vlad flavor text

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#328]
**The Problem:**
"IPS-N produced the SUN 2 Like many other IPS-N chassis, the VLAD ..."

**The Solution:**
"IPS-N produced the SUN 2. Like many other IPS-N chassis, the VLAD ..."

**The Location:**
Page 212 of PR2 itch.io PDF, in the italicized text below the mech's name

**Comment by melodycwatson** [comment]
Fixed. :)
