### ISSUE TITLE
[RAI] Prerelease: Drake Heavy FRAME Trait Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#329]
**The Problem:**
The Drake's Heavy FRAME trait currently reads "The Drake cannot be knocked back or prone by actors smaller than itself."  However other instances of this trait in both PC mechs such as the Barbarossa and NPC mechs read "The [MECH] cannot be knocked back, pushed, pulled, or be knocked prone by actors smaller than itself."

**The Solution:**
The Drake's version of the trait should likely be updated to include all the appropriate language for consistency's sake.  If this is a typo it can be easily corrected, but if the traits are meant to be different in this fashion then designer input may be necessary.

**The Location:**
Page 185

**Comment by lenaleciel** [comment]
Fixed for the Drake, not for the Goliath. Making a new issue for the Goliath: #587
