### ISSUE TITLE
RAW / RAI for Ghast Nexus Drone Tag[Errata]

### ISSUE THREAD

**Issue by Snooglebum** [AshleyMoni/Lancer-Community-Edition#330]
**The Problem:**
In https://github.com/AshleyMoni/Lancer-Community-Edition/issues/185 there were clarifications added to the pre-release about the Ghast Nexus's rules for when it's deployed as a drone. However, even when not deployed, the weapon still has the "Drone" tag, which as far as I understand is unique. Does that mean that things like the Drone Commander's Rank 2 ability can trigger from your square? Does the Drone tag mean to only apply if it's applied, and if so, why is it attached to the weapon?

**The Solution:**
I have no idea, because I'm not even sure that RAW is supposed to be correct in this instance.

**The Location:**
The Annihilation Nexus can be found on page 276

**The Ratification:**
There is no official ruling, to my knowledge.

**Comment by KaiTave** [comment]
Closing this due to the same request for clarification being asked across two separate tickets.
