### ISSUE TITLE
[RAI] Prerelease: Ghast Nexus Clarification

### ISSUE THREAD

**Issue by Snooglebum** [AshleyMoni/Lancer-Community-Edition#331]
**The Problem:**
The Ghast Nexus that the Hydra can choose has the Drone tag. It obviously has that while deployed, but does that mean the weapon itself has that tag? And if it does, does that mean you can target effects from yourself while it isn't deployed, such as the talents from Drone Commander?

**The Solution:**
Removing the drone tag and only adding it while it's deployed, or explicitly clarifying that the mounted weapon form of it has that tag for talent interaction.

**The Location:**
The Ghast Nexus can be found on page 271.

**Comment by KaiTave** [comment]
Edited ticket to note that this is about the Ghast Nexus and not the Annihilation Nexus, changed header tag from [Errata] to [RAI].
