### ISSUE TITLE
[RAI] Prerelease: Sealant Spray Wording Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#332]
**The Problem:**
The entry for using the Sealant Spray system on a hostile character reads "Your target must make an agility save. **On hit,** they are Slowed until the start of your next turn but immediately ends any Burn affecting them."

**The Solution:**
As this effect is a save and not an attack, it may be clearer and more accurate to phrase it as **"If they fail,** they are Slowed until the start of your next turn but immediately end any Burn affecting them."

**The Location:**
Page 191

**Comment by melodycwatson** [comment]
Fixed. :)
