### ISSUE TITLE
[Typo] Improvised Attack range clarity

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#333]
**The Problem:**
The improvised attack doesn't list a threat or range at all, making its range hard to determine. 

**The Solution:**
" Target in melee" should probably read "adjacent target", as melee isn't the norm in the rules.

**The Location:**
Page 106, Improvised Attack action

**Comment by melodycwatson** [comment]
This has now been clarified to specify the target must be adjacent.
