### ISSUE TITLE
[Typo] Prerelease: Drone Gear Tag Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#334]
**The Problem:**
"They can’t take actions or move by default unless specified, and act on their owner’s turn if
they do have actions or **mvoement**"

**The Solution:**
"They can’t take actions or move by default unless specified, and act on their owner’s turn if
they do have actions or **movement**"

**The Location:**
Page 129

**Comment by melodycwatson** [comment]
Fixed. :)
