### ISSUE TITLE
[RAI] Prerelease: Grappling and Teleportation

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#335]
**The Problem:**
Questions have arisen over the interactions between teleportation and grappling. Currently, the text says that as "a character that teleports counts as moving 1 space," and therefore can't teleport if immobilized, the smaller party in a grapple cannot teleport at all, but there is confusion as to whether the larger mech teleporting would bring the smaller grappled party along. 

In other words, does teleportation count for the "moves when the larger party moves, mirroring their movement," bit of grappling, teleporting the smaller party as well, or does it not come along, usually breaking adjacency and ending the grapple?

**The Solution:**
Clarification as to which option is intended by the game designers, probably under the Teleport rules would be appreciated.

On a somewhat related note, it was also asked if the fact that the smaller, immobilized party not being able to teleport was an intended interaction. The fact it works that way is fairly clear to be the case, rules as written, but others have asked if this was how it was intended to work, and clarification either way would be nice.

**The Location:**
pg. 94, pg. 103

**Comment by Ffzdf** [comment]
It seems very much intended that you can't teleport while grappled if you're the smaller party. I suppose at the end of the Teleport section, the sentence, "You can not teleport while grappled if you are the smaller party," could just be tacked on?

As far as the larger party being able to teleport, RAW, it would be the former. That is, the smaller party would mirror your movement through the teleport and be taken along for the ride. However, keep in mind that this then suggests that you must still find a valid space for them to arrive on (so you wouldn't be allowed to teleport next to a ledge with them handing off the edge and just drop them, for instance).
