### ISSUE TITLE
[Typo] Prerelease: Veil Rifle Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#336]
**The Problem:**
"Allies caught in the area of this rifle are not attacked, but **are instead are covered** in coruscating energy"

**The Solution:**
"Allies caught in the area of this rifle are not attacked, but **are instead covered** in coruscating
energy"

**The Location:**
Page 227

**Comment by melodycwatson** [comment]
Fixed. :)
