### ISSUE TITLE
[Typo] Misspelling of Deimos in HORUS section of "Players On A Galactic Scale"

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#338]
**The Problem:**
"... leading many who know of it to assume that it is a _product_ of the Deimos**t** Event ..."

**The Solution:**
"... leading many who know of it to assume that it is a _product_ of the Deimos Event ..."

**The Location:**
Page 532 of PR2 itch.io PDF

**Comment by lenaleciel** [comment]
Fixed in November Release.
