### ISSUE TITLE
Stay of Execution interactions [RAI][Long Rim]

### ISSUE THREAD

**Issue by ExperimentAlpha** [AshleyMoni/Lancer-Community-Edition#340]
**The Problem:**
Lich's Stay of Execution ability states "The chosen character is immune to all damage and effects until the end of its next turn". How does this interact with a mech that is already primed to self-destruct before Stay of Execution is applied? Rules as Written, currently, the mech 'explodes' (dealing damage to the area around it) but is not destroyed by doing so.

**The Solution:**
Establish in Stay of Execution's text if a mech that is currently prepared to self-destruct is able to successfully, voluntarily do so. 

**The Location:**
LICH PDF, page 3

**Comment by VertigoCharades** [comment]
Note: Manticore's Castigate the Enemies of the Godhead seems to have its explosion triggered off the destruction of the mech (and pilot), so if this truly prevents mech destruction, then this would also prevent the explosion.
