### ISSUE TITLE
[Typo] Punctuation error in "its" under Skill Check action in Other Actions of Mech Combat

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#341]
**The Problem:**
"This activity is involved enough to take a full action, and **it's** parameters and outcomes are up to GM discretion."

**The Solution:**
"This activity is involved enough to take a full action, and **its** parameters and outcomes are up to GM discretion."

**The Location:**
Page 111 of PR2 itch.io PDF

**Comment by melodycwatson** [comment]
Fixed. :)
