### ISSUE TITLE
[Typo] Prerelease: Tortuga Automatic Shotgun Flavor Text Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#342]
**The Problem:**
"The single-barrel constriction allows for pneumatic absorption, dampening the effect of its incredible recoil, and its belt-fed action accepts many types of **shot-and-FRAME ammunition.**"

**The Solution:**
This is a find/replace error.  The correct text should read "The single-barrel constriction allows
for pneumatic absorption, dampening the effect of its incredible recoil, and its belt-fed action accepts many types of **shot-and-shell ammunition.**"

**The Location:**
Page 204

**Comment by melodycwatson** [comment]
Fixed. :)
