### ISSUE TITLE
[Typo] GM Section Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#345]
**The Problem:**
"**FRAME systemly** we hope it will inspire you to create your own content, worlds, and NPCs for LANCER."

**The Solution:**
"**Ultimately** we hope it will inspire you to create your own content, worlds, and NPCs for LANCER."

**The Location:**
Page 326

**Comment by melodycwatson** [comment]
Fixed. :)
