### ISSUE TITLE
[RAI] Prerelease: Ace III Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#346]
**The Problem:**
Ace III currently reads "If your mech ends its turn flying, you may nominate a hostile or allied
character in your movement range and line of sight as a quick action."  This has led to questions as to how this is supposed to work given that once your turn has ended, you do not generally have a quick action left to spend.

**The Solution:**
Is this meant to be a free action instead of a quick action?  Or is it meant to be a quick action used during, not at the end, of your turn?  Designer input into this is requested for clarification.

**The Location:**
Page 149

**Comment by lenaleciel** [comment]
Now a quick action that grants you a reaction at the end of your turn if you end your turn flying as of the November Release.
