### ISSUE TITLE
[RAI] Drones and Heat

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#347]
**The Problem:**
Currently, deployable drones do not have a listed heat capacity. Presumably this would mean that they take heat as energy damage, like pilots or npcs without a heat capacity. However, there's no rule that actually states this, either for drones specifically or for characters and objects without a heat capacity in general.

**The Solution:**
In the section that explains heat (under the section that explains damage or under the section that explains heat and overheating), add a line explicitly saying that anything without a heat capacity that would take heat takes it as energy damage instead, which seems to be the intent in general.

**The Location:**
pg. 101 or 117.

**Comment by Ridiculon** [comment]
Could be worded like this
![image](https://user-images.githubusercontent.com/1812965/62483870-62088a80-b77e-11e9-9c8a-08bdd459c858.png)

pg. 364

**Comment by lenaleciel** [comment]
This has been clarified since the November release.
