### ISSUE TITLE
[RAI] Expanded Compartment control takeover action type?

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#348]
**The Problem:**
Expanded compartment reads:

> Your mech has room for one extra size 1/2 non-mech character or object to ride alongside you in your cockpit. They gain the benefits of being inside a mech as if they were piloting it (they cannot be targeted by attacks from outside or suffer any effect from outside). If they take over the controls from you, they suffer as usually from piloting a mech they are not licensed for (the mech’s impaired and slowed while they pilot it).

What type of action is it to switch pilots? This has implications for action economy multiplication, talent access, HASE, and save targets

**The Solution:**
Specify an action type for switching who is piloting the mech

**The Location:**
GMS Chassis mod: Expanded compartment pg. 172

**Comment by Ridiculon** [comment]
Tom's response:
![image](https://user-images.githubusercontent.com/1812965/62566639-0f4ad380-b84f-11e9-8796-a55f222b8035.png)Assuming this means that it costs a protocol to switch to the other pilot, which would eat the first pilot's ability to do mech actions

**Comment by melodycwatson** [comment]
The text now clarifies that it follows the same rules as handing control over to an AI.
