### ISSUE TITLE
[Typo] Expanded compartment capitalization

### ISSUE THREAD

**Issue by Ridiculon** [AshleyMoni/Lancer-Community-Edition#349]
**The Problem:**
GMS Chassis mod "Expanded **c**ompartment" 

also in the body:

> If they take over the controls from you, they suffer as usually from piloting a mech

**The Solution:**
Expanded **C**ompartment (match the other GMS mods)

If they take over the controls from you, they suffer as **usual** from piloting a mech

**The Location:**
Expanded compartment pg. 172

**Comment by melodycwatson** [comment]
Fixed. :)
