### ISSUE TITLE
[Typo] Redundant 'is' in opening quote for "A Golden Age, of A Kind" section

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#350]
**The Problem:**
There's a redundant "is" in the Italo Calvino quote:

"There is is the blueprint"

**The Solution:**
It should state: "There is the blueprint"

**The Location:**
Page 482 in the latest itch.io PR2 PDF

**Comment by lenaleciel** [comment]
Fixed as of November Release.
