### ISSUE TITLE
[RAI] Infiltrator III - Steel Assassin interaction with AoEs/Multi-Target Attacks

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#351]
**The Problem:**
Infiltrator III's Steel Assassin deals its bonus damage only to the character chosen through the talent's use: 

> When you end your turn hidden, choose a character in line of sight. Your next melee or ranged attack from hiding against that character does +1d6 bonus damage ... and you only gain it against the chosen target.

Because of that specific text, AoEs/multi-targeting attacks still would only deal the bonus damage to that chosen target. However, RAW, that bonus damage is still halved if there is more than one target, via the Bonus Damage section on page 98:

> If bonus damage applies to an attack that targets more than one character, it is reduced by 1/2.

Is this intentional? Or is the bonus damage meant to be fully dealt, but only to the chosen target from Steel Assassin?

**The Solution:**
Leave as-is if intentional, otherwise use some specific language in Steel Assassin to clarify (e.g. take off the "and you only gain it against the chosen target" clause and replace it with the full sentence, "If this next attack targets more than one character, this bonus damage is not reduced by 1/2 from that, but it may only apply to the chosen target.")

**The Location:**
Page 98 for Bonus Damage section, page 160 for Infiltrator III

**Comment by VertigoCharades** [comment]
I am well aware that there'll be significant change to Infiltrator III anyway, but logging this in just in case!!

**Comment by melodycwatson** [comment]
The talent has changed quite significantly, so this wording no longer applies. Thank you, though!
