### ISSUE TITLE
[Typo] Stormbringer Talent Typo

### ISSUE THREAD

**Issue by Stormbeard** [AshleyMoni/Lancer-Community-Edition#352]
**The Problem:**
On page 162, the rank II Stormbringer talent grants two abilities, Thunder and "Lighting". 

**The Solution:**
Lighting would be changed to Light[n]ing.

**The Location:**
On page 162, the rank II Stormbringer talent, GMS MM-AuxCon ability, part 1, "Lighting"

**Comment by melodycwatson** [comment]
Fixed. :)
