### ISSUE TITLE
[RAI] Overkill, Critical Hits, and the Combat Drill

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#356]
**The Problem:**
Overkill was recently rewritten to clarify that only the final damage dice are to be rerolled, so in the case of a critical hit, only 1s that made it to the final damage result would be rerolled. 
This raises a few questions:

1. If a 1 or multiple 1s manage to get to the final damage pool and are forced to be rerolled during a critical hit, do you reroll those dice twice, keeping the highest of the set, following the critical hit rules, or just a single reroll per remaining 1?

2. If you critical hit with a Combat Drill with it's special ability active and end up with a 1 that makes it to the final damage pool, you will activate the Drill's +1d6 bonus damage. Do you roll that 1d6 bonus damage as 2d6k1 as the attack is still a critical hit?

**The Location:**
Pg. 210, Combat Drill, Pg. 96, Critical Hit, Pg. 128, Overkill

**Comment by lenaleciel** [comment]
Someone else also noted that due to the way Overkill interacts with critical hits, it is harder for the Combat Drill to activate it's overpenetration on a critical hit, which seems counterintuitive. Whether this is a big enough deal to warrant a rules change is a developer decision.

**Comment by liq3** [comment]
I'm the one who ran numbers for it. The results always came out to something like this. The damage and heat are average, 1,000,000 damage rolls for each one. 

Non-final Dice Crit - Damage: 29.174002 Heat:2.000419
Non-crit roll Damage: 19.99817 Heat:0.998748
Final dice crit Damage: 19.267168 Heat:0.007653

So, ironically, if you only explode the top 4 dice out of 8, it does less damage than a normal roll of 4 dice with exploding. Here's the python code I used to calculate that if anyone wants to check it. https://pastebin.com/he3j17pA

**Comment by lenaleciel** [comment]
Overkill was changed to affect all damage dice rolled as of November release, thus making Critical Hits with Overkill hilarious, and the Combat Drill's interactions with Critical hits much more natural. I'm not personally sure if this resolves the first two questions listed, but I felt obliged to comment on the follow up comments.
