### ISSUE TITLE
[RAI] The HA Blackshield, Other Continuous Bursts, and Movement

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#358]
**The Problem:**
Currently, it would seem that most effects that result in a continuous burst (such as the cloaking field) around the character remain centered around the character if they move or are involuntarily moved, and in most cases, what happens if this zone moves or if this movement causes a character to cross into or out of the zone are fairly clear or explained.

This gets a bit more complicated with the Harrison Armory Blackshield, which keeps anything, characters included, from crossing it, and thus raises questions about what happens if there is someone right next to the blackshield and the user moves one space closer to them.

**The Solution:**
Clarification on what happens in this scenario, or if that movement is even possible, would be appreciated. If the blackshield or other burst effects are *not* intended to move when the character projecting them moves, then clarification and standardized wording on which effects are permanently centered around a character and which are just defined by the area centered around the character at the time of their creation would be appreciated.

**The Location:**
pg 310

**Comment by Thac0nius** [comment]
Seconding the request for explicit wording as to whether burst effects follow or stay put once created. If one is the general rule and the other an exception that should be made explicit as well.

**Comment by lenaleciel** [comment]
Bursts are now explicitly stated to move with their origin, unless otherwise stated, such as with the Blackshield.
