### ISSUE TITLE
[RAI] Atlas Ricochet Blades Resolution

### ISSUE THREAD

**Issue by CaptainCuddlecakes** [AshleyMoni/Lancer-Community-Edition#362]
Atlas Ricochet Blades text reads:

> "As a quick action, mark a line 5 area from your mech and attack all characters within, dealing 1d3+2 kinetic damage on hit."

Attack text does not specify if should be a ranged attack, which affects talent and system interactions.  Similarly, other limited charge systems use saves, and were written in prior editions as "attack all enemies within the area of effect."

Needs dev input to confirm if this system intended to be a save-for-half system like other grenade charges, or a ranged attack?

**Comment by Ffzdf** [comment]
My interpretation is that it is intentionally not meant to count as either type of attack, thereby excluding it from certain talent interactions. Since "save for half" isn't mentioned and the text specifies that you make an attack (i.e. roll to hit), the intent seems clear.
