### ISSUE TITLE
[RAI] Vlad, Dismemberment, and Self-immobilization

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#367]
**The Problem:**
As written, if the Vlad immoblizes itself through any of the systems that inflict self-immobilize as a cost, it will Shred itself.

**The Solution:**
Change the line to "successfully immobilizes another character"

**The Location:**
pg. 208

**Comment by KaiTave** [comment]
Tom's already stated that the Vlad should not self-shred on immobilizing itself so I've tagged this as errata as well.

**Comment by lenaleciel** [comment]
Fixed in November Release.
