### ISSUE TITLE
[RAI] Swallowtail CORE - Ally Teleport Range

### ISSUE THREAD

**Issue by ProtoDVD** [AshleyMoni/Lancer-Community-Edition#370]
**The Problem:**

Swallowtail CORE System Active:

"Until the end of the current challenge, once per round, as a reaction when an allied character you can see is damaged by another character you can see, you can roll a d6. On a 4+, the attack hitting was actually a simulation that your mech predicted. Your ally gains resistance to all the damage from that attack, and your ally **can teleport 3** in a direction of their choice to where they ‘actually’ were. On a 1-3, there’s a glitch - your ally doesn’t gain resistance and takes damage normally, but **can teleport 6 spaces**."

Compare to Exposed Singularity, which is a voluntary teleport whose language specifies "**up to** X spaces", and the general rule regarding voluntary teleportation:

"When a character teleports, it instantly moves to **any free space that is wholly within the specified range**, so long as the destination has enough space
to fit the whole of that character." (PR2, page 96)

The general rule suggests that the Swallowtail should enable a teleport at any distance *up to* 3 or 6, but the inclusion of "up to" in a different voluntary teleport risks ambiguity for a player unaware of the general rule.

**The Solution:**

If the Swallowtail CORE is meant as an exception to the general rule, enabling teleportation only to a ring-shaped perimeter, such should be stated explicitly; if it is meant to follow the general rule, the inclusion of "up to" before each distance would suffice.

**The Location:**

Swallowtail CORE System Active (PF2, page 249; box: "Cloudscout TACSIM Swarms")

**Comment by lenaleciel** [comment]
Fixed in November Release, "up to" added to both Teleports.
