### ISSUE TITLE
[Errata] November Release Decksweeper Automatic Shotgun Damage Code

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#381]
**The Problem:**
The Tortuga's DSAS was accidentally changed to 2d3 instead of 2d6. Presumably this was because the wrong shotgun's damage code got changed.

**The Solution:**
The correction, removal or addition.
![image](https://user-images.githubusercontent.com/49732719/69753086-abf7f080-1120-11ea-8d7e-9bb96f51022d.png)

**The Location:**
pg 150

**The Ratification:**
Screenshot above

**Comment by KaiTave** [comment]
Closing this due to duplication.
