### ISSUE TITLE
[RAI] November Release: Bonus Damage Halving Clarifications

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#395]
**The Problem:**
"but damage is only rolled once and bonus damage is halved if there are **multiple targets** affected."

"If an attack that targets **more than one character** deals bonus damage, the bonus damage is halved."

"Attacks that target **more than one character or object** only deal half bonus damage."

There are three instances in the book of how the interaction between bonus damage and multiple targets are explained with regards to halving. This is somewhat important to clarify consistently because, for example, if someone fires a line 20 railgun at a single enemy target but that line also intersects a piece of cover or terrain that they don't necessarily care about destroying or not, the question becomes does the bonus damage on that attack get halved or not? Strictly speaking AoE weapons such as lines and blasts cannot "selectively target," they will hit anything within their area. So there's an important distinction between bonus damage being halved if it targets more than one CHARACTER or more than one CHARACTER OR OBJECT (or simply "multiple targets.")

**The Solution:**
Tom should be consulted to clarify how this is intended to work across the board. In the previous draft bonus damage was halved upon targeting multiple CHARACTERS so, for example, precision attacks against single enemies with AoE weapons were not penalized. If this is how it's intended to work then this will need to be consistently revised across the various explanations.

**The Location:**
Page 67, 78, 104

**Comment by Jay-Iles** [comment]
It's clearer now that it's only targeting multiple Characters.
