### ISSUE TITLE
[RAI] November Release: Lock On Consumption Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#396]
**The Problem:**
"Hostile characters can choose to consume a character’s LOCK ON condition in exchange for +1 Accuracy on their next attack against that character."

"To LOCK ON , choose a character within SENSORS and line of sight. They gain the LOCK ON condition. Any character making an attack against a character with LOCK ON gains +1 Accuracy on that attack, then clears the LOCK ON condition after that attack resolves. This is called consuming LOCK ON."

The explanation how how the Target Lock action works implies that consuming a Lock On when you attack a target is mandatory instead of optional, while the other definition states that consuming Lock On is a choice. In previous drafts consuming Lock On has been optional as some abilities may only activate or trigger against targets which are locked, and players may wish to avoid consuming the lock, or may simply want to attack a locked target while foregoing the target lock so an ally may make use of it later.

**The Solution:**
If consuming a Lock On is meant to be optional, it should be clarified in the explanation of the Target Lock action on page 70 to line up with the explanation on page 78.

**The Location:**
Page 70, 78

**Comment by Jay-Iles** [comment]
Consuming Lock On is optional, and made consistently that.
