### ISSUE TITLE
[Typo] Breacher NPC Unload typo

### ISSUE THREAD

**Issue by Techhead0** [AshleyMoni/Lancer-Community-Edition#40]
**The Problem:**
Breacher's Unload trait says +3 Accuracy for +2 total accuracy, but the Dual Shotguns have +2 base difficulty.

**The Solution:**
Should say "(for a total of __+1__ Accuracy by default)"

**The Location:**
Breacher NPC, pg 270

**Comment by KaiTave** [comment]
No longer valid as of 1.8.5
