### ISSUE TITLE
[RAI] Metalmark Active wording is confusing

### ISSUE THREAD

**Issue by Ironykins** [AshleyMoni/Lancer-Community-Edition#41]
**The Problem:**
The Metalmark's Active CORE system, Tactical Cloak, reads:
```
Until the end of the current challenge, or when you deactivate this module at the start of your turn, you
become invisible. If you take damage, you lose the benefit of this module until the start of your next
turn. No other action will deactivate it.
```

This makes it sound like the player becomes invisible
a) Until the end of the current challenge
b) When they deactivate this module at the start of their turn.

It is also unclear whether the player can reactivate the protocol if they deactivate it.

**The Solution:**
Change the first instance of "when" to "until"

**The Location:**
Page 204

**Comment by KaiTave** [comment]
Metalmark Active has changed to be much simpler as of 1.8.5
