### ISSUE TITLE
[RAI] November Release: Tokugawa Limit Break Bonus Damage Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#414]
**The Problem:**
The Tokugawa's Limit Break trait says that it adds +3 energy damage to attacks while the mech is exposed, but does not state whether this additional damage is, specifically, bonus damage.

**The Solution:**
If this is meant to be bonus damage it should state so in the description, as being bonus damage or NOT being bonus damage will have different effects on various rules and restrictions concerning the application of bonus damage. If it is intended that this is not bonus damage, then it can remain as it is.

**The Location:**
Page 250

**Comment by lenaleciel** [comment]
As of the public free release, this is still not Bonus Damage.
