### ISSUE TITLE
[RAI] November Release: Pilots and Weapon Reloading Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#417]
**The Problem:**
Pilot heavy ranged weapons have the Loading tag, but there is no way for pilots to reload them rules-as-written as pilots do not have access to the Stabilize action in the same way mechs do.

**The Solution:**
Tom has stated that pilots should be able to reload pilot weapons as a special quick action, but this does not appear to be stated anywhere in either the Pilots In Mech Combat section or the Pilot Weapon section.

**The Location:**
Page 74, page 109

**Comment by Jay-Iles** [comment]
Pilots now have the Reload quick action.
