### ISSUE TITLE
[RAI] Invisible Mechs still require cover to remain hidden

### ISSUE THREAD

**Issue by Ironykins** [AshleyMoni/Lancer-Community-Edition#42]
**The Problem:**
The description of the HIDE action (page 94) says:
```
You must end your turn in cover to keep hidden.
You automatically lose hidden if you end your turn in a place where you wouldn’t benefit from
cover (ie, a mech comes around a wall and can now draw unbroken line of sight to you), your
cover is destroyed, or you move from cover. If you’re hiding and invisible, you also lose hidden if
you lose invisibility.
```

But according to Tom, you do not need cover to stay hidden, so long as you remain invisible.

**The Solution:**
![image](https://user-images.githubusercontent.com/10353708/51050587-86a4d700-158e-11e9-8475-f8a183b4d472.png)

**The Location:**
Page 93

**Comment by KaiTave** [comment]
Hiding has been adjusted as of the prerelease version.
