### ISSUE TITLE
[RAI] November Release: Deliberately Failing Attacks

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#430]
**The Problem:**
On page 13 it now states "You may always choose to fail a skill check, **attack,** or save." Previously this clause only applied to checks or saves, not attacks. With players able to deliberately fail attacks, this is a substantial change to how AoE weapons work in terms of mitigating friendly fire (a Barbarossa can fire an Apocalypse Rail into the middle of their allies and choose to miss them altogether) but also allows for things such as a player choosing to deliberately miss with an attack to proc Executioner 3 by deliberately missing a target, dealing Reliable damage to it, then getting another attack against a different target altogether.

**The Solution:**
It is my opinion that allowing players to deliberately miss attacks (specifically attacks) is liable to lead to unintended and degenerate outcomes, and this should most likely be considered carefully if it is intended to make it to print or if this needs to be amended to disallow deliberately failing of attacks in addition to checks or saves.

**The Location:**
Page 13

**Comment by kotarou** [comment]
For example, this:

- **removes the downside of SEKHMET**
- allows safe attacking of allies to gain skirmisher movement procs
- etc
