### ISSUE TITLE
[RAI] November Release: Universal Compatibility and Apocalypse Rail Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#433]
**The Problem:**
A potentially unintended interaction between the Apocalypse Rail core ability and the Universal Compatibility core bonus has been raised, to wit whenever someone activates a core ability the Universal Compatibility core bonus allows them to heal damage and cool heat as a free action, but the Barbarossa may activate the Apocalypse Rail without necessarily expending its core power if it doesn't FIRE it. The end result of this is that a Barbarossa with Universal Compatibility could, in theory, activate its core ability every scene for a free action heal and cool if it wanted to.

**The Solution:**
In all likelihood this is unintended. A way to head this interaction off would be to amend the wording on Universal Compatibility slightly, to read: "Any time you **spend CP to activate a CORE SYSTEM,** you may also take a free action to restore all HP, cool all HEAT , and roll 1d20: on 20+, regain 1 CP." That would help ensure that the Barbarossa can only gain the benefits of the core bonus once it actually commits to spending the CP.

[edit]: Upon further examination, the PRv2 draft did in fact specify that one had to spend core power in order to utilize this core bonus, so this appears to be an oversight in need of correction.

The other potential avenue for clarification may be within the Apocalypse Rail itself and how it spends core power to activate but may not wind up spending it, but I'm not personally sure how to best clarify that to prevent unintended interactions such as these cleanly without potentially causing even more confusion. Tom may need to be consulted. Something like "this core ability costs no CP to activate, but cannot fire or trigger any additional effects which rely on spending CP unless you choose to spend 1 CP to begin making attacks with it."

**The Location:**
Page 118, 226

**Comment by Jay-Iles** [comment]
Universal Compatibility now triggers off spending a CP to activate a core system.
