### ISSUE TITLE
[RAI] November Release: Sap NPC Ability Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#439]
**The Problem:**
Both the Assassin and Demolisher NPCs have an ability called Sap which functions similarly, but the abilities are each categorized and slightly different from each other. One is a Quick Tech which recharges on a 5+ while the other is a Quick Action trait that recharges on a 6+.

**The Solution:**
I am uncertain that these two abilities are meant to be differentiated in this fashion, and I would confer with Tom to see whether or not these are in fact supposed to be two largely similar, identically named abilities with different action types and recharge rates, or if a single standardized version is preferred for both NPCs.

**The Location:**
Page 289, 298

**Comment by Jay-Iles** [comment]
Both are now a Quick Tech with Recharge 5+.
