### ISSUE TITLE
[Typo] In section 1, under "Mech Structure", "Frames"

### ISSUE THREAD

**Issue by jlaakso** [AshleyMoni/Lancer-Community-Edition#453]
**The Problem:**
"But remember that you’re not limited to just one FRAME – you can acquire new ones by unlocking rank II licenses."

**The Solution:**
Seems wrong, I guess it should "by unlocking higher ranks".

**The Location:**
Page 32

**Comment by Jay-Iles** [comment]
Isn't it Rank II licenses that unlock Frames for you? Or am I missing something?

**Comment by KaiTave** [comment]
The text in the book is correct, additional frames are unlocked at Rank II licenses specifically. This doesn't appear to be an issue in need of correction.
