### ISSUE TITLE
[RAI] November Release: Reactions per round clarification.

### ISSUE THREAD

**Issue by Dokujaka** [AshleyMoni/Lancer-Community-Edition#456]
**The Problem:**
"Unless specified otherwise, once you take a reaction you cannot take it
again until the beginning of your next turn."

For example, Sisyphus, if it's used twice in one round and a new round starts, is the player allowed to use it two times more since it's a new round? Or is it not possible to use it again since "once you take a reaction you cannot take it again until the beginning of your next turn."

It's not immediately clear if a reaction that can be used twice per round is usable on a new round or if the user must activate first on the new round. I'm not sure what the intended meaning is so not sure what the solution should be.

**The Location:**
Page 73 in the Backer Release PDF.

**Comment by Jay-Iles** [comment]
Probabilistic Cannabilism now specifies that it can be used no more than two times before the start of your next turn. This is the general ruling for reactions that are usable more than once per round.
