### ISSUE TITLE
[RAI] November Release: Search action type

### ISSUE THREAD

**Issue by Techhead0** [AshleyMoni/Lancer-Community-Edition#458]
**The Problem:**
Search is an NPC tech action, but a PC non-tech action. This also means abilities like ICEOUT Drone can grant hidden PCs immunity to being found by RAW

**The Solution:**
Make NPCs able to Search as a non-tech action

**The Location:**
Page 280

**Comment by Jay-Iles** [comment]
Done - search is now non-tech.
