### ISSUE TITLE
[RAI] November Release: Tortuga Core Active Clarification/Question

### ISSUE THREAD

**Issue by Eldraen** [AshleyMoni/Lancer-Community-Edition#463]
The new Tortuga core active now says it increases its weapon threat to 3, compared to the previous core active which augmented it to 5, is this intended or is this a typo ? A threat 3 would make Deck Sweeper Shotgun not gain any threat at all.

Where ?: p.148

**Comment by Jay-Iles** [comment]
Yes, Threat 3 is intended.
