### ISSUE TITLE
[Typo] November Release: Space Combat Typo

### ISSUE THREAD

**Issue by Eldraen** [AshleyMoni/Lancer-Community-Edition#464]
**The Problem:**
In the space combat section, there is this phrase "Space combat involving whole fleets incredibly rare"

**The Solution:**
Add the word "are" between fleets and incredibly

**The Location:**
Lore section, Space Combat, page 358

**Comment by KaiTave** [comment]
Well, it should likely be "Space combat involving whole fleets **is** incredibly rare."
