### ISSUE TITLE
[RAI] November Release: Monstrosity Structure Table and "Bonus Damage"

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#468]
**The Problem:**
The monstrosity's unique structure damage table has a result, Dismemberment, that has it take +1d6 Bonus Damage. As of the latest release, only Melee and Ranged attacks can ever deal bonus damage, and bonus auxiliary weapon attacks can't deal bonus damage, which leads to some odd interactions if the Monstrosity happens to take Structure damage from anything that's not a Melee or Ranged attack.

**The Solution:**
Use other wording than "Bonus Damage" such as "additional 1d6 damage" or just "1d6 kinetic damage" or something to decouple this damage from the specific rules of Bonus damage.

**The Location:**
pg. 324

**Comment by Jay-Iles** [comment]
Changed to 'it takes 1d6 kinetic damage'
