### ISSUE TITLE
[Typo] November Release: Plasma Gauntlet Damage Icon Omission

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#470]
**The Problem:**
The self-heat portion of the Plasma Gauntlet has already been identified, but someone else has pointed out that the damage the gauntlet itself deals also seems to be omitted, only stating 4d6 AP damage without a type.

**The Solution:**
The Plasma Gauntlet's damage code should have the proper damage type icon added to it, in this case energy, if it hasn't been updated already.

**The Location:**
Page 253

**Comment by CaptainCuddlecakes** [comment]
This was identified and closed in #403 
https://github.com/AshleyMoni/Lancer-Community-Edition/issues/403

**Comment by KaiTave** [comment]
The missing heat symbol was confirmed closed. This is a different missing symbol.

**Comment by CaptainCuddlecakes** [comment]
> 
> 
> The missing heat symbol was confirmed closed. This is a different missing symbol.

Whoops, that one's on me and my reading comprehension.
