### ISSUE TITLE
[RAI] November Release: TLALOC Protocol Unlimited Refire Issue

### ISSUE THREAD

**Issue by Luciferos** [AshleyMoni/Lancer-Community-Edition#479]
**The Problem:**
1. Unlike in PR2, TLALOC Protocol in release DOES NOT stipulate you can only reroll each attack roll once, which lets you theoretically reroll every attack you make during the protocol unlimited times until you hit or completely run out of targets in range/in the area. This seems like an unintended massive buff, especially because every missed attack would trigger Reliable on weapons, and big AoE weapons like the Plasma Caster would be able to functionally guarantee hitting every target you want to make sure you hit due to sheer re-roll spam.

2. Relatedly: the new TLALOC wording just says you can reroll against a new target; it doesn't actually stipulate "within range." This is kinda obvious RAI but should probably be stated RAW anyway!

Release:

![image](https://user-images.githubusercontent.com/20429868/69889069-134aa780-12bd-11ea-9854-c3b24d6a9c9a.png)

PR2:

![image](https://user-images.githubusercontent.com/20429868/69889120-4ee57180-12bd-11ea-9c3d-1ba2b6a8659c.png)

**The Solution:**
1. Unless this was intended, clarify as per PR2, "You can only make[sic] this reroll once per attack"

2. Change the Release wording from:

> however, during this time, you may reroll any missed melee or ranged attacks, choosing new targets each time

To:

> however, during this time, you may reroll any missed melee or ranged attacks, choosing new targets within range each time

**The Location:**
PR2 p.241
Back Release p.179

**Comment by lenaleciel** [comment]
As it stands right now, this results in the strange play pattern of trying to intentionally miss as many inaccurate shots as possible with a Reliable weapon to fish for the damage on a miss on as many targets as possible.

**Comment by lenaleciel** [comment]
Tlaloc now specifies, "you may reroll any missed melee or ranged attacks *once per attack*"
Nothing about the "you have to retarget in range" specifically though.
