### ISSUE TITLE
[Typo] Typo in Multi-Party Grappling Rules

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#48]
**The Problem:**
"For example, if my all and I are both size 1 and grappling a size 2 target together"

**The Solution:**
"For example, if my **ally** and I are both size 1 and grappling a size 2 target together"

**The Location:**
Page 93

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.

**Comment by KaiTave** [comment]
Noted as amended by the editor.
