### ISSUE TITLE
[Typo] November Release: Flash Charges Wording Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#481]
**The Problem:**
The text of the Flash Mine reads "On a failure, their line of sight extends only to adjacent **squares** until the end of their next turn."

**The Solution:**
Since Lancer is map agnostic, this should most likely read "On a failure, their line of sight extends only to adjacent **spaces** until the end of their next turn."

**The Location:**
Page 174

**Comment by Jay-Iles** [comment]
Fixed.
