### ISSUE TITLE
[Errata] November Release: Drone Commander 3 Healing

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#482]
**The Problem:**
Currently Drone Commander 3, Invigorate, allows the restoration of hitpoints. As there is no limit on this, concerns have been raised that the overuse of this talent could promote a playstyle of utilizing it to break the healing economy through repair-less healing.

**The Solution:**
Tom has asked me to append this ticket for his future consultation. Potential solutions include A). limiting the use of Invigorate to 1/scene or B). converting Invigorate to grant 1d6 Overshield instead of restoring +1d6 HP.

**The Location:**
Page 93

**Comment by Luciferos** [comment]
Additional suggestions: 

- If the desire is to let DC3 be a means for in-combat healing, simply stipulate if the chain damages at least one hostile target, THEN allies touched by the chain heal for the rolled amount as well. This prevents out-of-combat use without arbitrarily disallowing the ability narratively. (something something nanites in the beam)

- If changed to Overshield, the amount should be buffed mildly to make up for the fact that Overshield of very small numbers is largely useless and Overshield is less overall useful than healing; something like roll 1d6; enemies in the chain take damage equal to the roll result, allies in the chain gain Overshield 3+the roll result.

-If Invigorate is changed to 1/scene the damage and healing should be buffed substantially.

**Comment by lenaleciel** [comment]
Now changed to overshield 4 for allies as of December Release.
