### ISSUE TITLE
[Errata] November Release: NPCs and Full Tech Restrictions

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#483]
**The Problem:**
Several NPCs such as the Priest and Witch have a majority of abilities as Quick Tech actions. However, under the current rules restrictions for NPC actions, when an NPC takes a Full Tech action they may ONLY do so specifically for Full Tech actions as opposed to the PC equivalent which also allows for two Quick Tech actions similar to barrage. This means that these NPCs are more limited in what they can do each round as they cannot utilize more than one quick action a turn outside of things like boosting.

**The Solution:**
The proposal is to allow NPCs to use a Full Tech either to activate a Full Tech action OR to use two Quick Tech actions. Of importance, this should almost certainly be two DIFFERENT Quick Tech actions and disallow duplications (unlike PCs who can freely double up) because NPC Quick Tech options are not generally balanced around being able to be used twice in one turn, and enabling that could result in unintended consequences.

**The Location:**
Page 281

**Comment by KaiTave** [comment]
To clarify, Tom asked me to append this ticket to the tracker, hence the use of the "errata" tag. The decision is, as always, ultimately up to him.

**Comment by lenaleciel** [comment]
NPCs can now make 2 different quick tech actions with a full tech action as of December Release.
