### ISSUE TITLE
[Typo] November Release: Reactive Weave Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#485]
**The Problem:**
"When you BRACE , you become INVISIBLE until the end of your next turn and may immediately move spaces equal to **its** SPEED."

**The Solution:**
"When you BRACE , you become INVISIBLE until the end of your next turn and may immediately move spaces equal to **your** SPEED."

**The Location:**
Page 174

**Comment by Jay-Iles** [comment]
Fixed.
