### ISSUE TITLE
[Typo] Reactive Weave Grammatical Error

### ISSUE THREAD

**Issue by Luciferos** [AshleyMoni/Lancer-Community-Edition#486]
**The Problem:**
Minor grammatical typo in Reactive Weave:

> When you BRACE, you become INVISIBLE until the end of your next turn and may immediately move spaces **equal to its** SPEED

**The Solution:**

> When you BRACE, you become INVISIBLE until the end of your next turn and may immediately move spaces **equal to your** SPEED

**The Location:**
Backer/Free p.174

**Comment by KaiTave** [comment]
Already noted in a previous ticket, closed due to duplication.
