### ISSUE TITLE
[Typo] November Release: Tempest Drone Fluff And Rules Typos

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#487]
**The Problem:**
"The **tempest** protocol is a cunning little piece of code"

" Any character that starts their turn adjacent to the tempest drone or moves adjacent to it for the first time **on in a round**"

**The Solution:**
"The **Tempest** protocol is a cunning little piece of code"

" Any character that starts their turn adjacent to the tempest drone or moves adjacent to it for the first time **in a round**"

**The Location:**
Page 209

**Comment by Jay-Iles** [comment]
Fixed.
