### ISSUE TITLE
[Typo] November Release: Possible Assault Grapples Fluff Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#488]
**The Problem:**
"Grapple heads are interchangeable and can be swapped for engagement with soft or hard targets – either electrified or loaded with codespike systems for long-distance incapacitation."

**The Solution:**
The hyphen in this particular sentence stuck out at me as slightly unusual. The earlier draft formatting was written thusly: "Grapple heads are interchangeable and can be swapped for hard or soft targets, electrified, or loaded with codespike systems to incapacitate targets at a distance." This may or may not merit revision, depending on stylistic and grammatical requirements.

**The Location:**
Page 128

**Comment by Jay-Iles** [comment]
I believe this was intended - the idea is that the two variant heads mentioned correlate to soft and hard targets respectively.
