### ISSUE TITLE
November Release: Black Witch and Mourning Cloak Lore duplication

### ISSUE THREAD

**Issue by simulated-beehive** [AshleyMoni/Lancer-Community-Edition#489]
The first line of the lore for both the SSC Black Witch and Mourning Cloak lists both as "the flagship model of SSC's Lux Iconic Line" Is this intentional?

**Comment by Jay-Iles** [comment]
Updated - the Mourning Cloak is now 'a brand-new model from SSC's Lux Iconic line'.
