### ISSUE TITLE
[Typo] November Release: Possible Burst Launcher Fluff Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#490]
**The Problem:**
"We killed many of **them—blew** them away with burst launchers and cannons."

**The Solution:**
It's unclear if the hyphen here is formatted properly. In other instanced hyphens appear to be singular with spaces before and after, such as "Somehow it got inside my cockpit. There were hands – cold hands – around my neck" and so forth. This may be a typographical/formatting error to be amended.

**The Location:**
Page 170

**Comment by Jay-Iles** [comment]
Fixed.
