### ISSUE TITLE
[Typo] November Release: Seeking Payload Missing Damage Reduction/Launcher Exclusivity Clauses

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#492]
**The Problem:**
In changing Seeking Payload to correctly work and allow it's Seeking to properly target enemies out of line of sight, the line about it's damage not being able to be reduced was removed.

**The Solution:**
This was likely a mistake, and should be fixed to restore this functionality.

**The Location:**
pg. 176, Seeking Payload

**Comment by KaiTave** [comment]
Also the clause should still only specify this works with a Launcher weapon, specifically. Here is my recommended correction: 

"The Monarch can attack a character with the LOCK ON condition using a Launcher weapon as if its weapon had SEEKING, but must consume the LOCK ON during the attack. When the Monarch attacks with a Launcher weapon and consumes LOCK ON, the damage cannot be reduced in any way."

**Comment by Jay-Iles** [comment]
Fixed.
