### ISSUE TITLE
[Typo] November Release: Drake and Barbarossa Trait Name Disambiguation

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#495]
**The Problem:**
A potential issue which was raised before is the fact that two mechs have a trait with the same name but completely different effects, the Drake's and Barbarossa's Blast Plating. While technically no changes need to be made about this, the identical names but different effects could cause potential confusion as well as issues with COMP/CON development.

**The Solution:**
This should probably be brought to Tom's attention when he is no longer on his honeymoon, and if he agrees then my suggestion is the Barbarossa's trait name be changed to something else to disambiguate the two (the Drake's trait is more extensively tied into its core ability, while the Barbarossa's is not).

**The Location:**
Pages 132, 226

**Comment by lenaleciel** [comment]
Barbarossa's Trait is now called Pressure Plating as of December Release.
