### ISSUE TITLE
[Typo] November Release: Apocalypse Rail Fluff Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#497]
**The Problem:**
"in order to **affect** the accumulation of live data for use in improving the system prior to naval adoption."

**The Solution:**
I believe this should be "in order to **effect** the accumulation of live data for use in improving the system prior to naval adoption." similar to the use of the term "effect change."

**The Location:**
Page 226

**Comment by Jay-Iles** [comment]
Fixed.
