### ISSUE TITLE
[RAI] Inconsistency between effects which make attacks deal half damage. [November Release]

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#498]
**The Problem:**
Scylla and Tactician 3 state that the special attacks they make deal half damage on a hit. This is weird because it means that reliable weapons deal full damage on a miss.

**The Solution:**
Change these to match the text for Heavy Gunner and the Monitor Module which don’t work that way.

**The Location:**
Pages 102 and 205

**Comment by KaiTave** [comment]
Monitor Module also states "half damage on hit." For consistency, all of these should simply read "deals half damage" or some equivalent.

**Comment by Jay-Iles** [comment]
Fixed.
