### ISSUE TITLE
[Typo] November Release: GMS Mech Weapons List

### ISSUE THREAD

**Issue by Cobalt960** [AshleyMoni/Lancer-Community-Edition#499]
The Problem:
"Anti-Materi**e**l Rifle"

The Solution:
"Anti-Materi**a**l Rifle"

The Location:
Page 119, on the top of the GMS Mech Weapons List.

**Comment by KaiTave** [comment]
No, anti-materiel is the correct spelling.

https://en.wikipedia.org/wiki/Anti-materiel_rifle

In fact, this was corrected from the incorrect "anti-material" spelling earlier. As this is not actually a typo, I am closing this ticket.
