### ISSUE TITLE
[Typo] November Release: Markerlight Inconsistent Wording

### ISSUE THREAD

**Issue by Luciferos** [AshleyMoni/Lancer-Community-Edition#500]
**The Problem:**
As of Release, Markerlight's on-hit reaction when an ally hits your marked target is no longer consistent. It now says "when an ally successfully attacks your target" as opposed to "when an ally hits your target." Everything about the trigger suggests it's on an ally hitting, but there is wording inconsistency - this is the only place in the book that uses "successfully attacks" instead of "hits" and so there was some deliberation.

**The Solution:**
Change "successfully attacks your target" to "hits your target".

**The Location:**
PR2 (says hits): p.250
Release: p.186

**Comment by Jay-Iles** [comment]
Fixed.
