### ISSUE TITLE
[Errata] November Release: AGNI Protocol 1/Scene Correction

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#501]
**The Problem:**
The current version of the AGNI Protocol does not specify that it can only be used 1/scene like it should.

**The Solution:**
I double-checked with Tom and this is an omission, and so the AGNI Protocol should read "1/scene" similar to the ASURA Protocol.

**The Location:**
Page 233

**Comment by Jay-Iles** [comment]
Fixed.
