### ISSUE TITLE
[Typo] November Release: Knockback Definition Omission/Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#502]
**The Problem:**
The current wording for Knockback reads "On a hit, this weapon knocks its target X spaces in a straight line directly away from the point of origin," however in all prior versions of the game knockback has always explicitly been optional, that is to say if you hit someone with a weapon that deals knockback you do not HAVE to knock them back the full distance or any distance at all. However the wording here makes it seem as though knockback is mandatory and absolute.

**The Solution:**
Unless this is a deliberate change to the rules surrounding knockback, it should most likely read "On a hit, you may knock back a target X spaces in a straight line directly away from the point of origin," or similar.

**The Location:**
Page 105

**Comment by KaiTave** [comment]
> Tom Today at 5:36 PM
> knockback's optional

So this does seem to confirm that knockback is optional.

**Comment by lenaleciel** [comment]
Knockback X tag again has "may" under Gear tags as of December Release.
