### ISSUE TITLE
[RAI] November Release: Pirate NPC Boarding Leash Clarifications

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#503]
**The Problem:**
The Pirate NPC template's Boarding Leash as listed in the November release as having Threat 5. However, in the prior draft this was actually a weapon that was listed as having Thrown 5 without any sort of attendant Threat value.

**The Solution:**
As I'm doubtful the actual intent of this weapon is to have a Threat value of 5, in all likelihood the actual intent for this weapon is to be something along the lines of Threat 1, Thrown 5. You can double-check with Tom to make sure this is the appropriate format for this weapon.

**The Location:**
Page 328

**Comment by Jay-Iles** [comment]
Threat 1 Thrown 5 was indeed the appropriate statline.
