### ISSUE TITLE
[Typo] November Release: Grammar Error

### ISSUE THREAD

**Issue by KurtSchlegel** [AshleyMoni/Lancer-Community-Edition#504]
**The Problem:**
"Space combat involving whole fleets incredibly rare,"

**The Solution:**
"Space combat involving whole fleets **is** incredibly rare,"

**The Location:**
Page 358

**Comment by KaiTave** [comment]
This particular issue was already noted and closed by Jay. When the updated backer draft is released we can check to make sure it made it in, until then I am closing this ticket.
