### ISSUE TITLE
[Typo] November Release: Autogun Fluff Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#505]
**The Problem:**
The last line of the Autogun's flavor text cuts off early, reading "a reliably tuned autogun can be trusted to track and eliminate designated enemy units while a pilot concentrates on more"

**The Solution:**
Per the prior draft, this should read "a reliably tuned autogun can be trusted to track and eliminate designated enemy units while a pilot concentrates on more **specialized weapons or processes."**

**The Location:**
Page 221

**Comment by Jay-Iles** [comment]
Fixed.
