### ISSUE TITLE
[Typo] November Release: Pegasus License Formatting Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#506]
**The Problem:**
In the currently available free version of the game, the column for the Pegasus' Autogun appears to have become offset from where it was in the earlier backer release.

**The Solution:**
This may warrant some layout adjustments to conform to the desired stylistic outcome across the mech chapter.

**The Location:**
Page 221

**Comment by Jay-Iles** [comment]
Fixed.
