### ISSUE TITLE
[Typo] November Release: //SCORPION Typographical Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#508]
**The Problem:**
"HORUS closely guards the full text of the modified source **code—it’s** even rumored that there’s a kill switch built into the program," the hyphen here seems off compared to other examples found throughout the text.

**The Solution:**
This may merit adjustment for stylistic consistency, i.e. "HORUS closely guards the full text of the modified source **code - it’s** even rumored that there’s a kill switch built into the program," the hyphen here seems off compared to other examples found throughout the text.

**The Location:**
Page 204

**Comment by Jay-Iles** [comment]
Fixed.
