### ISSUE TITLE
[RAI] November Release: Multiple Walking Armory Discrepancies Tied to "On Hit" Trigger

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#511]
**The Problem:**
An issue similar to the Monarch's Seeking Payload also exists within the Walking Armory talent's Mag Rounds option. The option reads "The attack gains ARCING and deals kinetic damage." However, Walking Armory allows you to select the option AFTER hitting with the attack, while Arcing is a tag that only benefits the attacker BEFORE making the attack (ignoring line-of-sight).

**The Solution:**
Similar to how the Seeking Payload trait required clarification, this option may need it as well. Something along the lines of "The attack gains ARCING and deals kinetic damage. You may apply this effect before making the attack."

[edit]: See further commentary for a more in-depth analysis of this talent and the discrepancies within, which seem to stem from the language changing from "when you attack" to "on hit" permission, causing a number of problems.

**The Location:**
Page 103

**Comment by lenaleciel** [comment]
Additional text may need to be applied to the Shock Rounds, as their effects are also intended to be applied on a miss.

**Comment by KaiTave** [comment]
A similar wording discrepancy exists with the Shock Round option as well, which has a "hit or miss" clause, though again per the baseline wording of the talent you choose options only on a hit.

The core of the issue may be that Walking Armory used to require choosing an option BEFORE you made the attack, while now it's specifically on-hit, and certain options have not been updated to reflect that change, including the third rank which allows you to regain charges on critical hits when using the special ammo, so now a character can elect to wait until they definitively crit to spend the ammo, guaranteeing the ability to regain it.

The broader, and more effective, solution to these cumulative issues may simply be reverting Walking Armory to spending charges on special ammo when making the attack instead of on hit.

**Comment by lenaleciel** [comment]
Now patched to activate and expend charges on attack as of December Release.
