### ISSUE TITLE
[Typo] November Release: Aegis NPC Stat Discrepancies

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#513]
**The Problem:**
The Aegis NPC's e-defense is listed as being 3 at tier 2.

**The Solution:**
The correct value for this, as of the PRv2, should be 12 at tier 2 instead. Also double check with Tom as to whether its sensors of 8 at tier 1 is correct, or if it should consistently be 10 across all three tiers.

**The Location:**
Page 287

**Comment by Jay-Iles** [comment]
Fixed. Sensors at 8 at T1 seems to be correct.
