### ISSUE TITLE
[Typo] November Release: Hive Scaling & Major Typos

### ISSUE THREAD

**Issue by LoreLibrarian** [AshleyMoni/Lancer-Community-Edition#514]
I tried to report this as best as possible but there are a lot of things incorrect it seems, good luck. Also, I'm very tired.

**The Problem:**
Hive Tier II:
H
Evasion - 15
E-Defense - 8
Speed - 6
SaveT - 12
Armor - 0

Hive Tier III:
H -2 A +6 S +3 E +1
HP - 14
Evasion - 18
E-Defense 10
Speed - 7
SaveT - 14
Armor - 0

Potential Problem, idk if this is a typo to nerf to the NPC
Hive Stats from PR2
TI - H -1, Armor 0
TII - H -1, Armor 1
TIII - H +1, Armor 1

**The Solution:**
Hive Tier II:
Evasion - 8
E-Defense - 13
Speed - 5
SaveT - 14
Armor - 1

Hive Tier III:
H +1 A +0 S +5 E +1
HP - 20
Evasion - 10
E-Defense - 16
Speed - 5
SaveT - 17
Armor - 1

**The Location:**
Nov Release - Pg 302
PR2 - 416

**Comment by KaiTave** [comment]
To summarize, the Hive NPC has incorrect tier 2 and tier 3 statblocks, and both should be brought in line with the correct stats from the PRv2 version.

**Comment by Jay-Iles** [comment]
Fixed.
