### ISSUE TITLE
[Typo] November Release: Aegis NPC Hardlight Cover Quick Action Tag

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#516]
**The Problem:**
The statblock for the Aegis' Hardlight Cover system lacks the Quick Action tag.

**The Solution:**
The text of the statblock does make it clear a quick action is necessary to employ it, but adding the tag to the statblock for consistency's sake may also be desired.

**The Location:**
Page 287

**Comment by Jay-Iles** [comment]
Fixed.
