### ISSUE TITLE
[Typo] November Release: Barricade NPC Fluff Typo/Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#517]
**The Problem:**
There's what appears to be an unusual spacing oddity in the sentence "During the battle, Audrey Reimaus of the Seraphs’ Company" that's visible between the words "battle" and "Audrey." It doesn't manifest when copy/pasting the sentence so it may be a display error instead of a typographical one, perhaps linked to the use of Sumatra pdf reader.

**The Solution:**
A quick double check to ensure the spacing there is correct.

**The Location:**
Page 291

**Comment by Jay-Iles** [comment]
Fixed, it seems to have been double-spaced.
