### ISSUE TITLE
[Typo] November Release: Berserker NPC Avalanche Charge Formatting Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#518]
**The Problem:**
The Berserker NPC's Avalanche Charge statblock has the assorted tags (Trait, Recharge 5+, Quick Action) indented to the right side of the text box instead of on the left, which appears to be the default formatting.

**The Solution:**
Move the tags to the appropriate location within the text box for stylistic consistency.

**The Location:**
Page 293

**Comment by Jay-Iles** [comment]
Fixed.
