### ISSUE TITLE
[Typo] November Release: Vehicle NPC Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#519]
**The Problem:**
The Limited Melee trait for the Vehicle NPC template reads "The **Ship** can’t make melee attacks other than RAM."

**The Solution:**
"The **Vehicle** can’t make melee attacks other than RAM."

**The Location:**
Page 333

**Comment by Jay-Iles** [comment]
Fixed.
