### ISSUE TITLE
[RAI] November Release: Vlad Charged Stake Damage Question

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#520]
The Problem:
The current text for the Vlad's Charged Stake reads "This system fires a charged stake at character
adjacent to you. Your target must succeed on a HULL save or be impaled by the stake, taking 1d6 energy AP energy damage and becoming IMMOBILIZED . A character can repeat this save as a full
action to free themselves, otherwise they can make another HULL save at the end of each of their turns. If successful, the effect ends; otherwise, they take another 2d6 energy AP damage and remain IMMOBILIZED."

The Solution:
I was going to consult with Tom to clarify if these damage values are correct or not, but he's gone on his honeymoon and so this is being put here as a reminder to check in with him. Is the damage on further failed hull saves beyond the initial one supposed to increase to 2d6 damage? Without a changelog on hand it's sometimes hard to determine which adjustments to weapons and systems are intended and which aren't. If this is in fact the intended outcome (1d6 damage initially, 2d6 damage thereafter) then this ticket may be disregarded.

The Location:
155

**Comment by lenaleciel** [comment]
Charged stake is now set to 1d6 energy AP for both instances of damage as of December Release.
