### ISSUE TITLE
[Missing Text] November Release: Archer ‘Suppress’ Trait Missing Actions

### ISSUE THREAD

**Issue by ninjaxenomorph** [AshleyMoni/Lancer-Community-Edition#521]
**The Problem:**
The ‘Suppress’ trait of the Archer NPC is missing text specifying what action it is, as well as the reaction keyword. Was Quick Action In prerelease.

**The Solution:**
Should read “Quick Action, Reaction, Trait” under “Suppress”

**The Location:**
Page 288

**Comment by Jay-Iles** [comment]
Fixed.
