### ISSUE TITLE
[Typo] November Release: Missing 20+ result Scrounge and Barter

### ISSUE THREAD

**Issue by CasualSawfish** [AshleyMoni/Lancer-Community-Edition#522]
**The Problem:**
Description of Scrounge and Barter lacks 20+ result

**The Solution:**
AFAIK it should read: On a total result of 20+, you get what you’re looking for, no problems at all.
**The Location:**
Page 55

**Comment by Jay-Iles** [comment]
Fixed. The last 10-19 option was also cut off.

**Comment by Jay-Iles** [comment]
Fixed. The last 10-19 option was also cut off.
