### ISSUE TITLE
[Typo] November Release: Assassin NPC's "Devil's Cough" Shotgun Lacks To-Hit Info

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#527]
**The Problem:**
The statblock for the Assassin NPC's "Devil's Cough" Shotgun weapon lacks to-hit information.

**The Solution:**
Per the PRv2 draft, the to-hit value for this weapon is simply +0 at all tiers. However please double check with Tom if this is the intent or if this weapon should feature scaling to-hit bonuses based on tier (i.e. should it be +0/+1/+2, or +1/+2/+3 etc).

**The Location:**
Page 289

**Comment by Jay-Iles** [comment]
Fixed - simply added '+0' to the stats.
