### ISSUE TITLE
[RAI] November Release: Ultra NPC Template Deadly/Extra Deadly Trait Discrepancies

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#528]
**The Problem:**
The Ultra NPC template's Extra Deadly optional trait currently reads as replacing the standard Deadly trait. However, in doing so it makes it makes it seem as though the Ultra can now only critically hit once per turn as opposed to the standard Deadly trait which has no such restriction.

**The Solution:**
Based on the PRv2 draft, the Extra Deadly trait did NOT replace the standard Deadly trait, and was instead simply added to it. While I might consult with Tom regarding the intent here, if this is not an intentional decision then the solution is simply to remove the clause in Extra Deadly which states "This trait replaces DEADLY" so that the two traits can work in conjunction as they did before.

**The Location:**
Page 331

**Comment by Jay-Iles** [comment]
Removed the replacement - now reads:
"The first critical hit the Ultra performs each turn deals +2d6 damage at Tier 2 or +3d6 damage at Tier 3."
