### ISSUE TITLE
[Typo] November Release: Operator NPC Evasion/E-Defense Typos

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#529]
**The Problem:**
The Operator NPC's evasion and e-defense stats at tier 1 are incorrectly listed as evasion 12 and e-defense 8.

**The Solution:**
At tier 1, both of these values should be 10.

**The Location:**
Page 306

**Comment by Jay-Iles** [comment]
Fixed.
