### ISSUE TITLE
[RAI] Mount Retrofitting Needs Dev Input

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#53]
**The Problem:**
The GMS Mount Retrofitting core bonus allows you to replace one of your mech's mounts with a different type.  However two of the choices are an Aux/Aux mount and a Flex mount.  The issue here is that a Flex mount is effective the exact same thing as an Aux/Aux mount only better, which makes the choice between the two something of a trap option.

**The Solution:**
Tom should decide how this needs to be addressed.

**The Location:**
Page 142

**Comment by Ffzdf** [comment]
So a potential solution is having Mount Retrofitting grant a Main/Aux mount without any choice, similar to how it used to grant a CORE mount?

**Comment by KaiTave** [comment]
Mount Retrofitting now simply grants a Flex Mount in 1.8.5
