### ISSUE TITLE
[Typo] November Release: Possible Pyro NPC Flamethrower Iconographic Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#530]
**The Problem:**
The Pyro NPC's Flamethrower has several instances in the text where it uses the word "burn" instead of the icon.

**The Solution:**
While explanatory, these instances may need to be changed over to the appropriate icons for stylistic consistency.

**The Location:**
Page 308

**Comment by Jay-Iles** [comment]
Fixed.
