### ISSUE TITLE
[Typo] November Release: HORUS Splash Art Logo Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#531]
**The Problem:**
The HORUS logo showcased on the splash art on pages 190-191 appears to be different than that which was originally showcased here https://twitter.com/rsather_od/status/1158050954190774272

Notably, the "eye" appears to be much higher than perhaps it ought to be.

**The Solution:**
This should be amended to its proper design.

**The Location:**
Pages 190-191, see page 404 for a proper example of the faction logo.

**Comment by Jay-Iles** [comment]
Fixed.
