### ISSUE TITLE
[Typo]November Release: Shut Down Action Description NHP Clause

### ISSUE THREAD

**Issue by Kl0ndike** [AshleyMoni/Lancer-Community-Edition#532]
**The Problem:**
Under the description of the Shut Down (Quick) action, the following line is written under its effects:

"And cascading NHPs return to a normal state."

**The Solution:**
"Any cascading NHPs return to a normal state."

'Any' instead of 'And' fits the clause as well as the formatting of the next clause in the bullet pointed list.

**The Location:**
Page 72

**Comment by Jay-Iles** [comment]
Fixed.
