### ISSUE TITLE
[RAI] November Release: Sekhmet Discrepancies/Clarifications Needed

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#534]
**The Problem:**
Currently Sekhmet states "While the SEKHMET protocol is active, you lose direct control of your mech. Your NHP uses all available actions and movement to move toward the closest visible character – allied or hostile – and attacks them with melee weapons. If there are no characters within THREAT , your NHP uses all actions to move as directly as possible to the next closest (visible) target. Your NHP can’t make ranged attacks, even if there are actions available."

This is somewhat different from the PRv2 version in several respects, namely that it mandates the use of melee weapons and explicitly forbids the use of ranged weapons. However, this has the potential to cause some difficulties such as, for example, if a Sekhmet pilot's melee weapons have all been disabled or destroyed.

**The Solution:**
An additional clause or clarifications to Sekhmet's current incarnation may be warranted to avoid potentially non-interactive circumstances. For example, it may be better to state "Your NHP uses all available actions and movement to move toward the closest visible character – allied or hostile – and attacks them with melee **attacks**, prioritizing melee weapons." This way a disarmed Sekhmet can still attempt to ram, grapple, or use improvised attacks.

**The Location:**
Page 131

**Comment by Jay-Iles** [comment]
Fixed, with the suggested wording implemented.
