### ISSUE TITLE
[Typo] November Release: Raleigh M35 Mjolnir Typos

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#535]
**The Problem:**
The Raleigh Core Power now says that it adds shots at the "at the end of **any turn** during which
you haven’t **fire** [sic] the M35 MJOLNIR". Also the period ending the sentence is offset a space.

**The Solution:**
Should say "end of **any of your turns** during which you haven't **fired** the M35 MJOLNIR" to prevent ultra-fast charging.

**The Location:**
Page 144

**Comment by Jay-Iles** [comment]
Fixed.
