### ISSUE TITLE
[Typo] November Release: Damage Halving Language Consistency

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#536]
**The Problem:**
Several systems and abilities in the book state that they deal "half damage or heat" when used, such as Scylla, Monitor Module, and Tactician 3 only states "half damage."

**The Solution:**
In all of these cases, the text should be similar to that used by Heavy Gunner which states **"half damage, heat, or burn"**

**The Location:**
Pages 102, 204, 205

**Comment by Jay-Iles** [comment]
Fixed.
