### ISSUE TITLE
[RAI] November Release: Phase-Ready Mod Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#538]
**The Problem:**
The Phase-Ready Mod reads "Choose a weapon: as long as you know the rough location of your target, it can attack through solid walls and obstructions, doesn’t require line of sight, and ignores all cover, but targets count as INVISIBLE." Currently as written, it's unclear if you can attack targets WITHOUT counting them as invisible.

**The Solution:**
As far as I know the intent for this mod is to only apply the penalty when making "impossible" shots, but an additional clause or rewording to that effect may make the intent more clear if that is indeed the case. Something like "Choose a weapon: as long as you know the rough location of your target, it can attack through solid walls and obstructions, doesn’t require line of sight, and ignores all cover, but targets count as INVISIBLE **when you make attacks in this way.**"

**The Location:**
Page 240

**Comment by lenaleciel** [comment]
Whatever wording is used should be clear in whether the penalty applies if you attack an enemy in cover, but within line of sight.

**Comment by Jay-Iles** [comment]
Now the rules end with 'targets attacked this way count as INVISIBLE'.
