### ISSUE TITLE
[Typo] November Release: NHP Specialist Background Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#541]
**The Problem:**
"As a prime NHP, the one you were associated **with`** was even more complex than most."

**The Solution:**
"As a prime NHP, the one you were associated **with** was even more complex than most." (Extraneous grammatical mark after "with")

**The Location:**
Page 22

**Comment by Jay-Iles** [comment]
Fixed.
