### ISSUE TITLE
[Typo] November Release: Mechanic Background Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#542]
**The Problem:**
"Grease monkey, wrench, working joe; you were a mechanic prior to becoming a **pilot:**"

**The Solution:**
""Grease monkey, wrench, working joe; you were a mechanic prior to becoming a **pilot.**" (Sentence ends with a colon instead of a period.)

**The Location:**
Page 22

**Comment by Jay-Iles** [comment]
Fixed.
