### ISSUE TITLE
[Typo] November Release: Super Soldier Background Formatting Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#543]
**The Problem:**
"using biological enhancement, gene therapy, neurological enhancement"

**The Solution:**
The spacing of the words in this sentence appears strangely elongated in the pdf, though when copy/pasting the text it comes out normally. There may be a formatting oddity at work here.

**The Location:**
Page 24

**Comment by Jay-Iles** [comment]
Fixed.
