### ISSUE TITLE
[Typo] Formatting - Lancaster pg 136

### ISSUE THREAD

**Issue by dwarf74** [AshleyMoni/Lancer-Community-Edition#546]
**The Problem:**
The text for the middle Lancaster trait is cut off.

**The Solution:**
Resize text box so it fits

**The Location:**
Page 136

**Comment by lenaleciel** [comment]
This was corrected by the Friday release.

**Comment by dwarf74** [comment]
Sorry for the duplicates. I was working off the pdf I grabbed from
Backerkit.
