### ISSUE TITLE
[RAI] November Release: Barrage and Firing Aux/Aux Mounts

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#548]
**The Problem:**
In the latest iteration of the rules, the restrictions on Barrage were slightly changed to say "In addition to your primary attacks, you may also attack with a different AUXILIARY weapon on each
mount that was fired. These AUXILIARY weapons don’t deal bonus damage"

This has lead to the possible reading that you could select two aux weapons on the same mount to barrage as the primary attacks, and then possibly another bonus attack from one of the aux weapons, as it's a different weapon than the other one that was fired.

**The Solution:**
Previous versions have stated that "you can make an attack with an auxiliary weapon from the same mount that hasn’t been fired with this action". The "hasn't been fired with this action" text might be useful in adjusting the current text if this behavior is not intended.

**The Location:**
pg 71, Barrage

**Comment by Jay-Iles** [comment]
Fixed.
