### ISSUE TITLE
[Typo] November Release: Engineer Prototype Weapon Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#549]
**The Problem:**
"When you install it, or during a FULL REPAIR , you may choose a new weapon type, damage type, and either Threat 1 or Range 10."

**The Solution:**
"When you install it, or during a FULL REPAIR , you may choose a new weapon type, damage type, and either Threat 1 **(melee)** or Range 10 **(ranged)."**

**The Location:**
Page 94

**Comment by lenaleciel** [comment]
While on the subject, https://github.com/AshleyMoni/Lancer-Community-Edition/issues/257#issue-456492799 is an issue related to the Engineer weapon that still needs clarifying as of November Release.

**Comment by Jay-Iles** [comment]
Fixed.
