### ISSUE TITLE
[RAI] November Release: Fall Timing Discrepancy

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#550]
**The Problem:**
The falling rules read: "Unless specified otherwise, characters start to fall at the end of their turn", which is **weird** because it makes character float in the air for a while if they got pushed off a ledge by forced movement.

**The Solution:**
Change back to the old "end of current turn" text.

**The Location:**
Page 63 "falling"

**Comment by lenaleciel** [comment]
Now changed back to "end of current turn" in December Release.
