### ISSUE TITLE
[Typo] November Release: Mimic Gun Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#551]
**The Problem:**
"At the start of combat, roll 3d20 and note the results in order: X, Y, and Z. X is its starting RANGE. **At the start of every turn after the first**, the mimic gun cycles to the next result, taking that as its RANGE. After Z, it cycles back to X."

**The Solution:**
"At the start of combat, roll 3d20 and note the results in order: X, Y, and Z. X is its starting RANGE. **At the start of each of your turns after the first**, the mimic gun cycles to the next result, taking that as its RANGE. After Z, it cycles back to X."

**The Location:**
Page 220

**Comment by Jay-Iles** [comment]
Fixed.
