### ISSUE TITLE
[Typo] November Release: Berserker lore lacking

### ISSUE THREAD

**Issue by SarkhanTheFlaming** [AshleyMoni/Lancer-Community-Edition#552]
**The Problem:**
The Berserker's lore displays in the November release as "their weapon output by orders of magnitude. The archetype, best-known for its use by Gen’Dal Merlos’s Knights of Imminent Destruction, is preferred by pure combat-focus organizations, PMCs, and deniable-asset corps in established states." It is missing most of the first sentence that should be present.

**The Solution:**
The backer release has the full text: "Berserker mechs are built to take advantage of advanced heat-cycling systems that allow them to shunt heat – as its generated – into a pure offensive force, increasing their weapon output by orders of magnitude. The archetype, best-known for its use by Gen’Dal Merlos’s Knights of Imminent Destruction, is preferred by pure combat-focus organizations, PMCs, and deniable-asset corps in established states."

**The Location:**
Page 293

**Comment by Jay-Iles** [comment]
Fixed.
