### ISSUE TITLE
[Typo] November release: Demolishor NPC fluff/trait discrepancy

### ISSUE THREAD

**Issue by SarkhanTheFlaming** [AshleyMoni/Lancer-Community-Edition#553]
**The Problem:**
The Demolishor's Tactics entry mentions an **ENTRENCH** trait; but its base systems list a **DIG IN** trait instead.

**The Solution:**
Should both be the same, I'm not certain which is supposed to be correct.

**The Location:**
Page 298

**Comment by Jay-Iles** [comment]
Fixed.
