### ISSUE TITLE
[Typo] Priest NPC fluff

### ISSUE THREAD

**Issue by SarkhanTheFlaming** [AshleyMoni/Lancer-Community-Edition#554]
**The Problem:**
The last sentence of the Priest's fluff reads "They even go so far as to share sensory input between linked pilots – an experience known to produce **and** hyper-perception fugues and other ascendant mental states.

**The Solution:**
The bolded 'and' is unnecessary and should be removed. 

**The Location:**
Page 307

**Comment by Jay-Iles** [comment]
Fixed.
