### ISSUE TITLE
[Typo] November release: Pyro NPC fluff

### ISSUE THREAD

**Issue by SarkhanTheFlaming** [AshleyMoni/Lancer-Community-Edition#555]
**The Problem:**
The first sentence of the Pyro's fluff reads "First popularized in the wake of the Hercynian Crisis by the lancer Flama and their aptly named Devil Corps, Pyro frames are reviled across the galaxy as the embodiment of the pure destructive power **of** held by militarized states and corpro-states.

**The Solution:**
Bolded 'of' is unnecessary and should be removed. 

**The Location:**
Page 308

**Comment by Jay-Iles** [comment]
Fixed.
