### ISSUE TITLE
[Typo] November Release: Overheating Table refers to [Stress]d6 instead of [Stress Damage]d6

### ISSUE THREAD

**Issue by emersonp** [AshleyMoni/Lancer-Community-Edition#557]
**The Problem:**
Overheating table, on page 81, instructs players to `CHECK THE LOWEST VALUE ON [STRESS] D6`

**The Solution:**
Should be `CHECK THE LOWEST VALUE ON [STRESS DAMAGE] D6`

**The Location:**
Table on page 81

**Comment by Jay-Iles** [comment]
Fixed.
