### ISSUE TITLE
[Typo] November Release: Guardian/Colossus Trait Wording Standardization

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#558]
**The Problem:**
The wording for various mechs' Guardian traits (and the Barbarossa's Colossus, which functions similarly) are inconsistent.

Drake: Allied characters can use the Drake for hard cover.

Tortuga: Allied characters can use the Tortuga for hard cover.

Gorgon: Allies [sic] characters may use the Gorgon for hard cover.

Barbarossa: Adjacent allied characters can use the Barbarossa for hard cover.

Saladin: Adjacent allies can use the Saladin for hard cover.

**The Solution:**
A single consistent wording for these traits should be settled on and applied to all of them equally. "Allied characters can use the [MECH] for hard cover" should be sufficient for each one.

**The Location:**
Pages 132, 148, 202, 226, 242

**Comment by Jay-Iles** [comment]
Fixed.
