### ISSUE TITLE
[Typo] November Release: Drake Blast Plating Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#560]
**The Problem:**
The Drake's Blast Plating trait currently reads "The Drake has RESISTANCE to **damage and heat**
from blast , burst , line , and cone attacks."

**The Solution:**
For clarity of effect, this should read "The Drake has RESISTANCE to **damage, burn, and heat** from blast , burst , line , and cone attacks."

**The Location:**
Page 132

**Comment by Jay-Iles** [comment]
Fixed.
