### ISSUE TITLE
[Typo] November Release: Missing range icon for Comp/Con Assistant Unit

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#562]
**The Problem:**
The sentence "You can issue new commands at the start of your turn as long as you are within 50 and have the means to communicate with your mech." is missing the range icon right before "50"

**The Solution:**
Place the icon right before "50" in the sentence.

**The Location:**
Page 120

**Comment by Jay-Iles** [comment]
Fixed.
