### ISSUE TITLE
[Typo] November Release: Unlike every other Status, Engaged is not defined in the list of statuses

### ISSUE THREAD

**Issue by darloth** [AshleyMoni/Lancer-Community-Edition#565]
**The Problem:**
Engaged is not defined in the Statuses and Conditions list, unlike every other status.

**The Solution:**
As with the other statuses, Engaged should have a short paragraph saying something like: "A character is Engaged when it is adjacent to a hostile character."  It doesn't have to be as long as the description on page 62 but it should be present.

**The Location:**
Engaged as a status is (un)defined on page 77, but the actual description of how Engagement works is on page 62.

**Comment by Jay-Iles** [comment]
Fixed.
