### ISSUE TITLE
[RAI] November Release: OASIS Wall hard cover rules

### ISSUE THREAD

**Issue by jpbrodsky** [AshleyMoni/Lancer-Community-Edition#566]
**The Problem:**
The OASIS wall system (Dusk Wing III) has been changed in the November release to provide hard cover instead of soft. The rules text has not been updated to clarify how the size of the light wall interacts with the hard cover rules. In particular, ordinary hard cover must have a Size score, but the Oasis wall does not.

"you create a holographic trail behind you as you move, creating a light barrier 1 space high in each space you move through. This barrier grants hard cover to adjacent characters, and characters that benefit from this cover also gain RESISTANCE to [energy]"

Is this supposed to be a Size 1 barrier? Or is it supposed to grant unconditional hard cover to adjacent allies? (If unconditional: does that waive both size and flanking conditions, or just size?)

The light barrier is hard cover that can be occupied, since it is not an obstacle. How does that interact with the flanking rules?

If a Size 2+ mech uses this system, RAW suggests they make a higher barrier ("each space they move through" presumably includes the vertical spaces occupied by the taller mech"). Is that right? Is this barrier a bigger Size hard cover?

**The Solution:**
Probably:
"you create a holographic trail behind you as you move, creating a light barrier along the line you move through. This barrier acts as Size 1 hard cover, and characters that benefit from this cover also gain RESISTANCE to [energy]. Characters inside the barrier cannot lose the hard cover it grants due to flanking."

Or alternatively:
"you create a holographic trail behind you as you move, creating a light barrier in each space you move through. Any attack against a character adjacent or inside the barrier is made with [2 difficulty]. Characters adjacent or inside the barrier have resistance to energy."

**The Location:**
P171 November Release.

**Comment by lenaleciel** [comment]
December Release now specifies that the Oasis wall is the size of your mech, and that you can't sit your ass inside of it, though if you were to somehow be shot while walking through it (as a reaction, perhaps) Adjacency includes sharing the same space.
