### ISSUE TITLE
[Typo]  November Release: Ambiguous lifespan of pilots

### ISSUE THREAD

**Issue by HelmicNewciv** [AshleyMoni/Lancer-Community-Edition#567]
The Problem:
As a general rule, the natural lifespan of a pilot is only marginally than that of a Diasporan or Metropolitan.

The Solution:
As a general rule, the natural lifespan of a pilot is only marginally [shorter/longer?] than that of a Diasporan or Metropolitan.

The Location:
Page 148, first sentence of paragraph 5.

**Comment by KaiTave** [comment]
Per the wording in PRv2, this should be "Generally speaking, the natural life of a pilot is only marginally **longer**" etc.

**Comment by Jay-Iles** [comment]
Fixed.
