### ISSUE TITLE
[Typo] November Release: Metalmark Fluff Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#568]
**The Problem:**
"The Metalmark is the backbone of SSC’s BELLA CIAO mil-spec chassis line, fully equipped with a comprehensive suite of proprietary design and engineering hallmarks to ensure **that** its survivability, deadliness, and agility."

**The Solution:**
"The Metalmark is the backbone of SSC’s BELLA CIAO mil-spec chassis line, fully equipped with a comprehensive suite of proprietary design and engineering hallmarks **to ensure its survivability, deadliness, and agility."**

**The Location:**
Page 172

**Comment by Jay-Iles** [comment]
Fixed.
