### ISSUE TITLE
[Typo] Autogun flavor text is truncated

### ISSUE THREAD

**Issue by Ffzdf** [AshleyMoni/Lancer-Community-Edition#570]
**The Problem:**
Autogun flavor text is missing a few words at the end.

**The Solution:**
Should say "more specialized weapons or processes" at the end.

**The Location:**
pg. 221

**Comment by Ffzdf** [comment]
also afaik this wasn't fixed in whatever we have access to currently

**Comment by Jay-Iles** [comment]
Fixed.
