### ISSUE TITLE
[RAI] November Release: Saladin CORE Defensive Pulse

### ISSUE THREAD

**Issue by Dokujaka** [AshleyMoni/Lancer-Community-Edition#571]
**The Problem:**

> "...you may force the attacker to reroll it
> against a character or object of your choice,
> checking line of sight and RANGE from your target
> instead of from the attacker."

It is unclear how this interacts with LINE, CONE, BLAST and BURST type attacks.

**The Solution:**
Some clarity regarding if those types of attacks can be redirected to another target at all, what Range to use if you can, since Range 3 is not the same as Line 3 for example.

**The Location:**
Page 242 in the Free Release PDF, in the CORE system section.

**Comment by Jay-Iles** [comment]
Perhaps it could work as 'treating your target as the attack's point of origin instead of the attacker'?

**Comment by lenaleciel** [comment]
Now specifies that "If the attack was part of an area of effect, the new target must be inside the same area of effect from the original attack instead."
