### ISSUE TITLE
[RAI] November Release: Talent Brutal Rank 3 - Relentless

### ISSUE THREAD

**Issue by Dokujaka** [AshleyMoni/Lancer-Community-Edition#572]
**The Problem:**

> When you make an attack and miss, your next
> attack gains +1 Accuracy. This effect stacks and persists
> until you hit.

**The Solution:**
In the case of multi hit attacks such as BLAST and LINE, what constitutes as a missed attack? Is it if you miss all attack rolls against targets in a BLAST? Or is it per attack roll?
It might be that most of the confusion stems from not understanding fully if an attack refers to all attack rolls included in a BLAST for example, or if one attack roll is considered an attack on its own, in which case clearing up the language there will solve everything (hopefully!).

**The Location:**
For the talent: Page 91 in the Free Version PDF.
For the language regarding attacks: Page 13 in the Free Version PDF.

**Comment by lenaleciel** [comment]
Also note the similar effect of the Kinetic Compensator on pg 167, as similar questions arise there.

**Comment by lenaleciel** [comment]
Both effects have been reverted to say "attack roll,"  thus clearing up their use with AoE effects.
