### ISSUE TITLE
[RAI] November Release: Ranged Weapons as a Definition and Attack Types

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#573]
**The Problem:**
Currently, while multiple things in the book refer to "ranged weapons" there is not actually any point in the book where this is defined as "Rifle, CQB, etc" except for maybe the Mimic Gun, which doesn't even list them all and probably shouldn't be the only source of explanation.
This has lead to confusion as to whether things like CQB make Melee Attacks (#239) in Threat, because there's not actually a section that explains that Melee Weapons make Melee Attacks and Ranged Weapons make Ranged Attacks. ...While the latter should be fairly self-evident and obvious, it becomes harder when there's not actually any definition for a "Ranged Weapon." 

The current definition of Melee Attack merely states "The attacker chooses a target within weapon
THREAT" which doesn't exclude the use of Ranged Weapons with Threat for this purpose, which is clearly not intentional, as that practically negates the concept of an Engagement Penalty.

**The Solution:**
I would advise against simply making "Melee Attack" specify "Melee Weapon" as there are multiple ways to Melee attack that don't involve weapons at all (Ram, Grapple, Improvised Attack, etc).

Instead, I'd suggest adding information under the Weapon Types descriptions to clarify that CQB, Rifles, Launchers, Cannons, and Nexus weapons are Ranged Weapons, and that Ranged Weapons only make Ranged Attacks, even against targets in their Threat.

**The Location:**
pg. 33 Type
pg. 64 Melee Attack
EDIT: Someone also pointed out that an alternate place to put this definition would be pg. 104 under the Gear Tags

**Comment by Jay-Iles** [comment]
Fixed: added this beneath the weapon types on p. 33 and p. 10:
"Note: CQB, Rifles, Launchers, Cannons and Nexus weapons are Ranged Weapons, and always make Ranged Attacks even against targets within their Threat."
