### ISSUE TITLE
[Typo] November Release: Extra period in Mag Deployer's Repulse

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#574]
**The Problem:**
"Allied characters that enter the space**.** may immediately fly 3 spaces in any direction as a free action."

**The Solution:**
"Allied characters that enter the space may immediately fly 3 spaces in any direction as a free action."

**The Location:**
Page 163

**Comment by Jay-Iles** [comment]
Fixed.
