### ISSUE TITLE
[Typo] November Release: Death's Head's Precognitive Targeting lore

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#575]
**The Problem:**
"Using a neural bridge, SSC’s precognitive targeting system allows pilots to learn constantly and unconsciously from data gathered in the field, **equipped** them to read situations before they develop."

**The Solution:**
"Using a neural bridge, SSC’s precognitive targeting system allows pilots to learn constantly and unconsciously from data gathered in the field, **equipping** them to read situations before they develop."

**The Location:**
Page 164

**Comment by Jay-Iles** [comment]
Fixed.
