### ISSUE TITLE
[Typo] November Release: Level to Tier Listing and LL 0 Pilots

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#576]
**The Problem:**
The section that shows the rough equation of LL to tiers lists "T1: LL1–4, T2: LL5–8, T3: LL9–12".
This leaves out LL0.

**The Solution:**
Change T1 to list 0-4 instead of 1-4.

**The Location:**
pg 281, Tier

**Comment by Jay-Iles** [comment]
Fixed.
