### ISSUE TITLE
[Typo] November Release: Mute Drive vs. Copy Drive

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#577]
**The Problem:**
In the section of the Setting Guide describing Smart Weapons, the two types of weapons listed are copy drives (Presumably renamed from Mute Drives, as they were called in the Pre-release Version) and comp/con wingmen. However, the end of the section still refers to Copy Drives as Mute Drives. ("Like civilian comp/con units, neither mute drives nor comp/con wingmen require shackling or cycling.") This is likely an error as the term mute drive no longer appears anywhere else in the text.

**The Solution:** 
Replace the reference to Mute Drive with Copy Drive.

**The Location:**
pg 380 Smart Weaponry

**Comment by Jay-Iles** [comment]
Fixed.
