### ISSUE TITLE
[Typo] November Release: Index Entry Discrepancies

### ISSUE THREAD

**Issue by grassy-gnoll** [AshleyMoni/Lancer-Community-Edition#578]
**The Problem:**
All index entries in left-hand column of page 426 between "GMS Core Bonuses" and "First Emergence" point to page 415, the entry for "Ungrateful Interactions."

**The Solution:**
Change PDF anchors to respective pages for each index entry.

**The Location:**
Page 426, Index section

**Comment by KaiTave** [comment]
This appears to have been fixed as of the latest version.
