### ISSUE TITLE
[RAI] November Release: Solidcore Maintaining Charges Between Missions

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#579]
**The Problem:**
A question has arisen regarding the Sherman's Solidcore integrated weapon as to whether or not it can maintain charges not just between scenes but between missions as well, given that it doesn't specify that charges are lost during full repairs.

**The Solution:**
If desired, it may be helpful to add a clause noting that all charges are lost during full repairs, otherwise no change is strictly necessary.

**The Location:**
Page 246

**Comment by lenaleciel** [comment]
Now specifies that charges are lost during a full repair, as of December Release.
