### ISSUE TITLE
[Typo] November Release: External Ammo Feed Self-Heat Formatting

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#580]
**The Problem:**
The External Ammo Feed system currently has its heat cost listed in the explanation for how the system functions rather than in the keyword listing, similar to how things such as AMATERASU Protocol does.

**The Solution:**
While as written the intent of the system and its function are both clear, for stylistic consistency it may be preferable to move the heat cost into the keyword portion of the textbox (i.e. "3 SP, Unique, Quick Action, 1d3+1 heat (self)") and reword the rules text of the system to simply read "1/round, you can ACTIVATE this system to reload a LOADING weapon."

**The Location:**
Page 229

**Comment by Jay-Iles** [comment]
Fixed.
