### ISSUE TITLE
[Typo] November Release: Lesson of the Held Image Wording Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#582]
**The Problem:**
Lesson of the Held Image currently reads: "1/round, as a reaction at the start of an allied character’s turn, **you may attempt to LOCK ON** to any character within SENSORS."

**The Solution:**
The use of the word "attempt" is somewhat unusual here because there isn't any roll to determine Lock On, it's an action that simply happens automatically. It may be clearer to state this core bonus as "1/round, as a reaction at the start of an allied character’s turn, **you may make a LOCK ON tech action against any character within SENSORS.**"

**The Location:**
Page 191

**Comment by lenaleciel** [comment]
As a side note, the Lock On tech action itself specifies that you need to target a character both in Sensors and Line of Sight. If this core bonus is meant to specifically let you use the Lock On Tech Action as a Reaction, then it might help to reiterate that you need Line of Sight here, as just stating that you need to target a character in Sensors implies that you don't need LoS, even though the Lock On action requires it.

**Comment by Jay-Iles** [comment]
Fixed: "1/round, as a reaction at the start of an allied character’s turn, you may make a Lock On tech action against any character within line of sight and Sensors."
