### ISSUE TITLE
[Feature Request] Rename Assault NPC's Brace reaction.

### ISSUE THREAD

**Issue by darloth** [AshleyMoni/Lancer-Community-Edition#583]
**The Problem:**
The Assault type NPCs have a reaction called Brace.  It is very different from the player's Brace.  This can cause confusion at the table, where someone says "But they Braced last turn!".  Well, yes, but not the -same- brace, you see? Their brace is different...

**The Solution:**
Given that it has no lasting benefits or lasting drawbacks like the player's Brace reaction, I think it should be renamed.  Something like "Hunker Down" or "Endure" would be fine.

**The Location:**
Page 290 of November Release Core Book.

**Comment by Jay-Iles** [comment]
Fixed - it's now Hunker Down.
