### ISSUE TITLE
[RAI] November Release: Annihilator, Heat Generation, Infinite Recursion

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#584]
**The Problem:**
As written, the Annihilator might be read as causing recursive attacks, i.e. triggering the on hit effect that makes more attacks with the extra attacks it gets for hitting. A similar weapon, the Annihilation Nexus has been edited to specify that the extra attacks don't recurse.

Additionally, it is unclear as to whether the extra attacks also trigger the Annihilator's Heat cost.

**The Solution:**
In all likelihood, this is not meant to recurse, and a line stating that might be necessary.
Also check with Tom to see if you are meant to take Heat for each extra attack you get or not.

**The Location:**
pg. 252.

**Comment by Jay-Iles** [comment]
Annihilator now reads: "On Hit: Make a secondary attack against all characters within Burst 1 of the target. These attacks can’t deal bonus damage, and don’t trigger the Annihilator’s heat cost or secondary attacks."
