### ISSUE TITLE
[RAI] November Release: Barbarossa's Apocalypse Rail and Duration

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#586]
**The Problem:**
The Barbarossa's Core Active, Apocalypse Rail, functions so that you start charging the weapon, and for the rest of the battle, can fire the weapon at certain levels of charge, going back to the uncharged state after firing. Once you do so, it continues to charge back up, allowing the player to fire the Apocalypse Rail again in the same battle with a single use of Core Power. This is intentional.

However, nothing in the Apocalypse Rail's rules text says that you ever stop charging, meaning that the charging state persists even when the scene ends, letting you use it and actually fire it in multiple fights without limit.

**The Solution:**
Clarify that you stop charging and lose your Apocalypse Die at the end of the scene.

**The Location:**
pg. 228.

**Comment by Jay-Iles** [comment]
Added clarification.
