### ISSUE TITLE
[RAI] November Release: Goliath's Heavy Frame

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#587]
**The Problem:**
All instances of the Heavy Frame trait between PC and NPC mechs state "The [Mech] can’t be pushed, pulled, knocked PRONE, or knocked back by smaller characters." except for the Goliath's Heavy Frame trait, which says "The Goliath cannot be knocked PRONE, pushed, or pulled by smaller characters."

**The Solution:**
Unify the trait effect by changing the Goliath's version to read the same as the Drake, Barbarossa, and Demolisher.

**The Location:**
pg. 300, Heavy Frame on the Goliath.
You may want to consult the Drake on page 132, the Barbarossa on page 226, and the Demolisher on pg. 298.

**Comment by Jay-Iles** [comment]
Fixed.
