### ISSUE TITLE
[Typo] November Release PDF bookmarks

### ISSUE THREAD

**Issue by Eldraen** [AshleyMoni/Lancer-Community-Edition#588]
**The Problem:**
In the most up to date version of the pdf the GM section is lacking the NPC profiles bookmarks, even tho it was in the backer release.

**The Solution:**
Add it back in, maybe separate the bookmark into NPC roles.

**The Location:**
In the bookmark bar on the pdf, in the book itself on page 286

**Comment by KaiTave** [comment]
NPC Classes have bookmarks as of the latest release.
