### ISSUE TITLE
[Typo] Ronin NPC Perfect Parry/Rebound Clarification 

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#589]
**The Problem:**
"**PERFECT PARRY** makes it dangerous for enemies to attack Ronins with ranged weapons,"

**The Solution:**
The ability that was named Perfect Parry in the last draft has been renamed to Rebound in this one, and the mention of Perfect Parry in the Ronin's Tactics section should be updated accordingly.

**The Location:**
Page 310

**Comment by Jay-Iles** [comment]
Fixed.
