### ISSUE TITLE
[Typo] Ronin NPC Echo Edge Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#590]
**The Problem:**
"At the start of the Ronin’s turn, the Ronin **can clear all RONIN’S MARKS** as a free action, automatically dealing 1d6 kinetic AP to all characters that have a RONIN’S MARK **and clearing the marks.**"

**The Solution:**
The wording in this sentence is somewhat redundant. One possible alternative might be something along these lines: "At the start of the Ronin’s turn, the Ronin can clear all RONIN’S MARKS as a free action, automatically dealing 1d6 kinetic AP to all characters that have a RONIN’S MARK cleared in this way."

**The Location:**
Page 310

**Comment by Jay-Iles** [comment]
Fixed.
