### ISSUE TITLE
[RAI] November Release: Stabilize Ally Adjacency Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#591]
**The Problem:**
The current entry for clearing conditions using Stabilize in the description of the action reads "Clear an allied character’s condition that wasn’t caused by one of their own systems."

**The Solution:**
In the last draft, this was stated as allowing you to clear an ADJACENT allied character's condition. Unless this is a deliberate change to the functionality of using Stabilize to clear allied characters' conditions, then both explanations of the Stabilize action should state that adjacency is required, i.e. "Clear an **adjacent allied character’s** condition that wasn’t caused by one of their own systems."

**The Location:**
Page 71

**Comment by lenaleciel** [comment]
As a note, while you're looking at Stabilize, it may be a good idea to look at #297, as there are ways to self-inflict conditions that are not Systems.

**Comment by Jay-Iles** [comment]
Now confirmed that it must be an adjacent ally, and that it can't remove conditions caused by your 'systems, talents, etc'.
