### ISSUE TITLE
[Typo] November Release: License and Talent Ranks/Points Terminology Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#592]
**The Problem:**
There are several places in the early introductory chapter which refer to talents and licenses in terms of "points" but "ranks" is used elsewhere, leaving things somewhat unclear.

**The Solution:**
My suggestion is to amend these instances to use "ranks" instead to make it clear what is being referred to.

**The Location:**
Page 18 ("Reallocate all **points** from one of your talents to any other talent, Reallocate all **points** from one of your licenses to any other license, If reallocating **points** from one license to another"), the level chart on page 19, page 127 ("For example, with six **points** in IPS-N licenses"), page 158 ("For example, with six **points** in SSC licenses"), page 191 ("For example, with six **points** in HORUS licenses"), page 225 ("For example, with six **points** in HA licenses")

**Comment by Jay-Iles** [comment]
Fixed.
