### ISSUE TITLE
[RAI] November Release: Heavy Gunner, "line of sight of one of your heavy ranged weapons"

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#593]
**The Problem:**
The first rank of Heavy Gunner reads "choose a character within Range and line of sight of one of your heavy ranged weapons." Generally, things wouldn't be within line of sight to one of your weapons, they'd be in Line of Sight to you.

**The Solution:**
Swap Range and line of sight so that it reads, "choose a character within line of sight and Range of one of your heavy ranged weapons."

If this is intended to interact with Arcing or Seeking weapons in some way, which is unlikely, check with Tom, then it may be better to spell that out for clarity's sake.

**The Location:**
pg. 97

**Comment by Jay-Iles** [comment]
Fixed.
