### ISSUE TITLE
[Typo] November Release: Hive NPC Fluff Inconsistency, Miguel's Input Requested

### ISSUE THREAD

**Issue by SacarineMountain** [AshleyMoni/Lancer-Community-Edition#594]
**The Problem:**
In theory, the mechs developed after the Deimos Event aren’t too different from their
older cousin

Inconstant (and a little illogical) with current lore/rule set

**The Solution:**
change "mechs" to "nexus"

**The Location:**
Page 302 Dec 3 Itch.to release

**Comment by lenaleciel** [comment]
Changed to "drones and drone swarms" as of December Release.
