### ISSUE TITLE
[Typo] November Release: Barricade Graviton Lance

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#597]
**The Problem:**
The Graviton Lance is using the old formatting of +X/tier instead of the current +X/+Y+Z formatting for its attack bonus

**The Solution:**
Should say +1/+2/+3 instead

**The Location:**
Page 291

**Comment by lenaleciel** [comment]
Also note the use of the written out word Accuracy as opposed to the symbol for Accuracy.

**Comment by Jay-Iles** [comment]
Fixed.
