### ISSUE TITLE
[Typo] November Release: Swallowtail flavor header

### ISSUE THREAD

**Issue by jpbrodsky** [AshleyMoni/Lancer-Community-Edition#599]
**The Problem:**
"The Swallowtail’s base model, the SW-01, is one of SSC’s few mass-produced
lines**,** and the entry-level BELLA CIAO model."

The third comma (after "lines") is ungrammatical.

**The Solution:**
"The Swallowtail’s base model, the SW-01, is one of SSC’s few mass-produced
lines and the entry-level BELLA CIAO model."

or (probably clearer)

"The Swallowtail’s base model, the SW-01, is one of SSC’s few mass-produced
lines and is the entry-level BELLA CIAO model."

**The Location:**
P184

**Comment by Jay-Iles** [comment]
I don't think this is ungrammatical? It's an example of the Oxford Comma, though I'll have to review the document and see what our general policy is on serial commas.

**Comment by jpbrodsky** [comment]
It's not reading as an Oxford comma to me--this may be an ambiguity in the text.

The Oxford comma is for three (or more) items in a list:
The Swallowtail’s base model, the SW-01, is:
1) one of SSC’s few mass-produced lines
2) and the entry-level BELLA CIAO model
3) ???

Perhaps this could be:
The Swallowtail’s base model is:
1) the SW-01, 
2) one of SSC’s few mass-produced lines,
3) and the entry-level BELLA CIAO model.

"The Swallowtail’s base model is the SW-01, one of SSC’s few mass-produced lines, and the entry-level BELLA CIAO model.

But I don't love this version since it's stretching the parallelism.

**Comment by Jay-Iles** [comment]
Alright, gonna go with: "The Swallowtail’s base model, the SW-01, is one of SSC’s few mass-produced lines – the entry-level BELLA CIAO model."
