### ISSUE TITLE
[Typo] November Release: Gorgon's Vorpal Gun is missing a reaction statblock

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#600]
**The Problem:**
The Vorpal Gun describes its reaction in the statblock for the weapon itself, rather than providing a statblock for the reaction ala Autopod. This doesn't affect the rules themselves, but adding a statblock would conform to the style being used.

**The Solution:**
Going off Autopod's example, we can replace the rule text in that weapon's statblock with the following: "Gain the ________ reaction, which is the only way you can attack with the Vorpal Gun:" This can be preceded with some descriptive text per devs' discretion.

The reaction, whatever it would be called, can then have this reaction block:

_(Insert some good title here, bonus points if it's a metal band or something)_
Reaction, 1/round
Trigger: A hostile character within RANGE and line of sight deals damage to an allied character.
Effect: You may attack the hostile character with the Vorpal Gun.

**The Location:**
Page 205 for Vorpal Gun, Page 198 for Autopod example

**Comment by Jay-Iles** [comment]
Added the Reaction, now just needs a reaction name.

**Comment by lenaleciel** [comment]
Now has a block and is named Snicker-Snack as of December Release.
