### ISSUE TITLE
[Typo] November Release: Missing(?) "Gain the following QUICK TECH options:" for Hydra's Puppetmaster

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#602]
**The Problem:**
The Puppetmaster system doesn't have sub-heading text stating "Gain the following QUICK TECH options:". Compare to Goblin's H0R_OS System Upgrade II as an example of a system that does. While the statblock's layout implies that the two entries are separate options, it may be good to include the "Gain the following QUICK TECH options:" text for consistency and clarity.

**The Solution:**
Add the text ala Goblin's H0R_OS System Upgrade II

**The Location:**
Page 208 for Puppetmaster, page 199 for Goblin's thing

**Comment by Jay-Iles** [comment]
Fixed.
