### ISSUE TITLE
[Typo] November Release: UNCLE-class Comp/con Capitalization Consistency

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#603]
**The Problem:**
The title for the Raleigh's UNCLE system currently reads "UNCLE-class Comp/con"

**The Solution:**
Based on the similar GMS entry, this should be capitalized as such: "UNCLE-class Comp/Con"

**The Location:**
Page 147

**Comment by Jay-Iles** [comment]
Fixed.
