### ISSUE TITLE
[RAI] November Release: Paracausal Weapon mods and immunity

### ISSUE THREAD

**Issue by liq3** [AshleyMoni/Lancer-Community-Edition#605]
**The Problem:**
The exotic template paracausal weapon mod says it ignores immunity. The PC one (saladin LL3) doesn't. They seem like they should work the same, and it's unclear whether they should ignore immunity or not. 

**The Solution:**
Make it clear whether it should ignore immunity. 

**The Location:**
pg 327, and pg 245.

**Comment by lenaleciel** [comment]
Exotic template no longer says it ignores immunity as of December Release.
