### ISSUE TITLE
[RAI] November Release: Argus Armor interactions with system destruction.

### ISSUE THREAD

**Issue by darloth** [AshleyMoni/Lancer-Community-Edition#607]
**The Problem:**
Argus Armor is defined as a system.  This means it can be destroyed.
What happens when it's destroyed?  Does the Ultra immediately drop to their default armour level?  What happens if they had 0 armour - does the armour level rise to the default?
Even if we assume the vaguely sensible approach of "the armour drops to the default but does not go up from the current value" that leads to cases where it could be beneficial to lose Argus Armor at the right time.

It also opens up a whole different set of what-ifs when the Argus Armor system is destroyed but then repaired - does the Ultra go back up to 6 armour?  Why not, if it dropped to something while it was destroyed - unless we're meant to track the 'destroyed' Argus Armor value.

**The Solution:**
If it were a Trait, this wouldn't be an issue.  Consistent and dependable results every time.  If it really should be a system, we need some extra rules covering the various special cases.

**The Location:**
Pg 330

**Comment by lenaleciel** [comment]
Now a trait as of December Release.
