### ISSUE TITLE
[Typo] November Release: NPC Invade Action To-Hit Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#608]
**The Problem:**
The general Invade action for NPCs currently doesn't provide information regarding what should be rolled, as NPCs do not have a general "tech attack" stat like PC mechs do.

**The Solution:**
Per the PRv2, the description of the NPC Invade option states "The NPC makes a Systems vs. E-Defense tech attack against a character in sensor range." This should be noted in the current version of the rules as well.

**The Location:**
Page 280

**Comment by Jay-Iles** [comment]
Fixed.
