### ISSUE TITLE
[Typo] Tier 3 Hive stat block error

### ISSUE THREAD

**Issue by nonshay** [AshleyMoni/Lancer-Community-Edition#609]
Problem:
Tier 3 Hive NPC has the same stat block as the Tier 3 Hornet. Presumed copy/paste error.

Solution:
Tier 3 Hive stat block from previous edition:
HP 20
Evade 10
E-D 16 
Heat 8 
H+1 
A+0 
S+4 
E+1 
Armor 1 
Spd 5 
Sense 10 
Save 17 
Size 1

Location:
Page 302

**Comment by Jay-Iles** [comment]
Fixed.
