### ISSUE TITLE
[RAW/RAI] November Release: P.64 "Range and Pattern" Issues

### ISSUE THREAD

**Issue by Luciferos** [AshleyMoni/Lancer-Community-Edition#610]
**The Problem:**
There are two major problems related to the Range and Pattern (Cone/Line/Burst) concepts.

1. There is a strong ambiguity on p.64, "Range and Patterns"  that implies that Pattern weapons without a Range stat can gain Range from mech/system/Core buffs:

![image](https://user-images.githubusercontent.com/20429868/70461922-c9657c80-1a87-11ea-9aa6-44cc41d4aa52.png)

It seems that the intent is that, following the other paragraph, that you can increase the range of Pattern attacks that HAVE the Range stat, not ones that don't; in essence, the Range of a Pattern weapon is "N/A" unless it lists a range. However, this is strongly ambiguous, and some interpretations have come up that this means that Pattern weapons all implicitly have "Range 0" that can be extended. This would lead to obvious major balance issues with CQB AoE weapons being fired at ludicrous ranges.

2. The second problem is that the first paragraph of the above linked content suggests that not all Pattern weapons have Range, but MANY effects in the books list "within range" as a stipulation (often bolding Range, even when they also implicitly or explicitly include Pattern weapons as usable for their effects). I.E. TLALOC Protocol. There's a conflict here, but the RAI seems to mean "in range" for Pattern weapons to mean "anything you could hit with the pattern." However, it's again ambiguous.

**The Solution:**
1. A brief addendum/edit to the last sentence in Range and Patterns to add words to clarify that it only applies to Pattern weapons that HAVE a Range stat. For example:

>This does not affect the size of the area affected by CONE, LINE, BURST and BLAST attacks, although it does increase the RANGE **of such attacks that have a listed RANGE**.

2. A brief addendum to the section about Patterns that explicitly states that effects that call for you to choose targets "in Range" of your weapon can be used by Pattern weapons on any target you could hit with its pattern. For example:

>Some weapons and systems have special attack patterns: LINE� , CONE�, BLAST�, and BURST�. These attacks affect all targets within a defined area. A separate attack roll is made for each target, but damage is only rolled once and bonus damage is halved if there are multiple characters affected. **For any ability or effect calling for you to choose a target or targets within Range, a weapon with a pattern can choose any target that could be hit by its pattern.**

**The Location:**
Backer Release/Free Version p.64

**Comment by KaiTave** [comment]
The text for this in PRv2 states "Some mech licenses or systems include increases to range. This range increase does not affect the size of cones, lines, or blast attacks (though it might allow you to place such attacks at further range if a range is specified)."

**Comment by lenaleciel** [comment]
December Release has returned to specifying that Range increases only apply to AoE attacks with listed range already, and that pattern weapons can pick any target that could be hit by it's pattern for targets in range.
