### ISSUE TITLE
[Typo] November Release: Pegasus Omnigun description

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#611]
**The Problem:**
This release states "it doesn’t require a mount, nor does it have a weapon type or size – meaning that it can’t be modified **by** or benefit from your talents." The bolded word here wasn't in the PRv2 copy, and the inclusion here may imply that actual weapon mods are okay to put on this weapon, especially since it's not stated that it's an integrated weapon. This would be counter to how it used to work, and seems very likely unintentional now.

**The Solution:**
Change to "it doesn’t require a mount, nor does it have a weapon type or size – meaning that it can’t be modified or benefit from your talents."

**The Location:**
Page 218

**Comment by Jay-Iles** [comment]
Fixed, removing the 'by'.
