### ISSUE TITLE
[Typo] November Release: Scout NPC Size Iconography Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#612]
**The Problem:**
The Scout NPC is listed as being either size 1/2 or size 1, but the icon in the upper left corner simply notes it as size 1.

**The Solution:**
Replace this icon with the size 1/2 or size 1 icon as found in the Assassin or Witch.

**The Location:**
Page 313

**Comment by Jay-Iles** [comment]
Fixed.
