### ISSUE TITLE
[RAI] November Release: Specter NPC Monowire Sword Clarification Needed

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#613]
**The Problem:**
The Specter NPC's Monowire Sword has a currently listed range of "range 3, threat 3," which is something more suitable for a ranged weapon than the melee weapon that it is.

**The Solution:**
This is how the Monowire Sword was listed in the PRv2 as well, but in both cases it seems like this information is erroneous in some regard. Without a "correct" version to compare this to, consultation with Tom may be necessary to determine what the proper range for this weapon should be, i.e. should it be threat 3, is it meant to be threat 2, etc.

**The Location:**
Page 318

**Comment by lenaleciel** [comment]
Range removed as of December Release.
