### ISSUE TITLE
[Typo] November Release: Burst Range Pattern Error and Clarifications

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#616]
**The Problem:**
The current version of the game describes Bursts as such "Affects characters within a radius of X
spaces, **centered on but not including the space occupied by the user (or target).** The attacker is not affected by the attack unless specified. Cover and line of sight are calculated from the character."

**The Solution:**
This is actually at odds with how Bursts are outlined in the PRv2, and following this explanation strictly means that things like mines do not affect their own space, merely the area around them, or that Flechette Launchers cannot attack someone occupying the same space. The PRv2 description of bursts reads as such: "Burst is an area **affecting a character’s own space and X spaces in a radius around it.** Characters are not affected by their own burst attacks unless specified. Check cover and
line of sight from the character. Make separate attack rolls for each target caught in the area."

The description for Bursts in the current draft should in all likelihood be amended to something more in line with the PRv2 description in order to prevent unintended rules interpretations.

As part of this, you may also want to slightly clarify the Tokugawa's Annihilator weapon to read "On Hit: Make a secondary attack against all **other** characters within burst 1 of the target. This attack can’t deal bonus damage." in order to specify that the secondary attack will not affect the initial target as well.

**The Location:**
Page 64, Page 104, icon primer on page 116, Annihilator page 252

**Comment by lenaleciel** [comment]
Page 64 correctly includes the origin space, while page 104 does not. 116 is debatable.

**Comment by KaiTave** [comment]
Duplicate of #692
