### ISSUE TITLE
[Typo] November Release: LB/OC Cloaking Field Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#617]
**The Problem:**
"You become SLOWED, but **all allied characters within a burst 2 area become INVISIBLE** as long as they remain completely inside the area."

**The Solution:**
This should specify that it affects your own mech as well, i.e. "You become SLOWED, but **your mech and all allied characters within a burst 2 area become INVISIBLE** as long as they remain completely inside the area."

**The Location:**
Page 187

**Comment by Jay-Iles** [comment]
Fixed.
