### ISSUE TITLE
[Typo] November Release: Missing "Gain the following QUICK TECH options:" for Iskander's Tesseract

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#618]
**The Problem:**
Tesseract seems to add two Quick Tech options, but is missing the standard "Gain the following QUICK TECH options:" blurb right before those options are listed and defined. See Goblin's H0R_OS System Upgrade I for an example of the standard format.

**The Solution:**
Add "Gain the following QUICK TECH options:" ala Goblin's H0R_OS System Upgrade I

**The Location:**
Page 237 for Tesseract, Page 198 for H0R_OS System Upgrade I

**Comment by Jay-Iles** [comment]
Fixed.
