### ISSUE TITLE
[RAI] November Release: Technophile NHP Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#619]
**The Problem:**
Questions have arisen regarding whether the Technophile talent mandates that you MUST include the Technophile custom NHP (thus locking you out of taking other NHP systems until you reach rank 3 of the talent and can include another NHP system along with the custom one) whenever you create a mech. 

**The Solution:**
Clarification in the rank 1 talent may be helpful to definitively state whether this is the case or not. While I am reasonably sure that the custom NHP is meant to be an optional inclusion in any mechs a player creates, Tom and Miguel as always should have the final word on the matter.

**The Location:**
Page 102

**Comment by lenaleciel** [comment]
Now says "You may choose for your mech to gain the following system." making it optional.
