### ISSUE TITLE
[Typo] November Release: Sentinel Drone Text Formatting Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#620]
**The Problem:**
The line "The sentinel drone can be redeployed to a new location or recalled as a quick action." does not appear to be indented in accordance with the rest of the system box's text.

**The Solution:**
A quick lookover for stylistic consistency may be warranted.

**The Location:**
Page 204

**Comment by Jay-Iles** [comment]
Fixed.
