### ISSUE TITLE
[RAI] November Release: "First Attack" vs "First Attack Roll"

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#621]
**The Problem:**
In the transition to November Release, various effects were changed from "first attack roll" to say "first attack." This has implications when it comes to area of effect attacks: First attack implies that the effects are on all the attack rolls in an aoe, while first attack roll means only the first attack you roll in an aoe has the effect apply.

**The Solution:**
If this was an intentional buff to the aforementioned effects, this is fine.
If it was not intentional, but "first attack" is meant to only apply to the first attack roll made in an AoE, clarify that somewhere.
If it was not intentional, and "first attack" is meant to apply to all the attacks made in an AoE, revert the effects that changed.

**The Location:**
Gunslinger I pg 95
Nuclear Cavalier I and II pg 99
Core Siphon pg 166

**Comment by Luciferos** [comment]
Just a note here - "First attack roll" has basically been completely eliminated, and effects now just influence an Attack. This is pretty much how the whole book is written now, and so pretty sure NucCav is supposed to be unified with this.

**Comment by lenaleciel** [comment]
December Release has reverted the aforementioned effects to "first attack roll"
