### ISSUE TITLE
[RAI] November Release: Clarification on Systems Lacking Unique Tag

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#622]
The Problem:
There are a number of non-weapon systems in the game which lack the Unique tag which may or may not require it for balance or clarity purposes. In no particular order:

-Monitor Module (a player could activate two instances of this system with a quick action each and gain 2d3 reaction attacks)
-Tesseract (a player could activate two separate instances of this system to utilize its effects twice in a single turn)
-Bulwark Mods (there's no balance issue here but also no benefit to having more than one instance aside, perhaps, from redundancy in case of critical damage)
-Mimic Mesh (a player could activate two instances of this system on their turn to gain the movement benefits for two characters)
-Plasma Gauntlet (in general the game seems to have ensured that limited use systems are categorized as Unique to prevent multiplicative stacking, and presently this system is not listed as unique)
-StunCrown (another limited use system without unique)
-ICEOUT Drone (and another one as well)

The Solution:
Designer input into these particular systems is necessary to determine whether they should be given the Unique tag. While non-unique systems can present interesting and clever mech design opportunities which do not seem particularly overtuned (there's nothing especially unbalanced about someone using two Ferrous Lashes in a turn, for example) these particular examples stand out as systems that merit additional consideration into whether or not are intended to be non-unique or if the omission is an oversight.

The Location:
Bulwark Mods page 142, ICEOUT Drone page 162, StunCrown page 171, Mimic Mesh and Monitor Module page 204, Tesseract page 237, Plasma Gauntlet page 253

**Comment by KaiTave** [comment]
Also double check the Nelson's Thermal Charge mod (page 142) for confirmation if it should remain non-unique or not.

**Comment by KaiTave** [comment]
Having asked Tom, the Nelson's Thermal Charge mod SHOULD in fact be unique.

**Comment by lenaleciel** [comment]
Relevant systems are now Unique as of December Release.
