### ISSUE TITLE
[Typo] November Release: Stasis Barrier Tag Spacing

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#624]
**The Problem:**
The Stasis Barrier's tags currently read "**2 SP,Limited 1**, Shield, Unique, Quick Action"

**The Solution:**
A space after the first comma appears to be needed, "**2 SP, Limited 1**, Shield, Unique, Quick Action

**The Location:**
Page 240

**Comment by Jay-Iles** [comment]
Fixed.
