### ISSUE TITLE
[Typo] November Release: Assassin Drone Text Formatting Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#625]
**The Problem:**
The Assassin Drone stats and the first paragraph in the Assassin Drone's text box do not appear to be indented in accordance with the rest of the system box's text.

**The Solution:**
A quick lookover for stylistic consistency may be warranted.

**The Location:**
Page 209

**Comment by Jay-Iles** [comment]
Fixed.
