### ISSUE TITLE
[Typo] November Release: Mesmer Charges Name Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#626]
**The Problem:**
In both the header at the top of the page as well as within the name of the system itself, "Mesmer Charge," singular, is used.

**The Solution:**
For stylistic consistency with other similar systems, this should be pluralized to "Mesmer Charges" in both cases.

**The Location:**
Page 216

**Comment by Jay-Iles** [comment]
Fixed.
