### ISSUE TITLE
[Typo] November Release: Clamp Mine Timing Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#628]
**The Problem:**
"Expend a charge to fire a cluster of miniature mines at a character within SENSORS . They must succeed on an ENGINEERING save, or the mines clamp on. **At the end of their turn**, the mines detonate"

**The Solution:**
While in line with the PRv2 text, this should probably read "At the end of their **next** turn" for consistency with other, similar effects.

**The Location:**
Page 237

**Comment by lenaleciel** [comment]
Now reads "end of their next turn" in December Release.
