### ISSUE TITLE
[Typo] November Release: Annihilator lore typo

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#631]
**The Problem:**
"tactical solutions are theorized and designed in the field as often as they are in the lab, with the former often **end up** outperforming the latter."

**The Solution:**
Either "tactical solutions are theorized and designed in the field as often as they are in the lab, with the former often **ending up** outperforming the latter."
OR
"tactical solutions are theorized and designed in the field as often as they are in the lab, with the former often outperforming the latter."

**The Location:**
Page 252

**Comment by KaiTave** [comment]
Duplicate of #694
