### ISSUE TITLE
[Typo] November Release: Grounding Charges Text Formatting

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#632]
**The Problem:**
In the text for the Gravity Grenade where it reads "Your target must succeed on an Agility save or be Slowed until they make no voluntary movements for a full turn on their own turn." neither the word Agility or Slowed are bolded as they generally are throughout the rest of the game's text.

**The Solution:**
These words should be bolded for stylistic consistency.

**The Location:**
Page 236

**Comment by lenaleciel** [comment]
Bolded as of December Release.
