### ISSUE TITLE
[RAI] November Release: Total Nitpick on "half damage, heat, or burn" phrasing

### ISSUE THREAD

**Issue by EWSouls** [AshleyMoni/Lancer-Community-Edition#635]
**The Problem:**
The phrase "half damage, heat, or burn," (as used in Covering Fire, or Unleash Scylla and Monitor Module after resolution of issue #536) can be easily misread as the "half" modifier applying only to the first list item, damage, as in "Half damage, (full) heat, or (full) burn.

This is enhanced by "half damage" often being used alone where applicable elsewhere, making it really quite easy to read "half damage" as singular phrase, followed separately by "heat" and "burn."

**The Solution:**
A change in phrasing could clarify that the "half" modifier applies to all listed harm types. Something like "half **of** [any?][all?][normal?][rolled?] damage, heat, or burn" could achieve that, if not a larger change to something like "half of harm" (though that would presumably be a much bigger consistency change). An additional word beyond "of" alone may be required to have it sound right, but I'm unsure what might be preferred.

**The Location:**
_"Half damage, heat, or burn" phrasing_
Covering Fire: 97
Monitor Module: 204
Unleash Scylla: 205
https://github.com/AshleyMoni/Lancer-Community-Edition/issues/536

_Standalone uses of "half damage"_
Destruction Of The Temple Of The Enemies of RA: 210
“Roller” Directed Payload Charges: 228
Plasma Gauntlet: 253
(etc, etc)

**Comment by jarena3** [comment]
I'd like to voice a recommendation that this issue be closed under `invalid` or `wontfix`. The text as written is grammatically correct for its intended reading and difficult to misunderstand, especially in context.
