### ISSUE TITLE
[RAI] November Release: Nuclear Cavalier II and Range Bonuses to Energy Weapons

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#636]
**The Problem:**
Various bonuses exist which grant Range or Threat bonuses to weapons that deal any Energy damage, such as the Tokugawa's Overclock or External Batteries. Currently, Nuclear Cavalier's second Rank makes it so that, while you're in the Danger Zone, the first attack you make on your turn also deals +1d6 Energy bonus damage on a hit. This has lead to strange rulings as naturally it would seem that the bonus damage specifically being Energy would turn on various bonuses that rely on the damage inflicted being Energy Damage, including the Range/Threat bonus effects of External Batteries and Overclock. However, it has been argued that since you don't know whether the attack will actually deal energy damage until you hit or not, you can't apply the Range/Threat Bonus because you might miss and thus not qualify your weapon as dealing Energy Damage.

...This was a stronger argument back when Nuclear Cavalier specifically applied to the first attack that hit on your turn, as opposed to the first attack you made as every attack was in a quantum state of "is this the attack that will have energy damage? dunno until it hits or misses." but ruling arguments have still came up.

The nature of Overclock and the Tokugawa's Limit Break trait means that this particular issue doesn't come up there, but it still applies to the External Batteries.

**The Solution:**
You can't just make Nuclear Cavalier say that it deals the bonus damage without the on hit marker because then you get people saying that it should deal the damage on a miss, perhaps with reliable or something like that.

If Nuclear Cavalier is intended to work with External Batteries, then you can either
1. Have a parenthetical explaining that "yes, this makes a weapon count as dealing energy damage at the point of attacking."
2. Don't change anything, and just give a general ruling that "yes, this is how it works," because as written, it can be interpreted either way, and the "it works" ruling is probably the more natural feeling ruling.

If Nuclear Cavalier is not intended to work with External Batteries, then you can either
1. Have a parenthetical explaining that "no, this doesn't make the weapon count as dealing energy damage at the point of attacking."
2. Just change Nuclear Cavalier back to dealing generic untyped bonus damage, dodging the problem, and avoiding confusion. 

**The Location:**
pg. 99 Nuclear Cavalier
pg. 250 Overclock
pg. 252 External Batteries

**Comment by KaiTave** [comment]
"On hit" does suggest to me that the attack is not going to benefit from any sort of preemptive range or threat increases in advance, and that's how I've always interpreted it.

**Comment by lenaleciel** [comment]
Nuclear Cavalier now makes the attack deal energy damage whether you hit or not, thus making it work with various energy dependent range/threat boosts.
