### ISSUE TITLE
[Typo] November Release: Missing "to" in Escort SITREP description

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#638]
**The Problem:**
"If the Objective is ever adjacent to two characters of opposing sides, it stops moving and can’t move until it is only adjacent characters from one side."

**The Solution:**
"If the Objective is ever adjacent to two characters of opposing sides, it stops moving and can’t move until it is only adjacent **to** characters from one side."

**The Location:**
Page 269

**Comment by KaiTave** [comment]
Duplicate of #698
