### ISSUE TITLE
[RAI] December Release: Nuclear Cavalier I and II "First Attack" Wording

### ISSUE THREAD

**Issue by Luciferos** [AshleyMoni/Lancer-Community-Edition#641]
**The Problem:**
The Nuclear Cavalier 1/2 wording has some ambiguity - it says when you're in the Danger Zone, the first attack you make on your turn deals bonus damage/heat. People are unsure if this is intended to mean your first attack on your turn gets bonus stuff IF you're in the DZ when you make it, and you completely lose the opportunity to NucCav if you're not in the DZ when you make your first attack; OR if it's intended to mean the first attack you make on your turn when in the DZ gets the bonus, so you could build heat via attacks and trigger NucCav off a subsequent attack.

The latter seems to be the intent (and meshes more closely with the PR2, except that now you can miss your NukeCav shot and lose it that way) but the former is closer to the current wording. See below.

![image](https://user-images.githubusercontent.com/20429868/70772848-cac2cd80-1d43-11ea-8919-c49d7ccfd6ad.png)

**The Solution:**
Change the wording to one of the following:

>"The first attack you make on your turn gains/deals [effect] if you're in the Danger Zone."
>"The first attack you make on your turn while in the Danger Zone gains/deals [effect]."

The latter seems better, because having it so you can both completely miss out on the opportunity to use your talent point(s) simply by not starting your turn in the DZ, AND being able to, due to the other NucCav changes, completely whiff and lose the talent even if you ARE in the DZ at the start of your turn, seems like a lot of bad feels.

**The Location:**
Backer/Free p.99
PR2 p.161 (for comparison)

**Comment by Jay-Iles** [comment]
Fixed, now it's 'the first attack roll you make on your turn while you're in the Danger Zone' and 'The first ranged or melee attack roll you make on your turn while in the Danger Zone '
