### ISSUE TITLE
[Typo] Berserker typo

### ISSUE THREAD

**Issue by RoosterHogfish** [AshleyMoni/Lancer-Community-Edition#642]
**The Problem:**
Beserker fluff text is missing first part of description.

"their weapon output by orders of magnitude. The archetype, best-known for
its use by Gen’Dal Merlos’s Knights of Imminent Destruction, is preferred
by pure combat-focus organizations, PMCs, and deniable-asset corps in
established states."

**The Solution:**
Add in missing text or re-write

**The Location:**
Top of page 293

**Comment by KaiTave** [comment]
Duplicate of #552 which has been noted as fixed by Jay.
