### ISSUE TITLE
[Typo] November Release: Typo in Iterative Worldbuilding intro

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#644]
**The Problem:**
"The second is to show you **theworlds** we envision exist in the world of LANCER, to give you an idea for creating your own unique worlds and landscapes."

**The Solution:**
"The second is to show you **the worlds** we envision exist in the world of LANCER, to give you an idea for creating your own unique worlds and landscapes."

**The Location:**
Page 274

**Comment by KaiTave** [comment]
Duplicate of #684
