### ISSUE TITLE
[Typo] November Release: AI Tag Wording Consistency

### ISSUE THREAD

**Issue by Luciferos** [AshleyMoni/Lancer-Community-Edition#645]
**The Problem:**
The wording of AI systems is still inconsistent in a few places. The tag rules on p.105 say the following:

>AI: A mech can only have one system with this tag installed at a time. A mech with this tag has an NHP or comp/con unit installed that can act on somewhat autonomously. A pilot can choose to hand over the controls to their AI or take control back as a protocol.

Three minor issues:

1. The RAW is correct but needs a minor clarity pass because it's not self-evident that "A mech with this tag" means a mech that is granted the tag by an AI saying it grants the tag (which the UNCLE C/C does not, for instance, because it can't drive your boat).

2. The wording for the actual AIs is inconsistent; many of them still use the term 'AI property' from prerelease days. I compiled a list below of AIs with the wrong wording and their pages; all others are correct.

3. The Everest Comp/Con Assistant Unit does not bold the "AI" keyword in "AI tag" like all other AIs, and this makes it hard to notice.

**The Solution:**
1. 
>"A mech can only have one system with this tag installed at a time. **Some AI systems grant the AI tag to the mech**. A mech with the AI tag..."

2. Change "AI property" to "AI tag" in the listed places below.

3. Bold 'AI' in the 'AI tag' on the Everest Comp/Con Assistant Unit

**The Location:**
AI Tag rule: Release p.105
AIs with the wrong wording: 

TLALOC, p.179
ATHENA, p.187
OSIRIS, p.200
SCYLLA, p.205
SISYPHUS, p.221
AGNI, p.233
VISHNU, p.245
AMATERASU, p.253

GMS Comp/Con with un-bolded keyword: p.120

**Comment by lenaleciel** [comment]
Every issue raised here seems to be fixed as of December Release.
