### ISSUE TITLE
[Typo] November Release: Ace NPC's Bombing Bay missing blast icon

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#646]
**The Problem:**
"This causes a 1 explosion that must at overlap with at least 1 space occupied by their target."

**The Solution:**
"This causes a **[blast AoE icon]** 1 explosion that must at overlap with at least 1 space occupied by their target." Basing the AoE icon used based on the PRv2 version of this system, which specifies blast.

**The Location:**
Page 286

**Comment by KaiTave** [comment]
Duplicate of #683
