### ISSUE TITLE
[Typo] November Release: Berserker NPC's Juggernaut refers to Avalanche Charge as just Charge

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#648]
**The Problem:**
"When the Berserker uses **Charge**, all characters adjacent to the path they follow or adjacent to their final position – hostile and allied – must succeed on a HULL save or be knocked Prone."

**The Solution:**
"When the Berserker uses **Avalanche Charge**, all characters adjacent to the path they follow or adjacent to their final position – hostile and allied – must succeed on a HULL save or be knocked Prone."

**The Location:**
Page 293

**Comment by KaiTave** [comment]
Duplicate of #682
