### ISSUE TITLE
[RAI] November Release: Confirming Infantry Squad Stats

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#655]
**The Problem:**
Tom has mentioned in the past on the discord server that the Infantry Squad NPC was tentatively receiving a number of changes, including the number of attacks it made and its attack ranges. While a previous ticket on this matter was noted and closed and the current version does have a reduced number of attacks, the rest of the NPC's stats remain unchanged, including its range.

**The Solution:**
Please double-check with Tom that the Infantry Squad statblock is what he intends for the final version. If the weapon ranges should be shorter or any other changes be desired by him, they should be incorporated into the final version.

**The Location:**
Page 323

**Comment by lenaleciel** [comment]
Infantry Range has been properly compressed in December Release.
