### ISSUE TITLE
[Typo] November Release: Hunter Talent Per Round Stylistic Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#656]
**The Problem:**
Both Lunge and Disdainful Blade state "Once a round" written out as such, but many other examples throughout the game use the formatting "1/round" for this instead.

**The Solution:**
Should this be consistent? If so there may be other examples in the game I'm not presently aware of.

**The Location:**
Page 97

**Comment by lenaleciel** [comment]
Fixed in December Release, though there's a minor typo now in Hunter III. #660
