### ISSUE TITLE
[Typo] December Release: Radiance refers to Overclock, not Limit Break

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#659]
**The Problem:**
The Tokugawa's Core Active, Radiance, still specifies that it stacks with Overclock, even though now it's Limit Break and not Overclock that gives a range/threat boost to stack with.

**The Solution:**
Rewrite the stacking clause of Radiance.

**The Location:**
page 250

**Comment by Jay-Iles** [comment]
Fixed.
