### ISSUE TITLE
[RAI] December Release: Engagement and Moving Away

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#664]
**The Problem:**
Lines were added to Engagement to clarify that "While engaged with a character, you can move normally as long as you don’t break engagement with that character," presumably to clarify that if you are Engaged, you can step to another square around that enemy without it eating up all your movement immediately. However, this now implies that you *can't* break engagement at all by moving away (and probably eating an Overwatch) which never has been a thing in previous editions.
**The Solution:**
Check with Tom to see if this is the intent. If not, rewrite the new lines, possibly adding a line clarifying that you can move away, though you'll probably trigger Overwatch.

**The Location:**
pg. 62

**Comment by KaiTave** [comment]
This is almost certainly just meant to imply "While engaged with a character, you can move without provoking overwatch as long as you don't break engagement with that character," I strongly doubt it's a rule change beyond that.

**Comment by KaiTave** [comment]
Okay, now that I slightly understand matters a bit more (I think), the wording for this is somewhat confusing at first. As Lena has explained it, the intent is basically "you cannot become repeatedly Engaged, losing your movement, by enemies you are already Engaged with." With that in mind, I might suggest slightly different phrasing such as "Engagement does not prevent you from moving at all. After you have become engaged with a character, you may make further moves normally, though beginning a move within that character's threat may provoke reactions such as Overwatch."

**Comment by Jay-Iles** [comment]
Now says: "After you have become engaged with a character, you may make further move actions as normal, though beginning a move within that character's threat may provoke reactions such as Overwatch."

**Comment by Jay-Iles** [comment]
Actually had a better thought on how to modify it:
'"After you have become Engaged with a character, you may make further move actions as normal and moving into other adjacent spaces does not stop your movement, though beginning a move within that character's threat may provoke reactions such as Overwatch."

**Comment by differentsmoke** [comment]
Guys, how about:

> **ENGAGEMENT**
> If a character moves adjacent to a hostile character, they both gain the ENGAGED status for as long as they remain adjacent to one another. Ranged attacks made by an ENGAGED character receive -1. Additionally, characters that become ENGAGED by targets of equal or greater SIZE during the course of a movement stop moving immediately and lose any unused movement. This is the only time the ENGAGED condition stops you from moving, and only if you weren't already ENGAGED with that same character. Moving to a space adjacent to a character you're already ENGAGED with does not stop your movement, but may result in reactions as usual.
