### ISSUE TITLE
[Typo] December Release: Clamp Bombs and inconsistent references

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#665]
**The Problem:**
Clamp Mines were renamed to Clamp Bombs to clarify that they aren't Mines, but their description still calls them mines.

**The Solution:**
Go through both the rules text and flavor text of the Clamp Bombs to make sure every instance of mines is changed to bombs. (Such as, "fire a cluster of miniature ~~mines~~ bombs" and "clamp-~~mines~~bombs can affix to designated")

**The Location:**
pg. 237

**Comment by Jay-Iles** [comment]
Fixed.
