### ISSUE TITLE
[RAI] December Release: Squads, Grapples, and Rams

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#666]
**The Problem:**
In Prv2, the Infantry Squad's Strength in Numbers feature, amongst other things, prevented them from Grappling or Ramming, This was removed in the transition to November Release and stayed removed in December Release.
**The Solution:**
Check with Tom to see if this is intended.

**The Location:**
pg 323

**Comment by Jay-Iles** [comment]
The Squad's Spread Out feature now includes: "As its size doesn’t reflect its mass, the Squad cannot Grapple or Ram."
