### ISSUE TITLE
[RAI]December Release: Tlaloc and multi target attacks

### ISSUE THREAD

**Issue by Thac0nius** [AshleyMoni/Lancer-Community-Edition#668]
**The Problem:**
Tlaloc says "a ranged or melee attack may be rerolled once per attack". This would limit it to only affect one roll per attack with multi target weapons. 

**The Solution:**
 "1 reroll per original target of the attack"

**The Location:**
Page 179

**Comment by KaiTave** [comment]
Or simply a clause stating that attacks which are made against more than one target may make one reroll per target.

**Comment by Jay-Iles** [comment]
The intent is that, for area attacks, you may reroll one of the attack rolls you make as part of the attack.
New phrasing:
"You become Immobilized until the start of your next turn; however, during this time, you may once per attack reroll a missed melee or ranged attack roll, choosing a new target within the attack’s Range. If the attack was part of an area of effect, it must target a character in the same area. Any given target can't be hit more than once as part of the same action."

**Comment by Jay-Iles** [comment]
Now it's: 
Your NHP can rapidly fire and retarget your weapons – far faster than thought. You become Immobilized until the start of your next turn; however, during this time, you may reroll each missed melee or ranged attack roll once, choosing a new target within the attack’s Range. If the attack was part of an area of effect, it must target a character in the same area. Any given target can't be hit more than once as part of the same action.
