### ISSUE TITLE
[Errata] Flicker Field and Stun Crown text in incorrect order

### ISSUE THREAD

**Issue by grandar-lr** [AshleyMoni/Lancer-Community-Edition#67]
**The Problem:**
The Flicker Field and Stuncrown are displayed in different orders in the licence summary and full equipment text. Tom has ruled that the licence summary takes precedence.

**The Solution:**
Swap the two items in the full equipment text section.

**The Location:**
Summary: pg200
Full Equipment Text: pg202

**The Ratification:**
![ruling](https://user-images.githubusercontent.com/46637904/51108450-25fbef80-1857-11e9-9f20-9ccc39f9dc22.PNG)

**Comment by KaiTave** [comment]
Corrected in prerelease.
