### ISSUE TITLE
[Typo] Vorpal gun reaction name (pre-print)

### ISSUE THREAD

**Issue by Thac0nius** [AshleyMoni/Lancer-Community-Edition#670]
**The Problem:**
Vorpal gun states you "gain the XXXX reaction" the following reaction is named snicker-snack. 

**The Solution:**
"Gain the Snicker-Snack reaction, which is the only way you can attack with this weapon."

**The Location:**
Page 204

**Comment by VertigoCharades** [comment]
Duplicate of #662
