### ISSUE TITLE
[RAI] December Release: Kinetic Mass Transfer

### ISSUE THREAD

**Issue by Thac0nius** [AshleyMoni/Lancer-Community-Edition#671]
**The Problem:**
There is no indication of whether the effect described second sentence of Kinetic Mass Transfer, ramming a character into an obstacle for damage, is 1/round and currently reads as being unlimited.

**The Solution:**
Rephrase ability so that "1/round" isn't strictly tied to the first effect/sentence. 

**The Location:**
Page 98

**Comment by Jay-Iles** [comment]
Now it's:
1/round, if you Ram a target into...  

- ...a space occupied by character, the other character must succeed on a Hull save or be knocked Prone. 
- ...an obstruction large enough to stop their movement, your target takes 1d6kinetic damage.
