### ISSUE TITLE
[Typo] December Release: Monarch Divine Punishment Formatting Error

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#672]
**The Problem:**
The Monarch's Divine Punishment ability is currently using the orange color and corner iconography for a protocol, though it's a full action.

**The Solution:**
Divine Punishment should use the green color and appropriate iconography for a full action.

**The Location:**
Page 176

**Comment by Jay-Iles** [comment]
Fixed.
