### ISSUE TITLE
[Typo] December Release: Technophile I & II Font

### ISSUE THREAD

**Issue by snw-0** [AshleyMoni/Lancer-Community-Edition#673]
**The Problem:**
The "flavor text" on the NHP blocks in Technophile I & II don't use the different, italic font usually used for flavor text.

**The Solution:**
They should use the same font as elsewhere, e.g. in Technophile III.

**The Location:**
Page 102.

**Comment by Jay-Iles** [comment]
Don't they?
<img width="207" alt="Screenshot 2019-12-19 at 16 13 02" src="https://user-images.githubusercontent.com/29062057/71189267-71dec200-227a-11ea-90b3-f57849884791.png">

**Comment by snw-0** [comment]
No, the font is different; other places use a monospace font: 
![image](https://user-images.githubusercontent.com/2808851/71190073-8060b580-2249-11ea-85fd-60bc6cadab80.png)

**Comment by Jay-Iles** [comment]
Ah, my apologies!
