### ISSUE TITLE
[Typo] December Release: Nelson Thermal Charge Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#674]
**The Problem:**
The Nelson Thermal Charge system is listed as "Thermal Charges" at the top of the page.

**The Solution:**
Either one of these is fine, pluralized or not, but one specific form should probably be used for both.

**The Location:**
Page 142

**Comment by Jay-Iles** [comment]
Now it's Thermal Charge in the header.
