### ISSUE TITLE
[Errata] Swarm body should be unique

### ISSUE THREAD

**Issue by grandar-lr** [AshleyMoni/Lancer-Community-Edition#68]
**The Problem:**
Swarm body should have the unique tag.

**The Solution:**
Give swarm body the unique tag.

**The Location:**
Pg229/230

**The Ratification:**
![ruling](https://user-images.githubusercontent.com/46637904/51108912-732c9100-1858-11e9-858a-9db4e1f3a5fb.PNG)

**Comment by KaiTave** [comment]
Corrected in prerelease.
