### ISSUE TITLE
[Typo] December Release: Ambiguity in trigger to Berserker NPC's Superhot Reaction

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#681]
The Problem:
"Trigger: The Berserker takes damage in melee." "In melee" isn't a game-defined term, and thus is a bit ambiguous as to whether this reaction:
-Can be done in response to an attack done within the Berserker's Threat (including ranged attacks)
-Can be done to someone dealing a ranged attack to the Berserker well out of its threat, as long as someone is engaged with the Berserker
Etc., etc.

The Solution:
"Trigger: The Berserker takes damage from a melee attack."

The Location:
Page 293

**Comment by Jay-Iles** [comment]
Fixed.
