### ISSUE TITLE
[Typo] December Release: Berserker NPC's Juggernaut refers to Avalanche Charge as just Charge

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#682]
The Problem:
"When the Berserker uses **Charge**, all characters adjacent to the path they follow or adjacent to their final position – hostile and allied – must succeed on a HULL save or be knocked Prone."

The Solution:
"When the Berserker uses **Avalanche Charge,** all characters adjacent to the path they follow or adjacent to their final position – hostile and allied – must succeed on a HULL save or be knocked Prone."

The Location:
Page 293

**Comment by Jay-Iles** [comment]
Fixed.
