### ISSUE TITLE
[Typo] December Release: Ace NPC's Bombing Bay missing blast icon

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#683]
The Problem:
"This causes a **1 explosion** that must at overlap with at least 1 space occupied by their target."

The Solution:
"This causes a **[blast AoE icon]** 1 explosion that must at overlap with at least 1 space occupied by their target." Basing the AoE icon used based on the PRv2 version of this system, which specifies blast.

The Location:
Page 286

**Comment by Jay-Iles** [comment]
Fixed.
