### ISSUE TITLE
[Typo] December Release: Witch NPC Predatory Logic Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#688]
The Problem:
The Witch NPC's Predatory Logic ability does not specify that the forced attack occurs/is treated as a reaction, as something like Law of Blades does.

The Solution:
The addition of a clause along this lines would help clarify how the forced attack works, as well as specifying that the Witch cannot use Predatory Logic to force attacks with superheavy weapons.

The Location:
Page 320

**Comment by Jay-Iles** [comment]
Here's the current text: "The Witch makes a tech attack against a character within Sensors. On a success, the target immediately and as a reaction uses a weapon chosen by the Witch to attack a character within Range chosen by the Witch." That works, right?
