### ISSUE TITLE
[RAI] December Release: Pilot Action Discrepancies

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#691]
**The Problem:**
On page 74, under Pilot Actions, the listed actions pilots can take are "BOOST, HIDE, SEARCH, ACTIVATE, DISENGAGE, PREPARE, OVERWATCH, MOUNT/DISMOUNT,... FIGHT, JOCKEY and RELOAD"
Meanwhile, on page 76, under Pilot Actions, the listed actions pilots can take are "BOOST, HIDE, SEARCH, ACTIVATE, SKILL CHECK, DISENGAGE, PREPARE, OVERWATCH, ...BRACE... FIGHT... JOCKEY...RELOAD"
**The Solution:**
Go over the lists and unify them, presumably so that all options are on both lists. Check with Tom to see which actions are intended to be on each list. Overwatch in particular is strange as Pilots cannot Skirmish by default.
**The Location:**
pgs 74 and 76

**Comment by Jay-Iles** [comment]
Here's the new list: "Boost, Hide, Search, Activate, Skill Check, Disengage, Prepare, Mount. Pilots can Overwatch, and use the Fight action when they do so."
