### ISSUE TITLE
[Typo] December Release: Burst Range Pattern Clarifications

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#692]
**The Problem:**
Burst attacks could still use some additional wording revisions to help make their function as clear as possible in several locations throughout the current release.

**The Solution:**
Page 64 currently states: "BURST X: affects characters within a radius of X spaces, centered on and including the space occupied by the user (or target). If the Burst is an attack, the user or target is not affected by the attack unless specified. Cover and line of sight are calculated from the character. If a BURST effect is ongoing, it moves with the character at its center." 

This is the wording that should be used later on in the Gear and Weapons section on page 104, and possibly on page 116 as well.

**The Location:**
Page 104, 116

**Comment by Jay-Iles** [comment]
Fixed.
