### ISSUE TITLE
[Typo] December Release: Sylph Typos

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#693]
The Problem:

"These semi-biological, skin-tight undersuits can be
worn for extended periods. They are translucent,
semi-liquid, **and able to be when not in use**,
**confirming** to whatever container they are placed in."

The Solution:

"These semi-biological, skin-tight undersuits can be
worn for extended periods. They are translucent,
semi-liquid, and able to be **stored** when not in use,
**conforming** to whatever container they are placed in."

The Location:
Page 114

**Comment by Jay-Iles** [comment]
Fixed.
