### ISSUE TITLE
[Typo] December Release: Annihilator Lore Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#694]
The Problem:
"tactical solutions are theorized and designed in the field as often as they are in the lab, with the former **often end up** outperforming the latter."

The Solution:
Either "tactical solutions are theorized and designed in the field as often as they are in the lab, with the former **often ending up** outperforming the latter."
OR
"tactical solutions are theorized and designed in the field as often as they are in the lab, with the former **often outperforming** the latter."

The Location:
Page 252

**Comment by Jay-Iles** [comment]
Fixed.
