### ISSUE TITLE
[RAI] Duelist III language clarification

### ISSUE THREAD

**Issue by SneepSnoop** [AshleyMoni/Lancer-Community-Edition#7]
**The Problem:**
Duelist III uses the words "immediately make an improvised attack, grapple, or ram as a free action." This implies it may be possible for a player to take this action between two attacks on a single two weapon mount. 

**The Solution:**
Additional action diagramming needed from Tom to clarify whether or not this can be broken up.

**The Location:**
Page 122.

**Comment by KaiTave** [comment]
Addressed in the prerelease version with clarified language.
