### ISSUE TITLE
[Typo] December Release: Assassin NPC's Heat Capacity

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#700]
The Problem:
The Assassin NPC's Heat Capacity goes from 7 at tier 1 to 8 at tier 2 to back to 7 at tier 3.

The Solution:
The pr2 version of the text had it stay consistently at 7 at all tiers.

The Location:
Assassin, pg 289

**Comment by Jay-Iles** [comment]
Fixed.
