### ISSUE TITLE
[Typo] December Release: Monstrosity Size Wording Consistency

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#701]
**The Problem:**
The size of the Monstrosity class NPC goes from "1 or 2" then "1-2" then "1-3" as you increase in tiers. 

**The Solution:**
To be consistent with other examples of variable sizes, this should be
Tier 1: 1 or 2
Tier 2: 1 or 2
Tier 3: 1, 2, or 3
The fact that tier 3 opens up size 3 Monstrosities seems intentional, it was that way in PR2.

**The Location:**
pg. 324

**Comment by Jay-Iles** [comment]
Fixed.
