### ISSUE TITLE
[Typo] December Release: Assassin Size Discrepancy

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#702]
**The Problem:**
At tiers 1 and 2, the Assassin can be either size 1/2 or size 1, while tier 3 only lists size 1.

**The Solution:**
This is most likely a typo as the prerelease had both sizes available at all tiers.
Adjust tier 3 to include both size 1/2 and size 1.

**The Location:**
pg. 289

**Comment by Jay-Iles** [comment]
Fixed.
