### ISSUE TITLE
[Errata] December Release: Shrike Code Errata

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#703]
**The Problem:**
Shrike Code (Neurospike invasion option) states it lasts until the end of your next turn

**The Solution:**
Should be "End of target's next turn" instead

**The Location:**
Page 170

**The Ratification:**
https://discordapp.com/channels/426286410496999425/441336855951048725/657065240349114398

Statement from Tom

**Comment by Jay-Iles** [comment]
Fixed.
