### ISSUE TITLE
[RAI] December Release: OASIS Clarification/Suggestion

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#706]
**The Problem:**
OASIS Wall currently states "Until the start of your next turn, you can only move in straight lines; however, you create a holographic trail behind you as you move, creating a light barrier made of contiguous sections **the same SIZE as your mech** in each space you move through"

The concern here is that since the OASIS Wall comes as part of the size 1/2 Dusk Wing's licenses, that a size 1/2 wall may not actually be very helpful for the majority of mechs which are size 1 and up.

**The Solution:**
It has been proposed that this be amended slightly to "creating a light barrier made of contiguous sections the same SIZE as your mech **rounded up** in each space you move through" This way size 1/2 mechs will produce size 1 barriers, without increasing the size for any other mechs that may use it.

**The Location:**
Page 171

**Comment by Jay-Iles** [comment]
Now it clarifies that Size 1/2 mechs produces Size 1 barriers, which I *think* is clearer than saying 'same Size, rounded up' given it addresses the specific case where that would trigger?
