### ISSUE TITLE
[Typo] December Release: Gorgon Core System Typos and Formatting

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#707]
**The Problem:**
The formatting of the text for the Gorgon's core system on the rightmost column of page 202 is currently laid out in such a way that the Gorgon's arm is obscuring elements of the text, making legibility of certain words and passages unclear. 

For example, the passage "Exposure to a basilisk typically causes immediate encephalitis, massive ocular and cranial hemorrhage, and death – survival is possible with tempering and interdictor heads-up displays," is currently obscured in such a way that the dash between death and survival is obscured, making it look as though punctuation and capitalization is missing.

In addition:

"but even then headaches, nausea, and confusion for a short period after viewing **is** possible."
This should most likely read:
"but even then headaches, nausea, and confusion for a short period after viewing **are** possible."

**The Location:**
Page 202

**Comment by Jay-Iles** [comment]
Reflowed so that no text is obscured, and fixed the typo.
