### ISSUE TITLE
[Typo] December Release: Reinforced Cabling Fluff Description Not Updated

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#710]
**The Problem:**
The Blackbeard's Reinforced Grapples were renamed to the Reinforced Cabling, presumably because they don't interact with Grappling, the game mechanic. However, the fluff description remains unchanged and refers to the system as Reinforced grapples.

**The Solution:**
Adjust the fluff to take into account the new name. Do note that just doing a copy/replace of "grapple" with "cabling" probably won't work here.

**The Location:**
pg. 131

**Comment by KaiTave** [comment]
To a certain extent I think most of the references to "grapples" in the fluff are probably fine to leave as is, my one suggestion would be "Reinforced **grappling cables** allow for full movement and utility in ≤1 g
environments."

**Comment by Jay-Iles** [comment]
Accepted Kai's suggested wording.
