### ISSUE TITLE
[RAI] December Release: Commander Template Press The Attack Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#712]
**The Problem:**
The Commander NPC template's Press the Attack reads "The Commander can attack the target, and
deals **half damage** if successful."

**The Solution:**
Double check with Tom to see if this should read "half damage, heat, or burn" instead, as many other such abilities in the game work (Heavy Gunner, Tactician's Overlapping Fire, etc).

**The Location:**
Page 326

**Comment by Jay-Iles** [comment]
Fixed, now 'half damage, heat or burn'.
