### ISSUE TITLE
[Typo] December Release: Flak Launcher Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#713]
**The Problem:**
The Barbarossa's Flak Launcher currently reads "Choose a flying character within range 15 and line of sight. They must succeed on an AGILITY save or become SLOWED and immediately land (this counts as falling without any damage); additionally, they can’t fly until the end of their next turn."

While it's fairly reasonable to come to the conclusion that the slowed condition to be temporary, the current wording makes it slightly ambiguous.

**The Solution:**
A suggestion for improved clarity is "Choose a flying character within range 15 and line of sight. They must succeed on an AGILITY save or immediately land (this counts as falling without any damage); additionally, they become SLOWED and can’t fly until the end of their next turn."

**The Location:**
Page 229

**Comment by Jay-Iles** [comment]
Fixed: now "They must succeed on an Agility save or immediately land (this counts as falling without any damage), and additionally become Slowed and can’t fly until the end of their next turn." which hopefully makes it clear that all effects are dependant on them failing the Agility save.
