### ISSUE TITLE
[Typo] December Release: Backer Characters Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#714]
**The Problem:**
Backer Aaron Wood has two listed entries in the Backer Characters index, which seem to be somewhat incomplete and/or redundant:

**Old relic of powered armor from the** 422 (re: “You”) Aaron Wood
**Old relic powered armour from the Little Wars** 422 (re: “You”) Aaron Wood

**The Solution:**
One of these seems to be in need of deletion.

**The Location:**
Page 431

**Comment by Jay-Iles** [comment]
Fixed.
