### ISSUE TITLE
[TYPO] December Release: Typos on pg 106

### ISSUE THREAD

**Issue by dwarf74** [AshleyMoni/Lancer-Community-Edition#715]
Under "Mine" - repeated "and" in "Upon deployment, it
arms at the end of the deploying character’s turn and –
unless otherwise specified – and is triggered"

Under "Personal Armor" - clumsy phrasing in "Putting on PERSONAL ARMOR takes 10–20
minutes to put on,"

**Comment by Jay-Iles** [comment]
Fixed.
