### ISSUE TITLE
[Typo] December Release: Personal Armor tag not used on Hardsuits

### ISSUE THREAD

**Issue by Eranziel** [AshleyMoni/Lancer-Community-Edition#719]
**The Problem:**
Hardsuits all use the "Armor" tag, instead of the "Personal Armor" tag. There is no "Armor" tag defined in the tags section.

**The Solution:**
Either the "Personal Armor" tag in the tags section should be shortened to just "Armor", or the hardsuits should use the "Personal Armor" tag.

**The Location:**
Pages 106 and 110 in latest PDF.

**Comment by Jay-Iles** [comment]
Fixed.
