### ISSUE TITLE
[RAI] December Release: Valid Directions and Specific Pull Effects

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#720]
**The Problem:**
Currently, there is a section on valid directions on page 106, likely meant to keep people from doing things like using a Ferrous Lash to yank people straight up into the air for fall damage, as it seems that that is not intended design space. However, the rules here specifically refer to cases in which effects cause "any direction". This does not lock out the case, for example, that someone is using a Mag Cannon or other effect that *specifies* a direction (away from you, towards you).

Additionally, the hostile version of Ferrous Lash doesn't actually use the "any direction" language, it says "a direction of your choice," and other systems, such as the Goblin's Puppet System Invasion option use the latter language as well.

**The Solution:**
Perhaps the restrictions on direction should be wrapped into Involuntary Movement instead? That may cause other issues, though. It would probably be best to talk to Tom about how he wants this to go in order to stop various fall damage cheese strategies.
In any case, if it is found that the current wording is fine, it would probably best to go through effects to replace any instances of moving another character in "a direction of your choice" with "any direction" or to specify that "a direction of your choice" also follows the same rules as "any direction."

**The Location:**
pg. 106 Valid Space and Direction
pg. 162 Mag Cannon, Ferrous Lash
pg. 96. Hacker I (A direction of your choice)
pg. 198 Puppet System (A direction of your choice)

**Comment by lenaleciel** [comment]
Oh, also check out the Nanobot Whip on page 195, though that might be fixable as is by a change to "free and valid" as opposed to just "free"

**Comment by Jay-Iles** [comment]
Replaced 
"Likewise, when a system or effect refers to “any direction”" 
with 
"Likewise, when a system or effect refers to voluntary or involuntary movement in a direction, such as “any direction”, "a direction of your choice", etc,"
