### ISSUE TITLE
[Errata] December Release: Explosive Vents Change Reminder

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#722]
**The Problem:**
Tom and Jay have discussed possible changes to the wording of Explosive Vents in an effort to prevent it from being overly abused by various systems such as the Fuel Rod Gun or Auto-Cooler, however Tom appears to have ultimately decided that the best solution is to keep the wording on Explosive Vents as it currently stands, but limit its use to 1/round.

**The Solution:**
Per Tom: "we'll probably just keep the old wording with 1/round
so FRG will work just fine"

**The Location:**
Page 232

**The Ratification:**
https://discordapp.com/channels/426286410496999425/441336855951048725/657645649537400858

https://discordapp.com/channels/426286410496999425/441336855951048725/657646696364376105

**Comment by Jay-Iles** [comment]
Now it's: "1/round, when you clear all heat or take stress, your mech’s cooling vents open and unleash a burst 1 explosion. Characters within the affected area take 2 heat and 2 burn."
