### ISSUE TITLE
[Errata] December Release: Death's Head Core Active Reminder

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#723]
**The Problem:**
Tom has mentioned in the new release feedback channel that he is considering a last minute adjustment to the Death's Head core active ability as its current implementation does not sit right with him. This is a reminder ticket for if he should decide he wishes to change it prior to locking the book down.

**The Solution:**
Per Tom: "looking at atm is death's head ult by the way which
has some weird potential whacky shit
the only change I'd make to it is to make the bonus damage scale on size (1/2/3d6 for aux/main/heavy)
because optimally right now you'd want to use a bunch of little accurate guns like the oracle
which doesn't really sit right with me
anyway that's it"

**The Location:**
Page 164

**The Ratification:**
https://discordapp.com/channels/426286410496999425/441336855951048725/656999230229053480

https://discordapp.com/channels/426286410496999425/441336855951048725/656999376862052372

**Comment by Jay-Iles** [comment]
Fixed - it's now 'you deal bonus damage based on weapon size  (aux: 1d6, main: 2d6, heavy or larger: 3d6)  on ranged critical hits against them'
