### ISSUE TITLE
[Typo] December Release: Death's Head Core Active Refers to "Marked For Death"

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#724]
**The Problem:**
The Death's Head Core Active Protocol says it gives you the "Marked For Death" action, while the listed action is labeled "Mark For Death"

**The Solution:**
Pick one and make it consistent between the two.

**The Location:**
pg. 164

**Comment by Jay-Iles** [comment]
Fixed.
