### ISSUE TITLE
[RAI] December Release: Mirage's Blip Not Requiring Sensors

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#727]
**The Problem:**
In the November Release, the Mirage NPC's Glitch Scanners Trait was split up into it's component parts for clarity, making it also grant the Blip Reaction which does the same thing but as a Reaction, as opposed to saying "you can do this as both a quick action and a reaction." 
However, the Blip Reaction does not follow the same constraints as the Glitch Scanners quick action (Glitch Scanners needs the ally to be in Sensors, while Blip does not.), even though it's supposed to be "the same thing, but a Reaction."

**The Solution:**
Specify in Blip that the allied character also needs to be in Sensors.

**The Location:**
pg. 304

**Comment by Jay-Iles** [comment]
Fixed.
