### ISSUE TITLE
[Errata] Centimane III Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#73]
**The Problem:**
The Virulent Swarm ability of Centimane III's Obliteration states "Any adjacent actors of your choice within
must repeat this check or also become Shredded."

**The Solution:**
Clarification of this sentence is required.  Within what?  Is the word "within" simply a typo since the ability already specifies it affects adjacent actors, or is there meant to be another qualifier but words are missing?

**The Location:**
Page 122

**Comment by AshleyMoni** [comment]
![image](https://user-images.githubusercontent.com/6186092/51192577-ce8c6c80-18b4-11e9-935e-601d2e75744b.png)

**Comment by KaiTave** [comment]
Corrected as of 1.8.5
