### ISSUE TITLE
[RAI] December Release: Operator's Telefrag and Successful Saves

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#730]
**The Problem:**
The Operator's optional Telefrag system isn't clear as to whether the target should be Jammed on a successful save, as it only says they take half damage on a successful save, unlike other similar systems (such as the Mercenary's Favors Owed which specifies that the additional prone effect doesn't work on a success.)

**The Solution:**
Add "and aren't Jammed" or similar to the line explaining what happens on a successful save.

**The Location:**
pg. 306

**Comment by KaiTave** [comment]
Resolved by Jay
