### ISSUE TITLE
[Typo] December Release: OSIRIS class NHP Typo

### ISSUE THREAD

**Issue by dwarf74** [AshleyMoni/Lancer-Community-Edition#732]
**The Problem:**
Extra letter in "parasubjectivityv" 

Potential - last paragraph, left column - "interpellator" - should it be spelled "interpolator" or is it a new word? 

**The Solution:**
"parasubjectivity" 

**The Location:**
200, 1st paragraph

**Comment by KaiTave** [comment]
"Interpellation" is a word that has to do with the internalization of cultural values and ideology, and it appears elsewhere in the text regarding NHPs, so I believe its use here is deliberate.

**Comment by Jay-Iles** [comment]
As Kai says, this is not a typo.
