### ISSUE TITLE
[Typo] December Release: Fragment Signal Formatting Correction

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#734]
**The Problem:**
"FRAGMENT SIGNAL. You feed false information, obscene messages, or phantom signals to your
target’s computing core. They become IMPAIRED and SLOWED until the end of their next turn."

The name "Fragment Signal" in this section isn't bolded like other Invade option names.

**The Solution:**
For consistency, "Fragment Signal" should be bolded.

**The Location:**
Page 70

**Comment by Jay-Iles** [comment]
Fixed.
