### ISSUE TITLE
[Typo] Awkward sentence structure in SSC Atlas's Multi Gear Maneuver System

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#736]
**The Problem:**
In the 12/22 release of the [SSC Atlas](https://massif-press.itch.io/the-atlas), there's a sentence that sounds a little off to me:

> Size 1/2 characters **that are able** to grab onto the line **that are adjacent** to either the start or end point of the zipline can move to the other end as a quick action.

It seems awkward and potentially grammatically incorrect to have two descriptive clauses starting with "that" in a row with no conjunction, when they both describe the same noun (i.e. "characters that X that Y", where X and Y both separately describe which characters are being talked about).

**The Solution:**
It might flow better and be more grammatically correct if connected by the conjunction "and":

> Size 1/2 characters that are adjacent to either the start or end point of the zipline and that are able to grab onto the line can move to the other end as a quick action.

(I've reversed the order just because it seems to make more logical sense to me - it matters first that they're actually next to the zipline, and only then is it relevant whether they're able to grab on.)

**The Location:**
12/22 release of the [SSC Atlas](https://massif-press.itch.io/the-atlas), p. 3, in the first bullet point under "Multi Gear Maneuver System".

**Comment by melodycwatson** [comment]
Noted and fixed. :)
