### ISSUE TITLE
[Typo] SSC Atlas, Jäger Kunst II - "does not recommended"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#737]
**The Problem:**
The flavor text for the SSC Atlas's Jäger Kunst II system says:

> SSC does not **recommended** using these embedded systems without proper bodily tempering.

**The Solution:**
The word "recommended" should be "recommend" instead:

> SSC does not **recommend** using these embedded systems without proper bodily tempering.

**The Location:**
12/22 release of the [SSC Atlas](https://massif-press.itch.io/the-atlas), end of p. 4, in the flavor text under "Jäger Kunst II".

**Comment by melodycwatson** [comment]
Noted and fixed. :)
