### ISSUE TITLE
[Typo] December Release: Nearlight Bolt Alignment

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#739]
**The Problem:**
The first paragraph of the Nearlight Bolt section uses Justified alignment, unlike the rest of the text.

**The Solution:**
Use the same alignment as the rest of the text

**The Location:**
pg. 371, first paragraph under Nearlight Bolt on the right.

**Comment by Jay-Iles** [comment]
Technically it is the same alignment as the rest of the text - it's just that the last line naturally fills that line. Even so, I've tweaked the tracking to make the gaps between words more natural.
