### ISSUE TITLE
[RAI] Wording on Reactive Weave

### ISSUE THREAD

**Issue by kotarou** [AshleyMoni/Lancer-Community-Edition#74]
**The Problem:**
As reactions are now 1/turn, Reactive weave's movement (a reaction) cannot ever be triggered after a brace (a reaction), despite the brace reaction being the trigger.

This may be a sub-issue of the new reaction wording being confusing.

**The Solution:**
Reword from "When you brace, your mech can immediately move its speed as a reaction and it also gains 
invisibility until the end of its next turn." to "When you take the brace reaction, your mech may also move its speed, and gains invisibility until the end of its next turn."

**The Location:**
204/205

**Comment by KaiTave** [comment]
Corrected in prerelease.
