### ISSUE TITLE
[Typo] December Release: Page Edge Headings Don't Match

### ISSUE THREAD

**Issue by Eranziel** [AshleyMoni/Lancer-Community-Edition#753]
**The Problem:**
The page edge headings on some sections of the compendium don't match the contents of the pages. For example, page 91 is part of the Talents subsection, but on the right margin of the page next to the section number it says "GEAR TAGS".

**The Solution:**
Correct the page edge headings to match the subsection the page belongs to.

**The Location:**
A few of these are debatable, but I included them for completion's sake. Pages 13, 59, 63, 91-107, 117, 263, 275-279, 337.

**Comment by Jay-Iles** [comment]
Fixed.
