### ISSUE TITLE
[Typo] December Release: Extraneous Space in Rank and File

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#756]
**The Problem:**
The Squad's Rank and File trait currently reads "The Squad can’t take the GRUNT, VETERAN, or ULTRA templates, and can never gain STRUCTURE." with an added space between the word "templates" and the comma following it.

**The Solution:**
Check to see if this is a kerning discrepancy or simply a misplaced space.

**The Location:**
Page 323

**Comment by Jay-Iles** [comment]
Fixed.
