### ISSUE TITLE
[Typo] December Release: bottom left 350 copasetic -> copacetic

### ISSUE THREAD

**Issue by Calvinfs852** [AshleyMoni/Lancer-Community-Edition#758]
**The Problem:**
The word copacetic is spelled copasetic in the PDF. While technically not incorrect, this is a very uncommon/unusual spelling of the word and the more common spelling should probably replace it.

cohesive and copasetic functioning of all states

**The Solution:**

cohesive and copacetic functioning of all states

**The Location:**
on page 350, halfway through the last line of the left column in the published PDF.

**Comment by Jay-Iles** [comment]
Fixed.
