### ISSUE TITLE
[Typo] Typos in Ace NPC

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#76]
**The Problem:**
"When the mech flies while it moves or boosts, it can drop a bomb on one target below as a free
action **it that it** passes over or adjacent to."

"This movement doesn’t provoke reactions, **ignores, engagement**, and any mechs engaged with the target when it activates this module must pass an agility check or be knocked prone."

**The Solution:**
"When the mech flies while it moves or boosts, it can drop a bomb on one target below as a free
action **that it** passes over or adjacent to."

"This movement doesn’t provoke reactions, **ignores engagement**, and any mechs engaged with the target when it activates this module must pass an agility check or be knocked prone."

**The Location:**
Page 354-355

**Comment by KaiTave** [comment]
Burst/Dash Module no longer exists, but the typo in the Bombing Bay system still persists.

**Comment by melodycwatson** [comment]
Fixed. :)
