### ISSUE TITLE
[Typo] December Release: Siege Specialist Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#760]
**The Problem:**
"1/round, before rolling an attack with a CANNON , all characters adjacent to you must succeed on a HULL save or be knocked back by 1 space and knocked PRONE. **Your** are then pushed 1 space in any direction."

**The Solution:**
"1/round, before rolling an attack with a CANNON , all characters adjacent to you must succeed on a HULL save or be knocked back by 1 space and knocked PRONE. **You** are then pushed 1 space in any direction."

**The Location:**
Page 100

**Comment by Jay-Iles** [comment]
Fixed.
