### ISSUE TITLE
[Typo] December Release: Talent section emphasis (small caps/bold)

### ISSUE THREAD

**Issue by jpbrodsky** [AshleyMoni/Lancer-Community-Edition#761]
In the talent section, starting on p90 in the latest itch release, there are some inconsistencies with bold/small-caps emphasis on certain words.

As a reader, I find it helpful when the use-case/requirement for each talent is emphasized (e.g. "flying" for Ace, "auxilliary ranged" for gunslinger). This is even more useful when the talent text does not contain many other emphasized words, though I understand the style guide says certain rule words should always be emphasized.

I'm not clear on the style rules for which words are bolded vs. small-capped, so I'm not making suggestions about which type of emphasis should be applied, only where I think some emphasis is applied inconsistently.

**Ace (p90)**
"Flying" is bolded in the third tier, but not in the first two.

**Bonded (p90)**
"Bondmate" is small-caps in the first tier, but not in the next two.

**Crack shot (p91)**
Should "steadying your aim" be emphasized? (See: Bonded's "Bondmate" as an example of a talent creating an emphasized keyword)

**Drone Commander (p93)**
Should the first tier say "DRONES" (small-caps emphasis), as in tier 2/tier 3, rather than "systems with the drone tag" (no emphasis)?

**"[SIZE] [RANGED/MELEE]" talents**
Several talents work on weapons of a specific size and either melee or ranged.
For the Duelist talent (p93) the emphasis pattern is "MAIN MELEE weapon". 
For the Executioner talent (p94) the emphasis pattern is "HEAVY or SUPERHEAVY melee weapon". 
Gunslinger (p95) is "AUXILIARY ranged"
Heavy Gunner (p97) is "HEAVY ranged"
Hunter (p97) is "AUXILIARY melee"
Walking Armory (p103) is "MAIN **ranged weapon**"

**Hacker (p96)**
"mount" and "dismount" are entirely in small caps, including the first letter. Elsewhere (e.g. Minotaur "Invert Cockpit" trait), these are written in first-letter-big, other-letters-small caps.

**Skirmisher (p100)**
"Reaction" in the third tier isn't bolded, but is bolded elsewhere, including in this talent.

**Walking Armory (p103)**
In the second tier, "ammo case" has the initial letters in small caps. In the third tier, it's "Ammo Case", with the initial letters in large caps.

**Comment by Jay-Iles** [comment]
Fixed.
