### ISSUE TITLE
[Typo] December Release: Vanguard Overwatch "start of turn"

### ISSUE THREAD

**Issue by jpbrodsky** [AshleyMoni/Lancer-Community-Edition#762]
### The Problem:
Vanguard talent, Semper Vigilo tier says:
"You may attack with OVERWATCH using CQB weapons when hostile characters enter, leave, or exit spaces within your THREAT, no matter whether they started their **turn** there."

Overwatch does not require the target to have started their _turn_ inside your threat. It requires them to have started their _move_ there (per the overwatch rules on p73).

### The Solution:
"You may attack with OVERWATCH using CQB weapons when hostile characters enter, leave, or exit spaces within your THREAT, no matter whether they started their **move** there."

### The Location:
Vanguard talent, Semper Vigilo tier (p103).

**Comment by Jay-Iles** [comment]
Fixed.
