### ISSUE TITLE
[Typo] December Release: Engaged status missing "I[f]"

### ISSUE THREAD

**Issue by jpbrodsky** [AshleyMoni/Lancer-Community-Edition#763]
**The Problem:**
In the summary of statuses, for the Engaged status:
ENGAGED
"f a character moves adjacent to a hostile character..."

**The Solution:**
"**I**f a character moves adjacent to a hostile character..."

**The Location:**
p77, under "Engaged"

**Comment by Jay-Iles** [comment]
Fixed.
