### ISSUE TITLE
[Typo] December release: Mourning Cloak's Hunter trait "other"

### ISSUE THREAD

**Issue by jpbrodsky** [AshleyMoni/Lancer-Community-Edition#764]
### The Problem:
The Mourning Cloak's Hunter trait says:
"1/round, the Mourning Cloak may deal +1d6 bonus damage on hit with a melee attack if its
target has no **other** adjacent characters, or if the Mourning Cloak is the only character adjacent to the target."

I am reading this text as saying:
Bonus damage if either:
1. The target has no adjacent characters **other** than the MC.
2. The MC is the only character adjacent to the target.

Those sound like the same thing.

### The Solution:
"1/round, the Mourning Cloak may deal +1d6 bonus damage on hit with a melee attack if its
target has no adjacent characters, or if the Mourning Cloak is the only character adjacent to the target."

Omitting "other" makes the meaning more clear: this trait triggers if there are either:
1. Zero adjacent characters
2. One adjacent character, the MC

### The Location:
Mourning Cloak Hunter trait, page 180

**Comment by Jay-Iles** [comment]
Fixed.
