### ISSUE TITLE
[Typo] NPCs in Mech Combat "quick actions or full action"

### ISSUE THREAD

**Issue by Eranziel** [AshleyMoni/Lancer-Community-Edition#765]
**The Problem:**
In the "NPCs in Mech Combat" section, the sentence "Just like PCs, NPCs each get one turn per round, and on that turn can move and take two quick actions one full action" seems to be missing an "or".

**The Solution:**
"Just like PCs, NPCs each get one turn per round, and on that turn can move and take two quick actions or one full action"

**The Location:**
Page 280, top of right column.

**Comment by Jay-Iles** [comment]
Fixed.
