### ISSUE TITLE
[Typo] December Release: Movement and Reactions Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#772]
**The Problem:**
The section on Movement and Reactions currently reads "Starting movement within RANGE 1–3 of another character can trigger reactions, like OVERWATCH." While in many cases correct given that most mechs do not have weapons with Threat higher than 3, the way this sentence is phrased suggests that it's specifically starting movement within a range band of 1-3 which triggers reactions rather than starting movement within an enemy's Threat range specifically.

**The Solution:**
For clarity's sake and to avoid confusion, it might be more intuitive to phrase it as "Starting movement within Threat another character, typically RANGE 1-3, can trigger reactions, like OVERWATCH." or perhaps "Starting movement while close to another character, typically RANGE 1-3, can trigger reactions, like OVERWATCH."

**The Location:**
Page 62

**Comment by Jay-Iles** [comment]
Fixed.
