### ISSUE TITLE
[Typo] Zheng Total Strength Suit III

### ISSUE THREAD

**Issue by squallevoker** [AshleyMoni/Lancer-Community-Edition#773]
**The Problem:**
Currently the rules text reads:
"A a full action, you can end a grapple to knock the character you’re grappling back 5 spaces in
any direction and knock it prone. ..."

**The Solution:**
Should read:
"As a full action, you can end a grapple to knock the character you’re grappling back 5 spaces in
any direction and knock it prone. ..."

**The Location:**
Page 4 of the .pdf file

**Comment by melodycwatson** [comment]
Noted and fixed.
