### ISSUE TITLE
[RAI] December Release: Attack/Attack roll definitions

### ISSUE THREAD

**Issue by Thac0nius** [AshleyMoni/Lancer-Community-Edition#774]
**The Problem:**
The terms attack and attack roll are constantly referred to but don't have an easy to reference definition. A definition can be inferred by reading attacks (p64), but a definition under combat terminology could be helpful.  

**The Solution:**
Adding a definition of attack and attack roll under combat terminology 

**The Location:**
Attacks (p64) and combat terminology (p78-79)

**Comment by Jay-Iles** [comment]
Now defines 'attack roll' on page 64.
