### ISSUE TITLE
[RAI] December Release: Diluvian Arc Reaction Clarification

### ISSUE THREAD

**Issue by Thac0nius** [AshleyMoni/Lancer-Community-Edition#775]
**The Problem:**
Diluvian arc reads "each time you or an adjacent allied character are targeted by a ranged attack..." and later "the attack automatically misses". As written when used on an AoE attack, on a roll of 4+ the attack would miss all targets including those not adjacent to Noah. 

**The Solution:**
Clarify interaction with area and multi-target attacks and whether the reaction's effect is per attack roll, indeed per attack as written, or something else. 

**The Location:**
p 245

**Comment by Jay-Iles** [comment]
Now states: "Each time you or an allied adjacent character are targeted by a ranged attack, you may take 1 heat as a reaction and roll 1d6 before the attacker rolls: on 4+, you take an additional 1 heat and the attack automatically misses you and any allies adjacent to you. This effect does not stack with Invisible."
