### ISSUE TITLE
[Typo] December Release: Bonus Damage Effects Sans "On Hit"

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#777]
**The Problem:**
Most sources of Bonus Damage specify "on hit" to make it clear that the Bonus Damage is not applied on a miss, even with Reliable weapons. However, the following sources do not include this caveat:
Tokugawa's Limit Break trait
Gunslinger III's I Kill With My Heart talent (this also grants the attack AP, which should apply on either a hit or miss, adding an on hit clause here would need to be done carefully)
Lucifer-Class NHP's Lucifer Protocol

**The Solution:**
In all likelihood, these effects should specify "on hit" to avoid nonsense like tokugawa assault cannons that deal 6 damage each on a miss or people getting +2d6 on a miss with a gms pistol.

Alternatively, text could be added specifically to the bonus damage rules specifying that bonus damage is only done on hit unless the source specifies otherwise.
Even if the latter is done, it's still probably good to patch these effects for consistent wording with other effects.

**The Location:**
Limit Break on pg. 250
Lucifer Protocol on pg. 253
Gunslinger on pg. 95

**Comment by Jay-Iles** [comment]
Added the 'on hit' rider to these three.
