### ISSUE TITLE
[RAI] December Release: Heavy Gunner II, Hammerbeat, and AoE Weapons

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#778]
**The Problem:**
In pr2, Hammerbeat was written in a manner so that you only Immobilize the target you selected for Covering Fire if you manage to hit them with the granted attack, even if you manage to hit a different target as well with the attack, such as with a AoE weapon.

However, the current wording only states that "If you successfully hit with the attack granted by
COVERING FIRE, your target is IMMOBILIZED until the end of their next turn." suggesting that anything you hit with an attack granted via Covering Fire will Immobilize the target (of that attack.)

**The Solution:**
Check with Tom to see if this is an intentional buff. If not, clarify that you only immobilize your selected Covering Fire target.

**The Location:**
Heavy Gunner, pg. 97

**Comment by Jay-Iles** [comment]
Now states: "If you successfully hit your Covering Fire target with the attack reaction granted by that talent, your target is Immobilized until the end of their next turn."
