### ISSUE TITLE
[Typo] December Release: Text is Behind Background Image, Page 347

### ISSUE THREAD

**Issue by randbrittain** [AshleyMoni/Lancer-Community-Edition#779]
**The Problem:**
On page 347 of the PDF, the text that's directly in front of the background logo is fuzzy and weird. I think the text layer is behind the image layer?

**The Solution:**
I'm assuming you can fix it by moving the textbox forward or the image backward?

**The Location:**
Page 347 of the PDF. Here are some pictures of the problem!

https://www.dropbox.com/s/7ni21p4d6cifn18/screenshot%202019-12-31%2018.14.41.png?dl=0
https://www.dropbox.com/s/h8mqotdv7qwmchh/screenshot%202019-12-31%2018.16.56.png?dl=0

**Comment by Jay-Iles** [comment]
Fixed (and throughout this chapter).
