### ISSUE TITLE
[RAI] December Release: High Gravity Rules Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#780]
**The Problem:**
The environmental rules for High Gravity state "Mechs cannot Boost and are Immobilized instead whenever they would be Slowed." This presents an odd interaction with Prone. While Prone mechs become Slowed, and so when high gravity rules apply Prone mechs would become Immobilized. Except when Prone, you cannot stand if you're also Immobilized. So a mech that gets knocked Prone in a high gravity environment, by rules as written, cannot stand back up.

**The Solution:**
Some sort of rules adjustment or additional clause here may be useful lest GMs unintentionally find themselves caught short by an unforeseen rules interaction. Either a clause specifying that Prone mechs can still stand normally in this instance, or perhaps some sort of associated Hull check to stand from Prone under these conditions. Tom may have his own ideas on the matter.

**The Location:**
Page 279

**Comment by Jay-Iles** [comment]
Now reads: "Mechs cannot Boost and are Immobilized instead whenever they would be Slowed. Prone mechs can stand even when Immobilized by this gravity, but must pass a Hull check to do so."
