### ISSUE TITLE
[RAI] December Release: Extreme Sun Rules Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#781]
**The Problem:**
The rules for the Extreme Sun environmental condition currently state "Characters take 1d6 heat whenever they are aren’t in shade at the end of **a** turn." As written, this suggests that this heat occurs during the end of ANY turn a mech remains exposed to the sun as opposed to only their own turn. Given the number of characters that can be involved in a fight, this suggests a mech exposed to the elements could take numerous d6's of heat before their turn rolls back around.

**The Solution:**
Check with Tom to see if this should be "at the end of **their** turn instead.

**The Location:**
Page 278

**Comment by Jay-Iles** [comment]
Now there's a proviso that each character may only take the heat damage once per round, but the trigger may still fire at the end of any turn.
