### ISSUE TITLE
[RAI] December Release: Armor-Lock Plating Clarification

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#782]
**The Problem:**
The current formatting of the Nelson's Armor-Lock Plating appears to not give you a choice to use its benefits or not (and thus forcing you taking it's 2 heat cost) when you Brace, as it merely states that "when you brace, you gain the following benefits..."

**The Solution:**
Check with Tom to see if it is intentional that you must take 2 heat and gain the benefits when you Brace. If it is not, clarify that you may choose whether or not to take the system's Heat cost when you Brace in order to gain those benefits.

**The Location:**
pg. 142

**Comment by KaiTave** [comment]
Amended by Jay
