### ISSUE TITLE
[Typo] December Release: Hornet Lock/Hold Javelin Lacks Range Icon

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#783]
**The Problem:**
The Hornet NPC's Lock/Hold Javelin currently reads "The Hornet fires a javelin at a character **within 5** and line of sight."

**The Solution:**
The icon for "range" should be included prior to the numerical value in that sentence.

**The Location:**
Page 303

**Comment by Jay-Iles** [comment]
Fixed.
