### ISSUE TITLE
[Typo] December Release: Priest Fortress Trait Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#784]
**The Problem:**
The Priest NPC's Fortress Trait currently reads "Hardened Target gives +3 Accuracy on SYSTEMS saves and deals +3 Difficulty on tech attacks, instead of +1." 

There are two things to note here. One is that the "+3" and "-3" values are not bolded as they generally are in other abilities and systems. The other thing is that while the intent here is clear, if consistency with other iterations of the Fortress trait, such as the Operator's, is desired, then perhaps the wording could be adjusted as well (though that may be up to the editor's discretion).

**The Solution:**
The appropriate numerical values should be bolded. If wording consistency between identical traits is desired, my suggestion for the Priest's Fortress trait would be "The Priest gains +3 Accuracy on SYSTEMS saves, and tech attacks against them receive +3 Difficulty. This trait replaces Hardened Target."

**The Location:**
Page 307

**Comment by Jay-Iles** [comment]
Bolded the +3 and -3. Keeping the trait to two lines is more important here than identical wording, so the wording won't change.
