### ISSUE TITLE
[Typo] December Release: Pyro Firebreak Shield Bolding

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#785]
**The Problem:**
The Pyro NPC's Firebreak Shield reads "it misses on a 4+ on 1d6." Neither numerical value in this sentence is bolded.

**The Solution:**
Both "4+" and "1d6" should likely be bolded for stylistic consistency.

**The Location:**
Page 308

**Comment by Jay-Iles** [comment]
Fixed.
