### ISSUE TITLE
[RAI] December Release: Sekhmet, Handing Over Control, and Talents

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#787]
**The Problem:**
The Sekhmet Protocol has been recently changed to specify that "you give control of your mech to your NHP," which would appear to run into the usual rules for AI that restrict them from benefiting from Talents unless you have Technophile III. 

**The Solution:**
Check with Tom to see if it is intended that taking the Sekhmet Protocol while inside your mech turns off your Talents. Either way, it may be nice to provide clarification as to whether your Talents work or not.

**The Location:**
pg. 131 Sekhmet Class NHP, Sekhmet Protocol

**Comment by KaiTave** [comment]
I'm pretty sure Tom has specified in the past that activating Sekhmet does not lock you out of talent use or it would be a pretty substantial downgrade in many cases.

**Comment by KaiTave** [comment]
Yep, found it:

"Tom 10/05/2019
sekhmet can use your talents"

100% confirmed

**Comment by Jay-Iles** [comment]
Added a line that 'It may benefit from your talents'.
