### ISSUE TITLE
[Typo] December Release: "Unon" typo in "THE BUREAUCRACY" diagram

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#788]
**The Problem:**
"UBO/NTM: **UNON** BUREAU OF ORBITAL AND NON-TERRESTRIAL MANAGEMENT" is displayed in the diagram

**The Solution:**
"UBO/NTM: **UNION** BUREAU OF ORBITAL AND NON-TERRESTRIAL MANAGEMENT" should be used instead

**The Location:**
Page 351

**Comment by Jay-Iles** [comment]
Fixed.
