### ISSUE TITLE
[Typo] December Release: Missing word in sentence describing Union Economic Bureau

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#789]
**The Problem:**
"The UEB’s increasing consolidation of power is a point of friction for CentComm; as ThirdComm’s rule has grown more assured over the centuries, and the first and second waves of post-revolution representatives have been replaced by new members, **newer members have pushed to liberalize certain of Union’s components.**" It seems there's a word missing after "certain".

**The Solution:**
Not entirely sure what the word should be; "parts" seems a bit redundant since "components" is in the same sentence. "Policies"?? This will be dependent on authorial intent.

**The Location:**
Page 354

**Comment by Jay-Iles** [comment]
Replaced 'certain' with 'some'.
