### ISSUE TITLE
[Typo] December Release: Napoleon Core Active Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#793]
**The Problem:**
The Napoleon's core active states "can only use systems with the SHIELD tag – any others immediately deactivate" which has prompted some confusion as to how this interacts with systems that are largely passive in nature such as Personalizations or Synthetic Muscle Netting which do not need to be manually activated.

**The Solution:**
Per Tom, such passive systems are not, and should not be, affected by this core ability, it's only meant to apply to systems which require manual activation of some sort such as Javelin Rockets. To clarify this, I would suggest adding a parenthetical to this clause of the core ability reading something along the lines of "(systems which do not require activation are unaffected)"

**The Location:**
Page 238

**Comment by Jay-Iles** [comment]
Fixed.
