### ISSUE TITLE
[Typo] [January Release] Neurolink Targeting does not list mechanical effect.

### ISSUE THREAD

**Issue by Conspiratiorist** [AshleyMoni/Lancer-Community-Edition#796]
**The Problem:**
SSC core bonus "Neurolink Targeting" doesn't list a mechanical effect.

**The Solution:**
Shift formatting to add space to list the mechanical effect.

**The Location:**
p158, bottom right corner.

**Comment by Jay-Iles** [comment]
Fixed.
