### ISSUE TITLE
[Typo/Errata] January Release: Overheating Table Meltdown Result Round 2 (Free vs Full)

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#797]
**The Problem:**
In this update, the overheating table's "you are going to meltdown in a couple of turns, but you can try this thing to fix it" was corrected to redo the Engineering check instead of rerolling on the table. However, it was also changed to a Free Action instead of a Full Action.

**The Solution:**
It seems that this was a mistake, and it should be a Full Action, see below.

**The Location:**
Overheating Table, pg 81

**The Ratification:**

![image](https://user-images.githubusercontent.com/49732719/72005866-89c3b900-321c-11ea-9393-eefc9c4f064d.png)

**Comment by Jay-Iles** [comment]
Fixed.
