### ISSUE TITLE
[Typo] January Release: Thermal Lance uses word Heat instead of symbol

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#798]
**The Problem:**
The GMS Thermal Lance has 2Heat(Self) in it's tag line instead of using the symbol for Heat.

**The Solution:**
Replace the word heat with the symbol for heat.

**The Location:**
pg. 119, GMS weapons table, Thermal Lance

**Comment by Jay-Iles** [comment]
Fixed.
