### ISSUE TITLE
[Typo] January Release: Backer Characters Index Errors

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#799]
**The Problem:**
The Backer Characters/Factions table at the end of the book seems to have a few inaccurate page references. For example, the first row references the Ace on page 288, but that is inaccurate as the Ace npc is on page 286. Not every entry is inaccurate, but many, especially the npc class entries, are off by a few pages.

**The Solution:**
The following is a list of the errors I've personally caught, but there may be others, and I might make mistakes, so it can't hurt to double check as well.

pg. 288 (Ace), actually page 286
pg. 289 (Aegis), actually page 287
pg. 290 (Archer), actually page 288
pg. 301 (Engineer), actually page 299
pg. 379 (re: Paracausal Studies) is correct
pg. 406 (HORUS Flashpoint) is correct
pg. 310 (Pyro), actually page 308
pg. 309 (Priest), actually page 307
pg. 295 (Berserker), actually page 293
pg. 293 (Barricade), actually page 291

At this point, I gave up on logging each of these, because it seems that most of the entries are correct, except for the npc classes which are all 2 off, and "Deep Field Discovery 486 (Support Archetype)" which I can't seem to find because the book isn't even 450 pages long. There may be other mistakes, but it primarily seems to be an issue on the part of the npc section. Someone else willing to look through the rest of the table might be willing to log everyone of these, but it really does seem to be a problem isolated in the npc section, and I am not being paid for this.

**The Location:**
Backer Characters, starting page 430.

**Comment by Jay-Iles** [comment]
Fixed.
