### ISSUE TITLE
[Typo] Centimane talent rank numbers

### ISSUE THREAD

**Issue by aritsune** [AshleyMoni/Lancer-Community-Edition#8]
**Problem:**
The Centimane talent rank numbers are out of order (II, I, III)

**Solution:**
Going off Tom's first peek of this talent on December 26th in the discord, the actual ranks are in the correct order as-is, only the numbers are flipped. _Expose Weakness_ is Rank I and _Hivemaster_ is Rank II.

**Location:**
Page 122

**Comment by KaiTave** [comment]
This seems to have been resolved as of 1.8.5
