### ISSUE TITLE
[TAI] Vlad lore text needs to be updated

### ISSUE THREAD

**Issue by AshleyMoni** [AshleyMoni/Lancer-Community-Edition#80]
![image](https://user-images.githubusercontent.com/6186092/51269372-52675700-1990-11e9-8757-8ed338bb867d.png)
![image](https://user-images.githubusercontent.com/6186092/51269384-572c0b00-1990-11e9-8ad4-a08be5efe97c.png)

**Comment by KaiTave** [comment]
This has been done as of 1.8.5
