### ISSUE TITLE
[Typo] January Release: Ace NPC stat block lurking under other pages

### ISSUE THREAD

**Issue by AN508** [AshleyMoni/Lancer-Community-Edition#800]
**The Problem:**
The stat block for the Ace NPC secretly lurks under pages 300, 301, 310 and 315 (possibly others)! It isn't actually visible and only appears in PDF search results, but who knows if this might have some weird effect later.

**The Solution:**
The Ace stat block should not be lurking anywhere near any page other than the Ace's.

**The Location:**
300, 301, 310, 315
![LANCER p315](https://user-images.githubusercontent.com/59668719/72017537-2cecf080-3266-11ea-9af0-7082052b2035.png)

**Comment by Jay-Iles** [comment]
Fixed.
