### ISSUE TITLE
[Typo] January Release: formatting - various errors with bold font

### ISSUE THREAD

**Issue by Conspiratiorist** [AshleyMoni/Lancer-Community-Edition#802]
**The Problem:**
Various instances of text that isn't using the proper font type.

**The Solution:**
Switch to the proper font type.

**The Location:**
Page 93, Drone Commander, Shepherd, third line, "4 spaces" should be bolded
Page 100, Siege Specialist, Impact, third line, "1" should be bolded
Page 309, Rainmaker NPC, Tier 2, E-Defense, "10" should *not* be bolded

**Comment by Jay-Iles** [comment]
Fixed.
