### ISSUE TITLE
[Typo] Uncle Class CompCon missing word.

### ISSUE THREAD

**Issue by Eldraen** [AshleyMoni/Lancer-Community-Edition#804]
**The Problem:**
"Compcon isn't a full NHP, so cannot enter cascade"

**The Solution:**
"Compcon isn't a full NHP, so **it** cannot enter cascade" or "Compcon isn't a full NHP, **and** so cannot enter cascade"

**The Location:**
Page 147

**Comment by KaiTave** [comment]
Technically this is grammatically correct.
