### ISSUE TITLE
[Typo] January Release: "cascade" formatting inconsistent

### ISSUE THREAD

**Issue by Conspiratiorist** [AshleyMoni/Lancer-Community-Edition#806]
**The Problem:**
"cascade" as part of mechanical descriptions uses bold font inconsistently through the document

**The Solution:**
The following instances should be using bold font:
p. 103 Enlightenment "AIs installed in your mech cannot enter *cascade*"
p. 147 UNCLE "UNCLE isn't a full NHP, so cannot enter *cascade*"
p. 191 Lesson of Shaping "systems or equipment enter *cascade*"
p. 332 NHP Co-Pilot "NHP can enter *cascade*, using the same rules as PC AIs."

**Comment by Jay-Iles** [comment]
Fixed.
