### ISSUE TITLE
[Typo] Text for Corrective is Wrong Color

### ISSUE THREAD

**Issue by ninjaxenomorph** [AshleyMoni/Lancer-Community-Edition#807]
**The Problem:**
Some of the text under Corrective is black rather than white, making it difficult to read

**The Solution:**
The text “Gear, Limited 1, Full Action” should be the same color as the heading, currently only Limited is white

**The Location:**
Page 112, top left, under Corrective

**Comment by Jay-Iles** [comment]
Fixed.
