### ISSUE TITLE
[Errata/Typo] Invade Tag Missing

### ISSUE THREAD

**Issue by Eranziel** [AshleyMoni/Lancer-Community-Edition#809]
**The Problem:**
The INVADE tag has no entry in the Gear Tags list.

**The Solution:**
INVADE should be added to the tag list. It is mentioned in the Invade action on page 70.

**The Location:**
Invade description on page 70.
Gear Tag list is on pages 105/106.

**The Ratification:**
I'm assuming this is simply an oversight.

**Comment by Jay-Iles** [comment]
Fixed.
