### ISSUE TITLE
[Errata] Barrage on Aux/Aux or Flex Mount

### ISSUE THREAD

**Issue by Ffzdf** [AshleyMoni/Lancer-Community-Edition#81]
**The Problem:**
Nothing prohibits a player from choosing two Aux weapons on the same mount to fire in a Barrage, thus each weapon fires and causes the other to fire an additional time.

**The Solution:**
This interaction is not intended. Add the following text (**bolded**): When you attack with a weapon, you can also attack with another auxiliary weapon in the same mount **if you aren't already attacking with it this turn.**

**The Location:**
Barrage rules on pg. 95

**The Ratification:**
Confirmed here: https://media.discordapp.net/attachments/531498621586374656/535190821973000215/Screenshot_20190116-141643.png?width=760&height=1352

**Comment by Techhead0** [comment]
Saying "this action" would be better than "this turn" due to free/bonus actions, but "if you aren't already attacking with it" is overall awkward as an addition. Might just be easier to specify "If you attack with two weapons they must be from separate mounts."

**Comment by Ffzdf** [comment]
Adding that stipulation to the Barrage rules, instead? But some people might get confused with how that interacts with Aux weapons.

**Comment by KaiTave** [comment]
Corrected in the prerelease.
