### ISSUE TITLE
[RAI] Is "Active" a tag?

### ISSUE THREAD

**Issue by Eranziel** [AshleyMoni/Lancer-Community-Edition#810]
**The Problem:**
All core powers have "Active (1CP)" in the tag line of their effect block. "Active" isn't in the gear tags list - should it be?

**The Solution:**
Add the "Active (1CP)" tag to the gear tags list, if it should be there.

**The Location:**
Gear tag list is on pages 105/106.

**Comment by Jay-Iles** [comment]
Fixed.
