### ISSUE TITLE
[Typo] NPC text overlapping bottom of page text/page number

### ISSUE THREAD

**Issue by AN508** [AshleyMoni/Lancer-Community-Edition#812]
**The Problem:**
The Engineer NPC's Arsenal trait partially overlaps the section text and maroon page number box.
![Annotation 2020-01-10 173312](https://user-images.githubusercontent.com/59668719/72169379-4bbac680-33cf-11ea-8ac1-209213528ae9.png)

The Seeder's Det Spike overlaps the section text. The Seeder's Lay Mines clip the maroon page number box.
![Annotation 2020-01-10 173012](https://user-images.githubusercontent.com/59668719/72169163-dea73100-33ce-11ea-963f-d4d7c03b71f0.png)

**The Solution:**
Move the Engineer's Mark trait back to the left column.

Clip the bottom left corner of the Lay Mines box. Fix the double line break between Grav Spike and Det Spike.

**The Location:**
299, 314

**Comment by Jay-Iles** [comment]
Fixed.
