### ISSUE TITLE
[Typo] January release: Personalisations text should not use the term "mod"

### ISSUE THREAD

**Issue by AN508** [AshleyMoni/Lancer-Community-Edition#813]
**The Problem:**
The text of the Personalisations GMS system uses the term "mod" to refer to the system (short for "modification" which it uses in the first paragraph). It is not a system with the Mod tag, so it should avoid using the term just for clarity's sake.

![Annotation 2020-01-10 180754](https://user-images.githubusercontent.com/59668719/72172081-925eef80-33d4-11ea-950b-b4b0d49527b0.png)

**The Solution:**
The word "mod" should be replaced with the word "modification."

**The Location:**
121

**Comment by KaiTave** [comment]
I would say the term "system" would be a better replacement than modification, if a replacement is warranted.

**Comment by Jay-Iles** [comment]
Now it's modification - 'system' is a rules term too.
