### ISSUE TITLE
[Typo] January Release: Couple typos in last paragraph of Homunculi section

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#814]
**The Problem:**
"**o** ensure the most accurate representation possible, subjects with foreknowledge of their memorialization or possible memorialization will often begin recording a profile on an extant **homunculi** prior to their death."

**The Solution:**
"**To** ensure the most accurate representation possible, subjects with foreknowledge of their memorialization or possible memorialization will often begin recording a profile on an extant **homunculus** prior to their death."

**The Location:**
Page 381

**Comment by Jay-Iles** [comment]
Fixed.
