### ISSUE TITLE
[RAI] January Release: Flight and Falling due to Stress or Structure

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#815]
**The Problem:**
Currently, the caveat for Flight that causes you to make an Agility Save when you take Stress or Structure damage causes you to make a Save, rather than a Check.

**The Solution:**
This should probably be a Check, as things can happen such as taking damage from Dangerous Terrain or other sources that don't have a Save Target, or you might cause Stress to yourself via your own Heat generating systems.

**The Location:**
Pg. 63

**Comment by Jay-Iles** [comment]
Fixed - now a check.
