### ISSUE TITLE
[Errata] January Release: GMS Type 1 Flight and SSC Core Bonus Flight Reminder

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#816]
**The Problem:**
Earlier, Jay mentioned that these two sources of flight were being tweaking to encompass all movement, but this change did not seem to go through.

**The Solution:**
This issue serves as a reminder to check if this was intentionally not pushed through or if it merely slipped through the cracks.

**The Location:**
GMS flight on page 121
SSC flight core bonus on page 158

**The Ratification:**

![image](https://user-images.githubusercontent.com/49732719/72191549-81ac7a80-33d0-11ea-8974-e2bc5c62d4a7.png)

**Comment by Jay-Iles** [comment]
Fixed.
