### ISSUE TITLE
[Typo] Extra opening parenthesis next to Reload under Pilot Actions in the Quick Combat Reference

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#818]
**The Problem:**
Under "Pilot Actions" in the Quick Combat Reference, the Reload action is listed as follows (emphasis mine):

> RELOAD **((quick)**: Reload a pilot weapon with the LOADING tag.

There's an extra opening parenthesis before "quick".

**The Solution:**
The extra opening parenthesis should be removed:

> RELOAD **(quick)**: Reload a pilot weapon with the LOADING tag.

**The Location:**
Bottom right of the Quick Combat Reference on p. 76, under "Pilot Actions".

**Comment by Jay-Iles** [comment]
Fixed.
