### ISSUE TITLE
[RAI] January Release: Infiltrator Rank II (Ambush) and multi-target attacks

### ISSUE THREAD

**Issue by Thac0nius** [AshleyMoni/Lancer-Community-Edition#819]
**The Problem:**
Ambush reads "when you start your turn hidden, the first attack of any type that you make sends your target reeling on a hit". The use of "attack" as opposed to attack roll implies that effect would apply to all targets of a multi-target attack, but the use of singular "target" makes the intent seem that the effect is single target.

**The Solution:**
Clarify the interaction with multi-target effects either by changing "target" to "targets" - or target(s) -  or use "attack roll" instead of "attack" depending on intended function. 

**The Location:**
p98

**Comment by Jay-Iles** [comment]
Changed to 'attack roll'.
