### ISSUE TITLE
[RAI] January Release: Cataphract Trample Clarification

### ISSUE THREAD

**Issue by Eldraen** [AshleyMoni/Lancer-Community-Edition#820]
**The Problem:**
Currently, the Cataphract can do 16 "unavoidable damage" by moving in and out of size 1 mechs at tier 1, and up to 32 damage at tier 3 because its trait isn't restricted in any way.

**The Solution:**
If this is indeed an issue, it could be fixed by adding some form of limit on it.

**The Location:**
NPC templates, page 297, Cataphract.

**Comment by KaiTave** [comment]
To clarify, the Cataphract's Trample trait reads "The Cataphract ignores engagement and can pass
through – but not stop in – spaces occupied by other characters, dealing 2/3/4 kinetic damage to those characters." There's no listed per round or per turn restriction on how many times this damage can be triggered on any given character, though it's also not entirely clear if Lancer even considers moving back and forth over a single space multiple times to be a valid type of move or not.

**Comment by KaiTave** [comment]
"Tom Today at 4:56 PM
no a cataphract can't infinitely trample someone
if your gm does that they are being a fucking dick
the language should probably be clarified but we have turned files into the printer at this point so"

**Comment by Jay-Iles** [comment]
Put a 1/turn restriction on the damage.
