### ISSUE TITLE
[Typo] January Release: Ace NPC Evasive Maneuvers Holdover

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#821]
**The Problem:**
"Aces are very fast and reactive strikers that can use **EVASIVE MANEUVERS** to mitigate dangerous or high-damage attacks."

**The Solution:**
"Aces are very fast and reactive strikers that can use **BARREL ROLL** to mitigate dangerous or high-damage attacks."

**The Location:**
Page 286

**Comment by Jay-Iles** [comment]
Fixed.
