### ISSUE TITLE
[RAI] January Release: Hunter 1 Movement Target Clarification

### ISSUE THREAD

**Issue by tortol44** [AshleyMoni/Lancer-Community-Edition#824]
**The Problem:**
Hunter 1's Lunge movement specifies "directly towards a character." This seems unclear as to whether the character should be the target of the attack or merely any character.

**The Solution:**
This should probably be more specific about who you can move towards, or be unrestricted.

**The Location:**
Pg 97

**Comment by Jay-Iles** [comment]
Now it's 'directly towards a targeted character'.
