### ISSUE TITLE
[Typo] Missing word in description of Hive NPC's Razor Swarms

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#825]
**The Problem:**
The third sentence of the Razor Swarms base system says (emphasis mine):

> **Hostile characters start their turn** at least partially within the area or move into it for the first time in a round take 2/4/6 [Burn].

The main verb of the sentence is "take", and "start their turn at least partially within the area or move into it for the first time in a round" is actually a descriptor explaining _which_ hostile characters take Burn. There's a missing word before that phrase, causing the sentence to be grammatically incorrect.

**The Solution:**
It should read (emphasis mine):

> **Hostile characters that start their turn** at least partially within the area or move into it for the first time in a round take 2/4/6 [Burn].

**The Location:**
Razor Swarms base system for the Hive NPC, in the bottom left of p. 302 (in the GM's Toolkit chapter of the premium PDF).

**Comment by Jay-Iles** [comment]
Fixed.
