### ISSUE TITLE
[Typo] January Release: Bastion NPC Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#826]
**The Problem:**
"Use **SHIELD WALL** to defend against distant enemies, like artillery and snipers."

**The Solution:**
This should read "Use **FRIENDLY INTERDICTION** to defend against distant enemies, like artillery and snipers."

**The Location:**
Page 292

**Comment by Jay-Iles** [comment]
Fixed.
