### ISSUE TITLE
[Typo] SSC Atlas - "Multi-gear manuever system" for license I

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#827]
**The Problem:**
In the systems list above the frame stats on p. 2, license I is listed as:

> I. **Multi-gear manuever system**, Kraul Rifle

Aside from the misspelling of "maneuver", this system is also missing capitalization. In addition, this section is hyphenated, but the actual system description on p. 3 (below the frame stats) is missing the hyphen:

> **Multi Gear** Maneuver System

**The Solution:**
License I in the systems list should read:

> I. **Multi-Gear Maneuver System**, Kraul Rifle

And the heading above the system description should read:

> **Multi-Gear** Maneuver System

**The Location:**
12/22 release of the [SSC Atlas](https://massif-press.itch.io/the-atlas), in the systems list (p. 2) and the heading above the "Multi Gear Maneuver System" system (p. 3).

**Comment by melodycwatson** [comment]
Noted and fixed. :)
