### ISSUE TITLE
[Typo] SSC Atlas - Ricochet Blades is missing from systems list for license II

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#828]
**The Problem:**
The systems list above the frame stats on p. 2 lists the following systems at each license rank:

> I. Multi-gear manuever system, Kraul Rifle
> II. **ATLAS Frame, Jäger Kunst I**
> III. Terashima Blade, Jäger Kunst II

However, in the descriptions of the systems on the following pages, there's another system that doesn't appear in the systems list quote above, located between Jäger Kunst I and Jäger Kunst II on p. 4 (for some reason, Terashima Blade's description doesn't appear in the listed order, but rather at the end after Jäger Kunst II):

> Ricochet **blades**

It's not clear why it's lowercase here.

(I don't think the full description needs quoting.)

**The Solution:**
All mechs seem to unlock 2 systems at each license rank, not counting the frame. The current systems list only lists one system other than the frame at license II, so I'm guessing Ricochet Blades is intended as the other one. Thus, the license II row of the systems list should read:

> II. **ATLAS Frame, Jäger Kunst I, Ricochet Blades**

In addition, the heading above the system description should read:

> Ricochet **Blades**

**The Location:**
12/22 release of the [SSC Atlas](https://massif-press.itch.io/the-atlas), in the systems list (p. 2) and the heading above the "Ricochet blades" system (p. 4).

**Comment by lionheart11899** [comment]
This is also prevalent on the new LONG-RIM pdf, now on page 43. It also does not show the Ricochet blades.

**Comment by melodycwatson** [comment]
Noted and fixed. :)
