### ISSUE TITLE
[Typo] January Release: Scout Optional Systems Typo

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#830]
**The Problem:**
The Scout NPC is missing the header which should designate which of it's systems are optional.

**The Solution:**
Based on the december version, this header should be between Cloaking Field and System Flayer: Essentially, there should be an optional system header at the top of the right column.

**The Location:**
pg. 313

**Comment by Jay-Iles** [comment]
Fixed.
