### ISSUE TITLE
[Typo] January Release: HyperDense Armor Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#831]
**The Problem:**
HyperDense Armor reads "You gain RESISTANCE to all damage and heat from attacks that originate
beyond range 3; however, you become SLOWED and deal half damage and half heat to characters beyond range 3."

**The Solution:**
For stylistic consistency with other similar effects, this should read ""You gain RESISTANCE to all damage, heat, **and burn** from attacks that originate beyond range 3; however, you become SLOWED and deal half damage, heat, **and burn** to characters beyond range 3."

**The Location:**
Page 151

**Comment by Jay-Iles** [comment]
Fixed.
