### ISSUE TITLE
[Typo] January Release: AI Tag Typo

### ISSUE THREAD

**Issue by Eranziel** [AshleyMoni/Lancer-Community-Edition#834]
**The Problem:**
The AI tag contains the sentence, "A mech with the AI tag has an NHP or comp/con unit installed that can act __onsomewhat__ autonomously." (Emphasis mine.)

**The Solution:**
Probably change the emphasized word to "somewhat", I'm guessing the "on" is simply an incomplete deletion.

**The Location:**
AI tag on page 105.

**Comment by Jay-Iles** [comment]
Fixed.
