### ISSUE TITLE
[RAI] January Release: Nuclear Cavalier attack conditionals

### ISSUE THREAD

**Issue by Conspiratiorist** [AshleyMoni/Lancer-Community-Edition#835]
**The Problem:**
The current wording of NC1 and NC2 is such:

"The first attack roll you make on your turn while in the Danger Zone deals +2 Heat on a hit."
"The first ranged or melee attack roll you make on your turn while in the Danger Zone deals [...] on a hit."

For a natural language reading, the conditional taking precedence is ambiguous and could be considered to be Danger Zone status - the talents activate on the first attack roll you make once you've entered the Danger Zone during your turn. You can thus say Barrage with a weapon that generates Heat, pushing you into the DZ, and the subsequent attack roll will meet the Nuclear Cavalier conditions.

However, Tom has indicated that the conditional taking precedence is "the first attack roll of your turn", with Danger Zone status relegated to being a check on whether it'll activate the talents at all. In this case, the scenario above would not work, as the first attack roll wasn't made while in the DZ and subsequent attacks can't activate it.

**The Solution:**
Let it work like that, you coward! It's still only once per round, and rewards clever heat management!

But for the sake of clarity, this is a concise rewrite so they work as intended:

"If you're in the Danger Zone, the first attack roll you make on your turn deals +2 Heat on a hit."
"If you're in the Danger Zone, the first ranged or melee attack roll you make on your turn deals [...] on a hit."

Which is much closer to the Backer and December release wordings.

**The Location:**
Page 99, Aggressive Heat Bleed and Fusion Hemorrhage

**Comment by KaiTave** [comment]
![tom](https://user-images.githubusercontent.com/46460730/73128595-a97e0f80-3f86-11ea-9f3e-13e47d34b18b.jpg)

**Comment by Jay-Iles** [comment]
Added a sidebar after NC1 saying: 'If you enter the Danger Zone during your turn, this talent takes effect on your next attack'.
