### ISSUE TITLE
[RAI] January Release: Stormbringer's Torrent Stun Duration

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#836]
**The Problem:**
The stun effect of Stormbringer's Rank III, Torrent, doesn't list a duration for the stunned effect, just "they must succeed on an AGILITY save or take 2d6 Explosive Damage, become STUNNED, and be knocked PRONE".
**The Solution:**
Most likely it should be "until the end of their next turn" but check with Tom, yes.

**The Location:**
pg. 101, Torrent, under Stormbringer.

**Comment by Jay-Iles** [comment]
Fixed - now it lasts until the end of their next turn.
