### ISSUE TITLE
[Typo] Rainmaker's Hound Missiles says "round" instead of "around"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#837]
**The Problem:**
The Rainmaker NPC's optional Hound Missiles system says (emphasis mine):

> It moves directly, maneuvering **round** cover and terrain if needed.

While this is technically an alternative form of "around", it's quite rare in usage, and the PR2 version says it "maneuvers **around** cover and obstacles", so I suspect "round" is not intended here.

**The Solution:**
Replace "round" with "around":

> It moves directly, maneuvering **around** cover and terrain if needed.

**The Location:**
Rainmaker's Hound Missiles optional system, Lancer core book p. 309. This is true of all 3 backer release versions (Nov., Dec., and Jan.).

**Comment by Jay-Iles** [comment]
Fixed.
