### ISSUE TITLE
[Typo] Extraneous comma in IPS-N Caliban's fluff text

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#838]
**The Problem:**
In the 1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), the second paragraph of the fluff text begins:

> The Caliban is IPS-N’s solution to the Yemanova Problem, **or, the** Impact-Override Problem.

As written, I don't think there should be a comma after "or". I assume what you're going for is that "the Impact-Override Problem" is another name for the "the Yemanova Problem". However, I believe the comma is grammatically incorrect where it is.

**The Solution:**
There are a few ways to fix the first sentence of the second paragraph. One way is to simply remove the comma after "or":

> The Caliban is IPS-N’s solution to the Yemanova Problem, **or the** Impact-Override Problem.

However, if you're worried that this could be interpreted as referring to 2 different problems, removing the repeated "the" might also make it more clearly another name for the same problem:

> The Caliban is IPS-N’s solution to the Yemanova Problem, **or** Impact-Override Problem.

Finally, another option is to change the sentence to more directly state "also known as" instead of "or" (though this feels least elegant) and once again remove the comma after it:

> The Caliban is IPS-N’s solution to the Yemanova Problem, **also known as the** Impact-Override Problem.

**The Location:**
1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), p. 2, in the first sentence of the second paragraph.

**Comment by melodycwatson** [comment]
Noted and fixed.
