### ISSUE TITLE
[Typo] IPS-N Caliban's Traits section - minor typos

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#840]
**The Problem:**
In the 1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), the list of the frame's traits has a few minor typos.

First, the Wrecking Ball trait says:

> The Caliban counts as size 3 when inflicting **knock back** from any ranged or melee attack.

The phrase "knock back" should be a single word with no space; "knockback" is a weapon tag (defined on p. 105 of the core book), and is written as a single word.

Second, the Slam trait says:

> 1/round when the Caliban knocks a character into a wall, mech, or other obstruction that would cause it to stop moving, **it’s** target takes 2 kinetic damage and becomes impaired until the end of its next turn.

This refers to the mech's target; this word should be a possessive pronoun, not a contraction of "it is".

Finally, the Weak Computer trait is missing a period at the end:

> The Caliban takes +1 difficulty on all systems saves and **checks**

**The Solution:**
The Wrecking Ball trait should read:

> The Caliban counts as size 3 when inflicting **knockback** from any ranged or melee attack.

The Slam trait should say:

> 1/round when the Caliban knocks a character into a wall, mech, or other obstruction that would cause it to stop moving, **its** target takes 2 kinetic damage and becomes impaired until the end of its next turn.

And the Weak Computer trait should be written as:

> The Caliban takes +1 difficulty on all systems saves and **checks.**

**The Location:**
1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), p. 3, Traits section.

**Comment by melodycwatson** [comment]
Noted and fixed.
