### ISSUE TITLE
[Typo] IPS-N Caliban's HHS-155 CANNIBAL - fluff uses em dash where it should use a hyphen

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#841]
**The Problem:**
In the 1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), the fluff text for the HHS-155 CANNIBAL weapon starts:

> The IPS-N Heavy **Howitzer—Shotgun** is a large, breech-loaded, over-under cannon

This seems to use an em dash. However, the Caliban's passive core system, the HHS-075 “Flayer” Shotgun, hyphenates the word in its fluff text:

> The Heavy **Howitzer-Shotgun** is a compact, formalized version of the long-popular “Daisy Cutter” pattern **howitzer-shotgun** used by Trunk Security and other stellar marine security forces.

Presumably it's a mix between a howitzer and a shotgun; this pair of words should indeed be connected with a hyphen, not by an em dash (which has a number of uses, none of which is to connect two nouns to form a compound noun).

**The Solution:**
The first sentence of the fluff text for the CANNIBAL should begin as follows:

> The IPS-N Heavy **Howitzer-Shotgun** is a large, breech-loaded, over-under cannon

**The Location:**
1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), p. 6, under the HHS-155 CANNIBAL heading.

**Comment by melodycwatson** [comment]
Noted and fixed.
