### ISSUE TITLE
[Typo] IPS-N Caliban's HHS-155 CANNIBAL - "it’s damage" should be "its damage"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#842]
**The Problem:**
In the 1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), the second sentence of the description of the HHS-155 CANNIBAL says:

> Alternately, both barrels can be fired at once, causing the weapon to be fired with +1 additional difficulty and requiring a reload as normal, but increasing **it’s** damage and knockback to 3d6+4 kinetic and knockback 4 respectively.

This refers to the weapon's damage; this word should be a possessive pronoun, not a contraction of "it is".

**The Solution:**
The word "it's" should be replaced with "its":

> Alternately, both barrels can be fired at once, causing the weapon to be fired with +1 additional difficulty and requiring a reload as normal, but increasing **its** damage and knockback to 3d6+4 kinetic and knockback 4 respectively.

**The Location:**
1/27 release of the [IPS-N Caliban](https://massif-press.itch.io/the-caliban), p. 6, at the end of the first paragraph of the HHS-155 CANNIBAL's description.

**Comment by melodycwatson** [comment]
Noted and fixed.
