### ISSUE TITLE
[Typo] January release: EX Slipstream capitalisation

### ISSUE THREAD

**Issue by AN508** [AshleyMoni/Lancer-Community-Edition#843]
**The Problem:**
Fluff text for Mourning Cloak core system does not capitalise all instances of EX Slipstream:
![image](https://user-images.githubusercontent.com/59668719/73599078-c050d300-453f-11ea-8022-4cf7f206247b.png)

**The Solution:**
All instanced of "Ex" should be "EX."

**The Location:**
180, EX Slipstream Module

**Comment by Jay-Iles** [comment]
Fixed.
