### ISSUE TITLE
[Typo] January Release: Jericho Deployable Cover Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#846]
**The Problem:**
The Jericho Deployable Cover states "Sections of cover can be picked up again as a full action."

**The Solution:**
For clarity, given the known intent of the system, this should probably read "**Both** sections of cover can be picked up again as a full action."

**The Location:**
Page 120

**Comment by Jay-Iles** [comment]
Fixed.
