### ISSUE TITLE
[Typo] January Release: Mirage Dataveil Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#847]
**The Problem:**
The Mirage's Dataveil system reads "By default, the Mirage is INVISIBLE and can transfer this status to another character within line of sight as a quick action. When they do so, the Mirage ceases to be INVISIBLE, and only regains the status when they transfer it back as a quick action or transfer it to another character; otherwise, this effect lasts until the Mirage is destroyed."

**The Solution:**
To clarify the system's precise function, some slight wording adjustments may help. My suggestion is "By default, the Mirage is INVISIBLE and can transfer this status to another character within line of sight as a quick action. When they do so, the Mirage ceases to be INVISIBLE, **and as a quick action they may transfer it back to themselves or to another character;** otherwise, this effect lasts until the Mirage is destroyed."

**The Location:**
Page 304

**Comment by Jay-Iles** [comment]
Fixed.
