### ISSUE TITLE
[Typo] January Release: Gorgon Metastatic Paralysis Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#848]
**The Problem:**
"When an attack roll against the Gorgon lands on 1–2, it automatically misses and the attacker becomes STUNNED until the end of their next **tturn.**"

**The Solution:**
"When an attack roll against the Gorgon lands on 1–2, it automatically misses and the attacker becomes STUNNED until the end of their next **turn.**"

**The Location:**
Page 202

**Comment by Jay-Iles** [comment]
Fixed.
