### ISSUE TITLE
[Typo] January release: Grenade tag

### ISSUE THREAD

**Issue by Eranziel** [AshleyMoni/Lancer-Community-Edition#849]
**The Problem:**
The text for the Grenade tag repeats "line of sight" (emphasis mine):
GRENADE: As a quick action, this explosive or other device can be thrown to a space within **line of sight** and the specified RANGE and **line of sight**.

**The Solution:**
One "line of sight" should be removed. Probably the first one.

**The Location:**
Grenade tag on page 106.

**Comment by Jay-Iles** [comment]
Fixed.
