### ISSUE TITLE
[Typo] Two Different Ways of Referencing Sticky Bomb Launcher

### ISSUE THREAD

**Issue by extremeradical** [AshleyMoni/Lancer-Community-Edition#85]
**The Problem:**
Iskander's weapon is referred to as "Sticky Bomb Launcher" and "Sticky Bombs" in different parts of the text.

**The Solution:**
Sticky Bomb Launcher is more descriptive and correct for a launcher-type weapon.

**The Location:**
273, ("Sticky Bombs") 275 ("Sticky Bomb Launcher")

**Comment by KaiTave** [comment]
The Sticky Bomb Launcher no longer exists in the Iskander's kit in 1.8.5, rest in peace
