### ISSUE TITLE
[Typo] January Release: Solidcore Statblock Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#851]
**The Problem:**
The statblock for the Sherman's ZF4 Solidcore weapon is missing the left side bracket, and also appears to have been indented somewhat.

"Main Cannon, Ordnance
   4/charge][1d6/charge]"

**The Solution:**
The statblock should be amended to its proper formatting.

**The Location:**
Page 246

**Comment by Jay-Iles** [comment]
Fixed.
