### ISSUE TITLE
[Typo] IPS-N Caliban fluff text: extra "to"

### ISSUE THREAD

**Issue by Knockenburg** [AshleyMoni/Lancer-Community-Edition#852]
**The Problem:**
In the 1/27 release of the IPS-N Caliban, the second sentence of the 6th paragraph of the description of the HHS-155 CANNIBAL says:

> It was only made small so it could **to** fit through most ship doors and bulkheads with minimal problems, crawl up the spinal corridors of ships, and speed up it’s average job completion rate by five minutes.

**The Solution:**
The extra "to" should be removed:

>  It was only made small so it could fit through most ship doors and bulkheads with minimal problems, crawl up the spinal corridors of ships, and speed up it’s average job completion rate by five minutes.

Alternatively, replace "so it could" with "in order":

 

> It was only made small in order to fit through most ship doors and bulkheads with minimal problems, crawl up the spinal corridors of ships, and speed up it’s average job completion rate by five minutes.

**The Location:**
1/27 release of the IPS-N Caliban, p. 2, at the end of the 6th paragraph of the HHS-155 CANNIBAL's description.

**Comment by melodycwatson** [comment]
Noted and fixed. :)
