### ISSUE TITLE
[RAI] Gauntlet Sitrep Victory Condition

### ISSUE THREAD

**Issue by CaptainCuddlecakes** [AshleyMoni/Lancer-Community-Edition#854]
The Problem:
Gauntlet SITREP has conflicting Victory condition information:

> VICTORY CONDITIONS
> • PC Victory: At the end of the eighth round, there
> are more PCs inside the CZ than there are enemy
> characters. Ultras count as 4 characters, elites
> count as 2, and grunts count as 1/4.
> • Enemy Victory: At the end of the sixth round,
> there are at least as many enemy characters
> inside the CZ as there are PCs.

This changed from Prerelease 2, where both victory conditions were 6 rounds.

The Solution:
Need dev confirmation if victory conditions trigger at end of 6 rounds or 8 rounds, and correction of the PC or Enemy Victory condition.

The Location:
p. 271 in January release

**Comment by Jay-Iles** [comment]
Fixed - both trigger at the end of the 8th round.
