### ISSUE TITLE
[Typo] Nelson Skirmish Trait Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#856]
**The Problem:**
The Nelson's Skirmisher Trait currently reads "After attacking, the Nelson can move 1 space in any direction **as a free action** as long as it isn’t IMMOBILIZED or SLOWED. This movement ignores
engagement and doesn’t provoke reactions."

Strictly speaking, the Nelson's Skirmisher movement wasn't ever really a free action. It's meant, per Tom, to be interwoven between individual attack rolls even within a Skirmish or Barrage, which is something a free action strictly speaking can't do (since actions don't usually get broken up by other actions).

**The Solution:**
Two possible solutions here:

1). Just remove "as a free action," which takes it back to a PRv2 similar formatting.

2). Use language similar to Duelist 3, i.e. "After attacking, the Nelson can **immediately** move 1 space in any direction as a free action as long as it isn’t IMMOBILIZED or SLOWED. This movement ignores engagement and doesn’t provoke reactions."

The former would permit the Nelson to use its trait during off-turn attacks such as Overwatch. The latter would not. You can check with Tom to see which one of these he might prefer.

**The Location:**
Page 140

**Comment by KaiTave** [comment]
Actually something I've noticed is the rules no longer even clearly state "Actions and reactions themselves cannot be split into parts, and each action must resolve before the next takes effect." the way it used to in the PRv2. Did this get dropped altogether? Should actions still remain inviolable or is the idea that free actions and such can now just freely interweave between other actions now without restriction? I don't know! I would like to hear Tom's thoughts on this.

**Comment by Jay-Iles** [comment]
We went with:  "After attacking, the Nelson can immediately move 1 space in any direction as a free action as long as it isn’t IMMOBILIZED or SLOWED. This movement ignores engagement and doesn’t provoke reactions."
