### ISSUE TITLE
[Typo] Spacer Template Concussion Gun Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#858]
**The Problem:**
The Spacer NPC Template's Concussion Gun deals no damage, but it doesn't say "No Damage" in the statblock, similar to how the Gravity Rifle's statblock is set up.

**The Solution:**
For stylistic consistency, the Concussion Gun should probably be laid out similarly to the Gravity Rifle, i.e.:

Main Rifle, Knockback 3, +1/+2/+3 
[Cone 3] [no damage]

**The Location:**
Page 329

**Comment by Jay-Iles** [comment]
Fixed.
