### ISSUE TITLE
[RAI] January Release: Environment Tables and Save Targets

### ISSUE THREAD

**Issue by Eldraen** [AshleyMoni/Lancer-Community-Edition#859]
**The Problem:**
Several environmental hazards on the environment page list rolls that call for saves, however there is no save target in any of these pages for either of those rolls.

**The Solution:**
Either change the word from save to check, making rolls succeed on a 10+, or put in save targets for every environmental hazards that call out for saves.

**The Location:**
Page 278-279, the following call out for saves:
1- Dangerous Fauna or Flora
2- Extreme Cold
8- Electrical Storms
12- Earthquakes
19- Sinking World

**Comment by KaiTave** [comment]
They should be checks not saves, as per the PRv2. This is a typo and not an intended rules change.

**Comment by Jay-Iles** [comment]
Fixed.
