### ISSUE TITLE
[Typo] Unnecessary Capitalization in Harrison Armory Core Bonuses

### ISSUE THREAD

**Issue by extremeradical** [AshleyMoni/Lancer-Community-Edition#86]
**The Problem:**
Every HA core bonus is capitalized, (except for HEATFALL Coolant System) breaking with the style of the other four foundries. 

**The Solution:**
Normal capitalization, with a possible exception for the word HEATFALL.

**The Location:**
262-263

**Comment by KaiTave** [comment]
Inconsistent capitalization of core bonuses is still a thing and may merit formatting consideration for final print version.

**Comment by melodycwatson** [comment]
Fixed. :)
