### ISSUE TITLE
[Typo] Hacker/Spec Ops backgrounds refer to "Act Unseen and Unheard", but Example Triggers mentions "Act Unseen or Unheard"

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#860]
**The Problem:**
In the list of backgrounds, each background lists four example triggers that might be associated with it. The backgrounds Hacker (p. 22) and Spec Ops (p. 24) reference "Act Unseen and Unheard" as an example trigger. 

However, in the Example Triggers list on p. 26, the actual name of the trigger is listed as "Act Unseen or Unheard".

(This seems to be an error that has gone unnoticed since the pre-release versions.)

**The Solution:**
I'm not positive which one is correct, but I'm guessing it's the version listed in the Trigger list.

As such, if the example triggers for Hacker and Spec Ops are incorrectly named, the fix is to change the trigger's name as mentioned in the example triggers to "Act Unseen or Unheard".

**The Location:**
Lancer Core Book, Hacker and Spec Ops backgrounds on p. 22-24. This is true of both the Free and Premium PDFs as of the February 2nd 2020 release (as well as older versions).

**Comment by Jay-Iles** [comment]
Fixed.
