### ISSUE TITLE
[Typo] Hack or Fix trigger description has unitalicized text

### ISSUE THREAD

**Issue by V2Blast** [AshleyMoni/Lancer-Community-Edition#861]
**The Problem:**
On p. 26, the description of the Hack or Fix trigger is formatted as follows:

> _Repair a device or faulty system; alternatively, hack it wide open, or totally wreck, disable or sabotage it._ You’re probably hacking or fixing when accessing or safeguarding secure electronic systems, including electronic door locks, computer systems, omninet servers, and so on.

The second full sentence is strangely unitalicized. It's strange because literally all of the text in all the other trigger descriptions is italicized.

**The Solution:**
Just italicize it all:

> _Repair a device or faulty system; alternatively, hack it wide open, or totally wreck, disable or sabotage it. You’re probably hacking or fixing when accessing or safeguarding secure electronic systems, including electronic door locks, computer systems, omninet servers, and so on._

**The Location:**
Core Book, p. 26, top right, under the description of "Hack or Fix". The problem appears in both the Free and Premium PDFs, in all release versions up to the February 2nd 2020 release.

**Comment by Jay-Iles** [comment]
Fixed.
