### ISSUE TITLE
[Typo] March Update: Hound/Atlas Missiles and Wolfhound Missile Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#862]
**The Problem:**
Both the Rainmaker's Hound Missiles and the Ultra template's Wolfhound Missiles are largely identical systems but the Hound uses Burst iconography while the Wolfhound uses Blast.

**The Solution:**
These should both be consistent. While the PRv2 used Blast for both, using Burst actually does make sense given that the explosion is centered on the missile itself similar to how mines work. I would most likely consider using Burst for both the Hound and Wolfhound, but you may want to double check with Tom on the matter.

The Rainmaker's Atlas Missiles also have a similar discrepancy with something like the Scout's Orbital Bombardment system where one designates a point and creates a Burst 2 and one designates a point and creates a Blast 2. Per the PRv2 at least, the Atlas Missile should be a Burst 2 most likely.

**The Location:**
Pages 309, 331

**Comment by Jay-Iles** [comment]
Now both are bursts.
