### ISSUE TITLE
[Typo] Operator NPC Telefrag Clarification

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#864]
**The Problem:**
The Operator's optional Telefrag system isn't clear as to whether the target should be Jammed on a successful save, as it only says they take half damage on a successful save, unlike other similar systems (such as the Mercenary's Favors Owed which specifies that the additional prone effect doesn't work on a success.)

**The Solution:**
Per Tom, on a successful save the target is not Jammed, i.e. "On a successful save, they take half
damage and are not Jammed."

**The Location:**
Page 306

**Comment by Jay-Iles** [comment]
Fixed.
