### ISSUE TITLE
[Typo] Minor Wording error in Black Thumb skill level 2.

### ISSUE THREAD

**Issue by unde2aker** [AshleyMoni/Lancer-Community-Edition#867]
**The Problem:**
Wording error in black thumb skill level 2. quoted wording mistake "You are become a valid target"

**The Solution:**
"You become a valid target"

**The Location:**
PG. 34 in Long Rim PDF
![unknown](https://user-images.githubusercontent.com/61846837/76016363-4b780c80-5ee2-11ea-87db-1e21e898a2a4.png)

**Comment by melodycwatson** [comment]
Noted and fixed. :)
