### ISSUE TITLE
[RAI/Flavor] Barbarossa: Flak Launcher

### ISSUE THREAD

**Issue by Nitroxylin** [AshleyMoni/Lancer-Community-Edition#869]
**The Problem:**
The flak launcher is... strange flavor-wise, possibly as a holdover from previous editions when it was an actual weapon. The name screams it's a weapon, the flavor screams it's a weapon, yet it's not.

**The Solution:**
The proper course might be to rename it entirely, dropping every hint of it being a cannon, a launcher, flak-based, and everything similar; perhaps to make it some sort of a tractor beam good only for driving flying vehicles off-course and into the ground.

**The Location:**
(p. 229)

**Comment by KaiTave** [comment]
Given that the book is in the process of being printed, changes of this sort at this juncture are highly unlikely.

**Comment by Nitroxylin** [comment]
Understandable.

**Comment by KaiTave** [comment]
As this issue is unlikely to progress any further given the fact that the book is in production, I'm going to go ahead and close this ticket.
