### ISSUE TITLE
[Typo] Different Ways of Introducting Lists of Mechs

### ISSUE THREAD

**Issue by extremeradical** [AshleyMoni/Lancer-Community-Edition#87]
**The Problem:**
Beginning the list of mechs for every manufacturer is slightly different. IPS-N begins with `IPS-N Mech FRAMEs:` (without an extra line break) SSC starts with `SSC Mechs:` HORUS goes with`HORUS mechs:`(in bold) while Harrison Armory is `HARRISON ARMORY MECHS:`

**The Solution:**
Keep them all to a standard, based off of the SSC entry. 

**The Location:**
149, 185, 219, 257

**Comment by KaiTave** [comment]
This formatting seems to have been eliminated as of the prerelease.
