### ISSUE TITLE
[RAI] IPS-N Kidd: Recycle clarification

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#905]
**The Problem:**
This seems to be an acknowledged issue, but just figured it's safer to be redundant than have it missed: The wording for Recycle is unclear as to how often it can restore a limited charge (per use of Re-Route Power during a scene vs 1/scene), and when that restoration takes place (reads as though it happens immediately, but doesn't seem to be intent).

**The Solution:**
From what I'm told, the intent is once a scene, if Re-Route Power is used at least once, the limited charge is restored at the end of the scene. Therefore wording like this should work: "If the Kidd used Re-Route power at least once in any scene, it gets +1 limited charge back to a system of its choice with the drone or deployable tag at the end of that scene."

**The Location:**
page 3

**Comment by KaiTave** [comment]
I believe this issue has been resolved, but also as the Kidd is now Wallflower content any tickets regarding it should be appended to the Wallflower specific tracker.
