### ISSUE TITLE
[RAI]IPS-N Kidd, Long Rim: PEBCAC and Antilinear Time vs. Jammed 

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#911]
**The Problem:**
PEBCAC and Antilinear Time are both Tech actions that could theoretically clear Jammed (PEBCAC ends all effects caused by tech actions, which might include Jammed and Antilinear Time clears all conditions except for Stunned, of which Jammed is one.) However, Jammed itself says that "Jammed characters can't... benefit from tech actions."

**The Solution:**
Are these two effects intended to be able to remove Jammed? If so, it might be necessary to explicitly make it so. There might be different answers to this question for each of the effects, so it would be important to check intent for both separately.

If these effects are not intended to be able to remove Jammed, reminder text might be appropriate. Additionally, it might help to add Jammed to the list of exceptions that Antilinear Time can't clear alongside Stunned.

**The Location:**
long rim page 56, wallflower preview document

**Comment by KaiTave** [comment]
Closing this since the Kidd is Wallflower content, and if this remains an issue it most likely belongs on the Wallflower ticket tracker (my personal take is that Jammed still winds up preventing the use of PEBCAC in cases such as this).
