### ISSUE TITLE
[Typo] Point Defense Drone Lacks Drone Tag

### ISSUE THREAD

**Issue by squallevoker** [AshleyMoni/Lancer-Community-Edition#92]
**The Problem:**
The current text does not properly tag the point defense drone as a drone, despite the description and function of the system being congruent with other drones.  

Current text:
"Point Defense Drone
_PDWs are mainstays in stellar navies, used to engage with and destroy incoming missiles and torpedoes. On a mech core, PDWs adopt the same role and then some, engaging not only incoming ordnance (missiles, FRAMEs), but nearby hostile soft targets as well._

_2 SP_
_Quick Action_
You can fire this drone to any free space in sensor range, where it hovers in place and creates a burst 1 area centered on the drone. Attacks against yourself or allied actors in the area that deal explosive damage or have the nexus, smart, or launcher tags attack with +2 difficulty."

**The Solution:**
"Point Defense Drone
_PDWs are mainstays in stellar navies, used to engage with and destroy incoming missiles and torpedoes. On a mech core, PDWs adopt the same role and then some, engaging not only incoming ordnance (missiles, FRAMEs), but nearby hostile soft targets as well._

_2 SP_
_Drone, Quick Action_
You can fire this drone to any free space in sensor range, where it hovers in place and creates a burst 1 area centered on the drone. Attacks against yourself or allied actors in the area that deal explosive damage or have the nexus, smart, or launcher tags attack with +2 difficulty."

**The Location:**
Page 240

**The Ratification:**
Just something I noticed.

**Comment by KaiTave** [comment]
Point Defense Drone no longer exists in 1.8.5
