### ISSUE TITLE
[Typo]

### ISSUE THREAD

**Issue by Kidneyslayer** [AshleyMoni/Lancer-Community-Edition#948]
**The Problem:**
Used the word "Hysterical" in the wallflower module

**The Solution:**
Should use a term like "mass panic" as hysterical is a misogynist term.

**The Location:**
No Room for a Wallflower: Act 1, page 14, paragraph 3.

**Comment by KaiTave** [comment]
This tracker, insofar as it's used for anything, is for core rulebook and Long Rim material. Wallflower has its own tracker located here.

https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues
