### ISSUE TITLE
[Typo] Danger Zone Parenthetical Rewrite

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#95]
**The Problem:**
Several instances throughout the text refer to the Danger Zone as "the bottom half of your heat gauge" which is vaguely at odds with both the accumulative nature of heat as well as the actual definition of what the Danger Zone is.

**The Solution:**
Replace "(the bottom half of your heat gauge)" with "(when your mech has 1/2 its total heat capacity filled)"

**The Location:**
Page 128, 248

**Comment by KaiTave** [comment]
There are still some references to the "bottom half of your heat gauge" in the 1.8.5 text that should be looked at.

**Comment by lenaleciel** [comment]
Current locations in 1.8.5 are under rank I of Nuclear Cavalier, (page 142) and Lightning Generator (page 256)

**Comment by KaiTave** [comment]
This appears to have been amended in the prerelease.
