### ISSUE TITLE
[Typo] Shock Knife Flavor Text Typo

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#98]
**The Problem:**
" the post-fabrication Shock **Wreathe** system"

**The Solution:**
 the post-fabrication Shock **Wreath** system

**The Location:**
Page 206

**Comment by KaiTave** [comment]
"Wreathe" and "Sheathe" with E's on the end appear in several places throughout the Lancer core rulebook and the IPS-N Zheng.  I've been taught that Wreath/Sheath without the E is a noun while Wreathe/Sheathe is a verb, but it's possible there's an international spelling convention I'm unfamiliar with.

**Comment by melodycwatson** [comment]
Melody here. This has now been noted and amended.
